In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
# 현재 Notebook Kernel이 실행 중인 위치
CURRENT_DIR = Path.cwd().resolve()

# .ipynb 파일이 notebooks 폴더 안에서 실행 중이면 상위 폴더를 프로젝트 루트로 사용
if CURRENT_DIR.name == "notebooks":
    BASE_DIR = CURRENT_DIR.parent
else:
    BASE_DIR = CURRENT_DIR
RAW_DIR = BASE_DIR / "data" / "raw"
RAW_PATH = RAW_DIR / "customers_raw.csv"
print("RAW_PATH:", RAW_PATH)
print("exists:", RAW_PATH.exists())

RAW_PATH: /home/soldesk/ai-hybrid-lab-kim-juil/data/raw/customers_raw.csv
exists: True

In [3]:
df = pd.read_csv(RAW_PATH)
df.head()

,customer_id,age,gender,monthly_fee,contract_type,usage_days,support_calls,churn
0,C001,34.0,F,59000.0,monthly,120,1,0
1,C002,45.0,M,79000.0,yearly,380,3,1
2,C003,NaN,F,NaN,monthly,45,0,0
3,C004,52.0,M,99000.0,yearly,800,5,1
4,C005,41.0,F,69000.0,NaN,220,2,0

In [4]:
df.head()
df.tail()

,customer_id,age,gender,monthly_fee,contract_type,usage_days,support_calls,churn
5,C005,41.0,F,69000.0,NaN,220,2,0
6,C006,37.0,M,72000.0,monthly,90,4,0
7,C007,58.0,F,110000.0,yearly,1000,6,1
8,C008,23.0,NaN,45000.0,monthly,15,0,0
9,C009,63.0,M,120000.0,yearly,1100,7,1

In [5]:
df.shape

(10, 8)

In [6]:
df.columns
for col in df.columns:
    print(col)

customer_id
age
gender
monthly_fee
contract_type
usage_days
support_calls
churn

In [7]:
df.dtypes

customer_id          str
age              float64
gender               str
monthly_fee      float64
contract_type        str
usage_days         int64
support_calls      int64
churn              int64
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    10 non-null     str
 1   age            9 non-null      float64
 2   gender         9 non-null      str
 3   monthly_fee    9 non-null      float64
 4   contract_type  8 non-null      str
 5   usage_days     10 non-null     int64
 6   support_calls  10 non-null     int64
 7   churn          10 non-null     int64
dtypes: float64(2), int64(3), str(3)
memory usage: 877.0 bytes

In [9]:
missing_count = df.isnull().sum()
missing_count

customer_id      0
age              1
gender           1
monthly_fee      1
contract_type    2
usage_days       0
support_calls    0
churn            0
dtype: int64

In [10]:
missing_ratio = df.isnull().mean() * 100
missing_ratio

customer_id       0.0
age              10.0
gender           10.0
monthly_fee      10.0
contract_type    20.0
usage_days        0.0
support_calls     0.0
churn             0.0
dtype: float64

In [11]:
missing_summary = pd.DataFrame({
    "missing_count": missing_count,
    "missing_ratio_percent": missing_ratio
}).sort_values("missing_count", ascending=False)
missing_summary

               missing_count  missing_ratio_percent
contract_type              2                   20.0
age                        1                   10.0
monthly_fee                1                   10.0
gender                     1                   10.0
customer_id                0                    0.0
usage_days                 0                    0.0
support_calls              0                    0.0
churn                      0                    0.0

In [12]:
duplicate_count = df.duplicated().sum()
duplicate_count

np.int64(1)

In [13]:
df[df.duplicated(keep=False)]

,customer_id,age,gender,monthly_fee,contract_type,usage_days,support_calls,churn
4,C005,41.0,F,69000.0,NaN,220,2,0
5,C005,41.0,F,69000.0,NaN,220,2,0

In [14]:
df.describe()
df.describe(include="all")

,customer_id,age,gender,monthly_fee,contract_type,usage_days,support_calls,churn
count,10,9.000000,9,9.000000,8,10.000000,10.00000,10.000000
unique,9,NaN,2,NaN,2,NaN,NaN,NaN
top,C005,NaN,F,NaN,monthly,NaN,NaN,NaN
freq,2,NaN,5,NaN,4,NaN,NaN,NaN
mean,NaN,43.777778,NaN,80222.222222,NaN,399.000000,3.00000,0.400000
std,NaN,12.397356,NaN,24580.367053,NaN,411.493216,2.44949,0.516398
min,NaN,23.000000,NaN,45000.000000,NaN,15.000000,0.00000,0.000000
25%,NaN,37.000000,NaN,69000.000000,NaN,97.500000,1.25000,0.000000
50%,NaN,41.000000,NaN,72000.000000,NaN,220.000000,2.50000,0.000000
75%,NaN,52.000000,NaN,99000.000000,NaN,695.000000,4.75000,1.000000
max,NaN,63.000000,NaN,120000.000000,NaN,1100.000000,7.00000,1.000000

In [15]:
df["contract_type"].value_counts(dropna=False)

contract_type
monthly    4
yearly     4
NaN        2
Name: count, dtype: int64

In [16]:
df["gender"].value_counts(dropna=False)

gender
F      5
M      4
NaN    1
Name: count, dtype: int64

In [17]:
df["churn"].value_counts(dropna=False)

churn
0    6
1    4
Name: count, dtype: int64

In [18]:
df.head()

,customer_id,age,gender,monthly_fee,contract_type,usage_days,support_calls,churn
0,C001,34.0,F,59000.0,monthly,120,1,0
1,C002,45.0,M,79000.0,yearly,380,3,1
2,C003,NaN,F,NaN,monthly,45,0,0
3,C004,52.0,M,99000.0,yearly,800,5,1
4,C005,41.0,F,69000.0,NaN,220,2,0

In [19]:
df.tail()

,customer_id,age,gender,monthly_fee,contract_type,usage_days,support_calls,churn
5,C005,41.0,F,69000.0,NaN,220,2,0
6,C006,37.0,M,72000.0,monthly,90,4,0
7,C007,58.0,F,110000.0,yearly,1000,6,1
8,C008,23.0,NaN,45000.0,monthly,15,0,0
9,C009,63.0,M,120000.0,yearly,1100,7,1

In [20]:
churn_rate = df["churn"].mean()
print("이탈률:", churn_rate)

이탈률: 0.4

In [21]:
churn_rate = df["churn"].mean()
print("이탈률:", churn_rate)

이탈률: 0.4

In [22]:
observation_summary = {
    "author": "student",
    "data_file": str(RAW_PATH),
    "row_count": int(df.shape[0]),
    "column_count": int(df.shape[1]),
    "columns": list(df.columns),
    "dtypes": {col: str(dtype) for col, dtype in df.dtypes.items()},
    "missing_columns": list(missing_summary[missing_summary["missing_count"] > 0].index),
    "missing_summary": {
        col: {
            "missing_count": int(missing_summary.loc[col, "missing_count"]),
            "missing_ratio_percent": float(missing_summary.loc[col, "missing_ratio_percent"])
        }
        for col in missing_summary.index
    },
    "duplicate_count": int(duplicate_count),
    "target_column": "churn",
    "id_column": "customer_id",
    "churn_rate": float(churn_rate),
    "g4dn_used": False,
    "openshift_deploy_used": False,
    "note": "Day 1 6교시는 pandas로 raw 데이터를 읽고 관찰하는 실습"
}
observation_summary

{'author': 'student',
 'data_file': '/home/soldesk/ai-hybrid-lab-kim-juil/data/raw/customers_raw.csv',
 'row_count': 10,
 'column_count': 8,
 'columns': ['customer_id',
  'age',
  'gender',
  'monthly_fee',
  'contract_type',
  'usage_days',
  'support_calls',
  'churn'],
 'dtypes': {'customer_id': 'str',
  'age': 'float64',
  'gender': 'str',
  'monthly_fee': 'float64',
  'contract_type': 'str',
  'usage_days': 'int64',
  'support_calls': 'int64',
  'churn': 'int64'},
 'missing_columns': ['contract_type', 'age', 'monthly_fee', 'gender'],
 'missing_summary': {'contract_type': {'missing_count': 2,
   'missing_ratio_percent': 20.0},
  'age': {'missing_count': 1, 'missing_ratio_percent': 10.0},
  'monthly_fee': {'missing_count': 1, 'missing_ratio_percent': 10.0},
  'gender': {'missing_count': 1, 'missing_ratio_percent': 10.0},
  'customer_id': {'missing_count': 0, 'missing_ratio_percent': 0.0},
  'usage_days': {'missing_count': 0, 'missing_ratio_percent': 0.0},
  'support_calls': {'missing_count': 0, 'missing_ratio_percent': 0.0},
  'churn': {'missing_count': 0, 'missing_ratio_percent': 0.0}},
 'duplicate_count': 1,
 'target_column': 'churn',
 'id_column': 'customer_id',
 'churn_rate': 0.4,
 'g4dn_used': False,
 'openshift_deploy_used': False,
 'note': 'Day 1 6교시는 pandas로 raw 데이터를 읽고 관찰하는 실습'}

In [23]:
import json
OUTPUT_DIR = Path("outputs") / "week2"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_PATH = OUTPUT_DIR / "day1_data_observation_summary.json"
with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    json.dump(observation_summary, f, ensure_ascii=False, indent=2)
print("saved:", OUTPUT_PATH)

saved: outputs/week2/day1_data_observation_summary.json

In [24]:
from pathlib import Path
import json

# 현재 Notebook 실행 위치 확인
CURRENT_DIR = Path.cwd()

# Notebook이 notebooks 디렉터리 안에서 실행되는 경우
# 예: project-root/notebooks
if CURRENT_DIR.name == "notebooks":
    PROJECT_ROOT = CURRENT_DIR.parent
else:
    PROJECT_ROOT = CURRENT_DIR

# 프로젝트 루트 하위 outputs/week2 디렉터리
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "week2"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# 저장 파일 경로
OUTPUT_PATH = OUTPUT_DIR / "day1_data_observation_summary.json"

# JSON 저장
with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    json.dump(observation_summary, f, ensure_ascii=False, indent=2)

print("current dir:", CURRENT_DIR)
print("project root:", PROJECT_ROOT)
print("saved:", OUTPUT_PATH)

current dir: /home/soldesk/ai-hybrid-lab-kim-juil/notebooks
project root: /home/soldesk/ai-hybrid-lab-kim-juil
saved: /home/soldesk/ai-hybrid-lab-kim-juil/outputs/week2/day1_data_observation_summary.json

In [25]:
print(OUTPUT_PATH.exists())

True

In [26]:
df_clean.head()

NameError: name 'df_clean' is not defined

In [27]:
df_clean = df.copy()

In [28]:
df_clean.head()

,customer_id,age,gender,monthly_fee,contract_type,usage_days,support_calls,churn
0,C001,34.0,F,59000.0,monthly,120,1,0
1,C002,45.0,M,79000.0,yearly,380,3,1
2,C003,NaN,F,NaN,monthly,45,0,0
3,C004,52.0,M,99000.0,yearly,800,5,1
4,C005,41.0,F,69000.0,NaN,220,2,0

In [29]:
duplicate_count = df_clean.duplicated().sum()

In [30]:
duplicate_count

np.int64(1)

In [31]:
df_clean[df_clean.duplicated(keep=False)]

,customer_id,age,gender,monthly_fee,contract_type,usage_days,support_calls,churn
4,C005,41.0,F,69000.0,NaN,220,2,0
5,C005,41.0,F,69000.0,NaN,220,2,0

In [32]:
before_rows = len(df_clean)
df_clean = df_clean.drop_duplicates().copy()
after_rows = len(df_clean)
print("중복 제거 전 행 수:", before_rows)
print("중복 제거 후 행 수:", after_rows)
print("제거된 행 수:", before_rows - after_rows)

중복 제거 전 행 수: 10
중복 제거 후 행 수: 9
제거된 행 수: 1

In [33]:
df_clean.isnull().sum()

customer_id      0
age              1
gender           1
monthly_fee      1
contract_type    1
usage_days       0
support_calls    0
churn            0
dtype: int64

In [34]:
age_median = df_clean["age"].median()
monthly_fee_median = df_clean["monthly_fee"].median()
df_clean["age"] = df_clean["age"].fillna(age_median)
df_clean["monthly_fee"] = df_clean["monthly_fee"].fillna(monthly_fee_median)
print("age median:", age_median)
print("monthly_fee median:", monthly_fee_median)

age median: 43.0
monthly_fee median: 75500.0

In [35]:
df_clean["gender"] = df_clean["gender"].fillna("unknown")

In [36]:
df_clean["contract_type"] = df_clean["contract_type"].fillna("unknown")

In [37]:
df_clean.isnull().sum()

customer_id      0
age              0
gender           0
monthly_fee      0
contract_type    0
usage_days       0
support_calls    0
churn            0
dtype: int64

In [38]:
selected_cols = [
    "customer_id",
    "age",
    "gender",
    "monthly_fee",
    "contract_type",
    "usage_days",
    "support_calls",
    "churn"
]
df_selected = df_clean[selected_cols]
df_selected.head()

,customer_id,age,gender,monthly_fee,contract_type,usage_days,support_calls,churn
0,C001,34.0,F,59000.0,monthly,120,1,0
1,C002,45.0,M,79000.0,yearly,380,3,1
2,C003,43.0,F,75500.0,monthly,45,0,0
3,C004,52.0,M,99000.0,yearly,800,5,1
4,C005,41.0,F,69000.0,unknown,220,2,0

In [39]:
usage_over_30 = df_clean[df_clean["usage_days"] >= 30]
usage_over_30.head()

,customer_id,age,gender,monthly_fee,contract_type,usage_days,support_calls,churn
0,C001,34.0,F,59000.0,monthly,120,1,0
1,C002,45.0,M,79000.0,yearly,380,3,1
2,C003,43.0,F,75500.0,monthly,45,0,0
3,C004,52.0,M,99000.0,yearly,800,5,1
4,C005,41.0,F,69000.0,unknown,220,2,0

In [40]:
high_fee_customers = df_clean[df_clean["monthly_fee"] >= 50000]
high_fee_customers.head()

,customer_id,age,gender,monthly_fee,contract_type,usage_days,support_calls,churn
0,C001,34.0,F,59000.0,monthly,120,1,0
1,C002,45.0,M,79000.0,yearly,380,3,1
2,C003,43.0,F,75500.0,monthly,45,0,0
3,C004,52.0,M,99000.0,yearly,800,5,1
4,C005,41.0,F,69000.0,unknown,220,2,0

In [41]:
churn_customers = df_clean[df_clean["churn"] == 1]
churn_customers.head()

,customer_id,age,gender,monthly_fee,contract_type,usage_days,support_calls,churn
1,C002,45.0,M,79000.0,yearly,380,3,1
3,C004,52.0,M,99000.0,yearly,800,5,1
7,C007,58.0,F,110000.0,yearly,1000,6,1
9,C009,63.0,M,120000.0,yearly,1100,7,1

In [42]:
df_clean["is_high_fee"] = (df_clean["monthly_fee"] >= 70000).astype(int)
df_clean[["customer_id", "monthly_fee", "is_high_fee"]].head()

  customer_id  monthly_fee  is_high_fee
0        C001      59000.0            0
1        C002      79000.0            1
2        C003      75500.0            1
3        C004      99000.0            1
4        C005      69000.0            0

In [43]:
def make_usage_group(days):
    if days < 90:
        return "short"
    elif days < 365:
        return "middle"
    else:
        return "long"
df_clean["usage_group"] = df_clean["usage_days"].apply(make_usage_group)
df_clean[["customer_id", "usage_days", "usage_group"]].head()

  customer_id  usage_days usage_group
0        C001         120      middle
1        C002         380        long
2        C003          45       short
3        C004         800        long
4        C005         220      middle

In [44]:
summary_fee = (
    df_clean
    .groupby("contract_type")["monthly_fee"]
    .mean()
    .reset_index()
)
summary_fee

  contract_type  monthly_fee
0       monthly      62875.0
1       unknown      69000.0
2        yearly     102000.0

In [45]:
summary_churn = (
    df_clean
    .groupby("contract_type")["churn"]
    .mean()
    .reset_index()
)
summary_churn = summary_churn.rename(columns={
    "churn": "churn_rate"
})
summary_churn

  contract_type  churn_rate
0       monthly         0.0
1       unknown         0.0
2        yearly         1.0

In [46]:
usage_churn = (
    df_clean
    .groupby("usage_group")["churn"]
    .mean()
    .reset_index()
)
usage_churn = usage_churn.rename(columns={
    "churn": "churn_rate"
})
usage_churn["churn_rate_percent"] = usage_churn["churn_rate"] * 100
usage_churn

  usage_group  churn_rate  churn_rate_percent
0        long         1.0               100.0
1      middle         0.0                 0.0
2       short         0.0                 0.0

In [47]:
contract_summary = (
    df_clean
    .groupby("contract_type")
    .agg(
        customer_count=("customer_id", "count"),
        avg_monthly_fee=("monthly_fee", "mean"),
        churn_rate=("churn", "mean")
    )
    .reset_index()
)
contract_summary

  contract_type  customer_count  avg_monthly_fee  churn_rate
0       monthly               4          62875.0         0.0
1       unknown               1          69000.0         0.0
2        yearly               4         102000.0         1.0

In [48]:
from pathlib import Path

# 현재 Notebook 실행 기준 디렉터리
CURRENT_DIR = Path.cwd()

# 현재 위치가 notebooks 디렉터리라면 한 단계 위를 프로젝트 루트로 사용
if CURRENT_DIR.name == "notebooks":
    PROJECT_ROOT = CURRENT_DIR.parent
else:
    PROJECT_ROOT = CURRENT_DIR

# 프로젝트 루트 하위 data/clean 디렉터리
CLEAN_DIR = PROJECT_ROOT / "data" / "clean"
CLEAN_DIR.mkdir(parents=True, exist_ok=True)

# 저장 파일 경로
CLEAN_CANDIDATE_PATH = CLEAN_DIR / "customers_clean_candidate.csv"

# CSV 저장
df_clean.to_csv(CLEAN_CANDIDATE_PATH, index=False)

print("current dir:", CURRENT_DIR)
print("project root:", PROJECT_ROOT)
print("saved:", CLEAN_CANDIDATE_PATH)
print("exists:", CLEAN_CANDIDATE_PATH.exists())

current dir: /home/soldesk/ai-hybrid-lab-kim-juil/notebooks
project root: /home/soldesk/ai-hybrid-lab-kim-juil
saved: /home/soldesk/ai-hybrid-lab-kim-juil/data/clean/customers_clean_candidate.csv
exists: True

In [49]:
import json
from pathlib import Path
basic_processing_summary = {
    "author": "student",
    "input_raw_path": "data/raw/customers_raw.csv",
    "clean_candidate_path": str(CLEAN_CANDIDATE_PATH),
    "raw_rows": int(len(df)),
    "clean_rows": int(len(df_clean)),
    "removed_duplicates": int(len(df) - len(df_clean)),
    "numeric_missing_strategy": {
        "age": "median",
        "monthly_fee": "median"
    },
    "categorical_missing_strategy": {
        "gender": "unknown",
        "contract_type": "unknown"
    },
    "missing_after_processing": df_clean.isnull().sum().to_dict(),
    "selected_columns": selected_cols,
    "created_columns": [
        "is_high_fee",
        "usage_group"
    ],
    "groupby_outputs": {
        "summary_fee_rows": int(len(summary_fee)),
        "summary_churn_rows": int(len(summary_churn)),
        "usage_churn_rows": int(len(usage_churn)),
        "contract_summary_rows": int(len(contract_summary))
    },
    "g4dn_used": False,
    "openshift_deploy_used": False,
    "note": "Day 1 7교시는 raw를 보호하고 df_clean에서 기본 처리한 clean 후보 생성 실습"
}
OUTPUT_DIR = Path("outputs") / "week2"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_PATH = OUTPUT_DIR / "day1_basic_processing_summary.json"
with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    json.dump(basic_processing_summary, f, ensure_ascii=False, indent=2)
print("saved:", OUTPUT_PATH)
basic_processing_summary

saved: outputs/week2/day1_basic_processing_summary.json

{'author': 'student',
 'input_raw_path': 'data/raw/customers_raw.csv',
 'clean_candidate_path': '/home/soldesk/ai-hybrid-lab-kim-juil/data/clean/customers_clean_candidate.csv',
 'raw_rows': 10,
 'clean_rows': 9,
 'removed_duplicates': 1,
 'numeric_missing_strategy': {'age': 'median', 'monthly_fee': 'median'},
 'categorical_missing_strategy': {'gender': 'unknown',
  'contract_type': 'unknown'},
 'missing_after_processing': {'customer_id': 0,
  'age': 0,
  'gender': 0,
  'monthly_fee': 0,
  'contract_type': 0,
  'usage_days': 0,
  'support_calls': 0,
  'churn': 0,
  'is_high_fee': 0,
  'usage_group': 0},
 'selected_columns': ['customer_id',
  'age',
  'gender',
  'monthly_fee',
  'contract_type',
  'usage_days',
  'support_calls',
  'churn'],
 'created_columns': ['is_high_fee', 'usage_group'],
 'groupby_outputs': {'summary_fee_rows': 3,
  'summary_churn_rows': 3,
  'usage_churn_rows': 3,
  'contract_summary_rows': 3},
 'g4dn_used': False,
 'openshift_deploy_used': False,
 'note': 'Day 1 7교시는 raw를 보호하고 df_clean에서 기본 처리한 clean 후보 생성 실습'}

In [50]:
import json
from pathlib import Path

# 현재 Notebook 실행 기준 디렉터리
CURRENT_DIR = Path.cwd()

# 현재 위치가 notebooks 디렉터리라면 한 단계 위를 프로젝트 루트로 사용
if CURRENT_DIR.name == "notebooks":
    PROJECT_ROOT = CURRENT_DIR.parent
else:
    PROJECT_ROOT = CURRENT_DIR

basic_processing_summary = {
    "author": "student",
    "input_raw_path": "data/raw/customers_raw.csv",
    "clean_candidate_path": str(CLEAN_CANDIDATE_PATH),
    "raw_rows": int(len(df)),
    "clean_rows": int(len(df_clean)),
    "removed_duplicates": int(len(df) - len(df_clean)),
    "numeric_missing_strategy": {
        "age": "median",
        "monthly_fee": "median"
    },
    "categorical_missing_strategy": {
        "gender": "unknown",
        "contract_type": "unknown"
    },
    "missing_after_processing": df_clean.isnull().sum().to_dict(),
    "selected_columns": selected_cols,
    "created_columns": [
        "is_high_fee",
        "usage_group"
    ],
    "groupby_outputs": {
        "summary_fee_rows": int(len(summary_fee)),
        "summary_churn_rows": int(len(summary_churn)),
        "usage_churn_rows": int(len(usage_churn)),
        "contract_summary_rows": int(len(contract_summary))
    },
    "g4dn_used": False,
    "openshift_deploy_used": False,
    "note": "Day 1 7교시는 raw를 보호하고 df_clean에서 기본 처리한 clean 후보 생성 실습"
}

# 프로젝트 루트 하위 outputs/week2 디렉터리
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "week2"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# 저장 파일 경로
OUTPUT_PATH = OUTPUT_DIR / "day1_basic_processing_summary.json"

# JSON 저장
with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    json.dump(basic_processing_summary, f, ensure_ascii=False, indent=2)

print("current dir:", CURRENT_DIR)
print("project root:", PROJECT_ROOT)
print("saved:", OUTPUT_PATH)
print("exists:", OUTPUT_PATH.exists())

basic_processing_summary

current dir: /home/soldesk/ai-hybrid-lab-kim-juil/notebooks
project root: /home/soldesk/ai-hybrid-lab-kim-juil
saved: /home/soldesk/ai-hybrid-lab-kim-juil/outputs/week2/day1_basic_processing_summary.json
exists: True

{'author': 'student',
 'input_raw_path': 'data/raw/customers_raw.csv',
 'clean_candidate_path': '/home/soldesk/ai-hybrid-lab-kim-juil/data/clean/customers_clean_candidate.csv',
 'raw_rows': 10,
 'clean_rows': 9,
 'removed_duplicates': 1,
 'numeric_missing_strategy': {'age': 'median', 'monthly_fee': 'median'},
 'categorical_missing_strategy': {'gender': 'unknown',
  'contract_type': 'unknown'},
 'missing_after_processing': {'customer_id': 0,
  'age': 0,
  'gender': 0,
  'monthly_fee': 0,
  'contract_type': 0,
  'usage_days': 0,
  'support_calls': 0,
  'churn': 0,
  'is_high_fee': 0,
  'usage_group': 0},
 'selected_columns': ['customer_id',
  'age',
  'gender',
  'monthly_fee',
  'contract_type',
  'usage_days',
  'support_calls',
  'churn'],
 'created_columns': ['is_high_fee', 'usage_group'],
 'groupby_outputs': {'summary_fee_rows': 3,
  'summary_churn_rows': 3,
  'usage_churn_rows': 3,
  'contract_summary_rows': 3},
 'g4dn_used': False,
 'openshift_deploy_used': False,
 'note': 'Day 1 7교시는 raw를 보호하고 df_clean에서 기본 처리한 clean 후보 생성 실습'}