In [4]:
import sys
import pandas as pd
import numpy as np
from pathlib import Path

print("Python 실행 파일:", sys.executable)
print("Python 버전:", sys.version)
print("pandas 버전:", pd.__version__)
print("numpy 버전:", np.__version__)
print("현재 위치:", Path.cwd())

Python 실행 파일: /home/soldesk/week2-reproducibility/.venv/bin/python
Python 버전: 3.12.3 (main, Mar 23 2026, 19:04:32) [GCC 13.3.0]
pandas 버전: 3.0.3
numpy 버전: 2.5.0
현재 위치: /home/soldesk/week2-reproducibility/notebooks

In [5]:
import sys
import os
import platform
import json
from datetime import datetime
from pathlib import Path
import pandas as pd
import numpy as np
print("Python version:")
print(sys.version)
print("\nOS:")
print(platform.platform())
print("\nCurrent working directory:")
print(Path.cwd())
print("\npandas version:", pd.__version__)
print("numpy version:", np.__version__)

Python version:
3.12.3 (main, Mar 23 2026, 19:04:32) [GCC 13.3.0]

OS:
Linux-6.18.33.2-microsoft-standard-WSL2-x86_64-with-glibc2.39

Current working directory:
/home/soldesk/week2-reproducibility/notebooks

pandas version: 3.0.3
numpy version: 2.5.0

In [6]:
try:
    import sklearn
    sklearn_version = sklearn.__version__
except ImportError:
    sklearn_version = None
try:
    import pyarrow
    pyarrow_version = pyarrow.__version__
except ImportError:
    pyarrow_version = None
try:
    import dotenv
    python_dotenv_installed = True
except ImportError:
    python_dotenv_installed = False
print("scikit-learn:", sklearn_version)
print("pyarrow:", pyarrow_version)
print("python-dotenv installed:", python_dotenv_installed)

scikit-learn: 1.9.0
pyarrow: 24.0.0
python-dotenv installed: True

In [7]:
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
DATA_DIR = BASE_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
CLEAN_DIR = DATA_DIR / "clean"
FEATURE_DIR = DATA_DIR / "feature"
OUTPUT_DIR = BASE_DIR / "outputs"
REPORT_DIR = BASE_DIR / "reports" / "week2"
for path in [RAW_DIR, CLEAN_DIR, FEATURE_DIR, OUTPUT_DIR, REPORT_DIR]:
    path.mkdir(parents=True, exist_ok=True)
input_file = CLEAN_DIR / "customers_clean_20260606_v2.csv"
print("BASE_DIR:", BASE_DIR)
print("RAW_DIR:", RAW_DIR)
print("CLEAN_DIR:", CLEAN_DIR)
print("FEATURE_DIR:", FEATURE_DIR)
print("OUTPUT_DIR:", OUTPUT_DIR)
print("REPORT_DIR:", REPORT_DIR)
print("input_file:", input_file)

BASE_DIR: /home/soldesk/week2-reproducibility
RAW_DIR: /home/soldesk/week2-reproducibility/data/raw
CLEAN_DIR: /home/soldesk/week2-reproducibility/data/clean
FEATURE_DIR: /home/soldesk/week2-reproducibility/data/feature
OUTPUT_DIR: /home/soldesk/week2-reproducibility/outputs
REPORT_DIR: /home/soldesk/week2-reproducibility/reports/week2
input_file: /home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv

In [8]:
print("입력 파일 존재 여부:", input_file.exists())
if input_file.exists():
    print("입력 파일 크기:", input_file.stat().st_size, "bytes")
else:
    print("입력 파일이 없습니다. Day 2 clean v2 저장 결과를 확인하세요.")

입력 파일 존재 여부: True
입력 파일 크기: 1595 bytes

In [9]:
if input_file.exists():
    df_input = pd.read_csv(input_file)
    print("입력 데이터 shape:", df_input.shape)
    display(df_input.head())
else:
    df_input = None

입력 데이터 shape: (9, 29)

,customer_id,age,monthly_fee,usage_days,support_calls,gender_standard,contract_type_standard,signup_date,last_login_date,signup_year,...,monthly_fee_outlier,support_calls_outlier,is_high_fee,is_short_user,has_many_support_calls,usage_group,is_long_contract,churn,gender,contract_type
0,C001,34,59000,120,1,female,monthly,2025-01-10,2026-06-01,2025,...,0,0,1,0,0,middle,0,0,female,month-to-month
1,C002,45,79000,380,3,male,one_year,2024-12-01,2026-05-10,2024,...,0,0,1,0,1,long,1,1,male,1-year
2,C003,41,72000,45,0,female,monthly,2026-04-20,2026-06-03,2026,...,0,0,1,0,0,middle,0,0,female,month-to-month
3,C004,52,99000,800,5,male,one_year,2023-05-15,2026-03-01,2023,...,0,0,1,0,1,long,1,1,male,1-year
4,C005,41,69000,220,2,female,unknown,2025-08-03,2026-05-30,2025,...,0,0,1,0,0,middle,0,0,female,unknown

In [10]:
SEED = 42
print("SEED:", SEED)

SEED: 42

In [11]:
run_info = {
    "run_name": "week2_day3_reproducibility",
    "created_at": datetime.now().isoformat(),
    "python_version": sys.version,
    "os": platform.platform(),
    "cwd": str(Path.cwd()),
    "base_dir": str(BASE_DIR),
    "pandas_version": pd.__version__,
    "numpy_version": np.__version__,
    "sklearn_version": sklearn_version,
    "pyarrow_version": pyarrow_version,
    "python_dotenv_installed": python_dotenv_installed,
    "seed": SEED,
    "input_file": str(input_file),
    "input_file_exists": input_file.exists(),
    "input_row_count": int(df_input.shape[0]) if df_input is not None else None,
    "input_column_count": int(df_input.shape[1]) if df_input is not None else None,
    "output_dir": str(OUTPUT_DIR),
    "author": "student",
    "execution_environment": "local_wsl2",
    "openshift_local_used": False,
    "developer_sandbox_used": False,
    "g4dn_used": False,
    "h200_used": False,
    "note": "Day 3 period 2 reproducibility run info practice"
}
run_info

{'run_name': 'week2_day3_reproducibility',
 'created_at': '2026-06-29T10:42:41.556515',
 'python_version': '3.12.3 (main, Mar 23 2026, 19:04:32) [GCC 13.3.0]',
 'os': 'Linux-6.18.33.2-microsoft-standard-WSL2-x86_64-with-glibc2.39',
 'cwd': '/home/soldesk/week2-reproducibility/notebooks',
 'base_dir': '/home/soldesk/week2-reproducibility',
 'pandas_version': '3.0.3',
 'numpy_version': '2.5.0',
 'sklearn_version': '1.9.0',
 'pyarrow_version': '24.0.0',
 'python_dotenv_installed': True,
 'seed': 42,
 'input_file': '/home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv',
 'input_file_exists': True,
 'input_row_count': 9,
 'input_column_count': 29,
 'output_dir': '/home/soldesk/week2-reproducibility/outputs',
 'author': 'student',
 'execution_environment': 'local_wsl2',
 'openshift_local_used': False,
 'developer_sandbox_used': False,
 'g4dn_used': False,
 'h200_used': False,
 'note': 'Day 3 period 2 reproducibility run info practice'}

In [12]:
run_info_file = OUTPUT_DIR / "run_info.json"
with open(run_info_file, "w", encoding="utf-8") as f:
    json.dump(run_info, f, ensure_ascii=False, indent=2)
print("실행 기록 저장:", run_info_file)
print("저장 여부:", run_info_file.exists())

실행 기록 저장: /home/soldesk/week2-reproducibility/outputs/run_info.json
저장 여부: True

In [13]:
with open(run_info_file, "r", encoding="utf-8") as f:
    loaded_run_info = json.load(f)
loaded_run_info

{'run_name': 'week2_day3_reproducibility',
 'created_at': '2026-06-29T10:42:41.556515',
 'python_version': '3.12.3 (main, Mar 23 2026, 19:04:32) [GCC 13.3.0]',
 'os': 'Linux-6.18.33.2-microsoft-standard-WSL2-x86_64-with-glibc2.39',
 'cwd': '/home/soldesk/week2-reproducibility/notebooks',
 'base_dir': '/home/soldesk/week2-reproducibility',
 'pandas_version': '3.0.3',
 'numpy_version': '2.5.0',
 'sklearn_version': '1.9.0',
 'pyarrow_version': '24.0.0',
 'python_dotenv_installed': True,
 'seed': 42,
 'input_file': '/home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv',
 'input_file_exists': True,
 'input_row_count': 9,
 'input_column_count': 29,
 'output_dir': '/home/soldesk/week2-reproducibility/outputs',
 'author': 'student',
 'execution_environment': 'local_wsl2',
 'openshift_local_used': False,
 'developer_sandbox_used': False,
 'g4dn_used': False,
 'h200_used': False,
 'note': 'Day 3 period 2 reproducibility run info practice'}

In [14]:
print("run_name:", loaded_run_info["run_name"])
print("created_at:", loaded_run_info["created_at"])
print("input_file:", loaded_run_info["input_file"])
print("seed:", loaded_run_info["seed"])
print("author:", loaded_run_info["author"])
print("g4dn_used:", loaded_run_info["g4dn_used"])
print("openshift_local_used:", loaded_run_info["openshift_local_used"])

run_name: week2_day3_reproducibility
created_at: 2026-06-29T10:42:41.556515
input_file: /home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv
seed: 42
author: student
g4dn_used: False
openshift_local_used: False

In [15]:
run_record_file = OUTPUT_DIR / "reproducibility_run_record.md"
run_record_text = f"""# 2주차 Day 3 2교시 실행 기록
## 1. 작성자
{run_info["author"]}
## 2. 실행 이름
{run_info["run_name"]}
## 3. 실행 시각
{run_info["created_at"]}
## 4. 실행 환경
| 항목 | 값 |
|---|---|
| Python | {run_info["python_version"].split()[0]} |
| OS | {run_info["os"]} |
| pandas | {run_info["pandas_version"]} |
| numpy | {run_info["numpy_version"]} |
| scikit-learn | {run_info["sklearn_version"]} |
| pyarrow | {run_info["pyarrow_version"]} |
| python-dotenv 설치 여부 | {run_info["python_dotenv_installed"]} |
## 5. 입력과 출력
| 항목 | 값 |
|---|---|
| 입력 파일 | {run_info["input_file"]} |
| 입력 파일 존재 여부 | {run_info["input_file_exists"]} |
| 입력 행 수 | {run_info["input_row_count"]} |
| 입력 열 수 | {run_info["input_column_count"]} |
| 출력 폴더 | {run_info["output_dir"]} |
## 6. seed
| 항목 | 값 |
|---|---|
| SEED | {run_info["seed"]} |
## 7. 환경 사용 여부
| 환경 | 사용 여부 |
|---|---|
| 개인 로컬 PC WSL2 | 사용 |
| OpenShift Local | {run_info["openshift_local_used"]} |
| Developer Sandbox | {run_info["developer_sandbox_used"]} |
| AWS g4dn.xlarge | {run_info["g4dn_used"]} |
| H200 | {run_info["h200_used"]} |
## 8. 오늘의 핵심
실험 결과만 저장하면 부족하다.
실행 날짜, Python 버전, 패키지 버전, 입력 파일, seed, 출력 위치를 함께 기록해야
결과가 달라졌을 때 원인을 추적할 수 있다.
"""
with open(run_record_file, "w", encoding="utf-8") as f:
    f.write(run_record_text)
print("Markdown 실행 기록 저장:", run_record_file)
print("저장 여부:", run_record_file.exists())

Markdown 실행 기록 저장: /home/soldesk/week2-reproducibility/outputs/reproducibility_run_record.md
저장 여부: True

In [16]:
import sys
from pathlib import Path
print("Python executable:")
print(sys.executable)
print("\nCurrent working directory:")
print(Path.cwd())

Python executable:
/home/soldesk/week2-reproducibility/.venv/bin/python

Current working directory:
/home/soldesk/week2-reproducibility/notebooks

In [17]:
import sys
from pathlib import Path
print("Python executable:")
print(sys.executable)
print("\nCurrent working directory:")
print(Path.cwd())

Python executable:
/home/soldesk/week2-reproducibility/.venv/bin/python

Current working directory:
/home/soldesk/week2-reproducibility/notebooks

In [18]:
import sys
import json
from pathlib import Path
OUTPUT_DIR = Path.cwd().parent / "outputs" if Path.cwd().name == "notebooks" else Path.cwd() / "outputs"
run_info_file = OUTPUT_DIR / "run_info.json"
if run_info_file.exists():
    with open(run_info_file, "r", encoding="utf-8") as f:
        run_info = json.load(f)
else:
    run_info = {}
run_info["venv_python_executable"] = sys.executable
run_info["venv_detected"] = ".venv" in sys.executable
run_info["period3_note"] = "venv 가상 환경 생성 및 패키지 설치 확인"
with open(run_info_file, "w", encoding="utf-8") as f:
    json.dump(run_info, f, ensure_ascii=False, indent=2)
run_info

{'run_name': 'week2_day3_reproducibility',
 'created_at': '2026-06-29T10:42:41.556515',
 'python_version': '3.12.3 (main, Mar 23 2026, 19:04:32) [GCC 13.3.0]',
 'os': 'Linux-6.18.33.2-microsoft-standard-WSL2-x86_64-with-glibc2.39',
 'cwd': '/home/soldesk/week2-reproducibility/notebooks',
 'base_dir': '/home/soldesk/week2-reproducibility',
 'pandas_version': '3.0.3',
 'numpy_version': '2.5.0',
 'sklearn_version': '1.9.0',
 'pyarrow_version': '24.0.0',
 'python_dotenv_installed': True,
 'seed': 42,
 'input_file': '/home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv',
 'input_file_exists': True,
 'input_row_count': 9,
 'input_column_count': 29,
 'output_dir': '/home/soldesk/week2-reproducibility/outputs',
 'author': 'student',
 'execution_environment': 'local_wsl2',
 'openshift_local_used': False,
 'developer_sandbox_used': False,
 'g4dn_used': False,
 'h200_used': False,
 'note': 'Day 3 period 2 reproducibility run info practice',
 'venv_python_executable': '/home/soldesk/week2-reproducibility/.venv/bin/python',
 'venv_detected': True,
 'period3_note': 'venv 가상 환경 생성 및 패키지 설치 확인'}

In [19]:
from pathlib import Path
import sys
import subprocess
import platform
from datetime import datetime

# ==========================================================
# 1. 프로젝트 루트 및 outputs 경로 설정
# ==========================================================

BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

venv_record_path = OUTPUT_DIR / "venv_environment_record.md"


# ==========================================================
# 2. 현재 Notebook 커널 환경 정보 수집
# ==========================================================

created_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
python_executable = sys.executable
python_version = sys.version
os_info = platform.platform()
current_working_dir = Path.cwd()


# ==========================================================
# 3. 현재 커널 기준 pip freeze 결과 수집
# ==========================================================

pip_freeze_result = subprocess.run(
    [sys.executable, "-m", "pip", "freeze"],
    capture_output=True,
    text=True
)

if pip_freeze_result.returncode == 0:
    pip_freeze_text = pip_freeze_result.stdout.strip()
else:
    pip_freeze_text = (
        "pip freeze 실행 중 오류가 발생했습니다.\n"
        + pip_freeze_result.stderr.strip()
    )

if not pip_freeze_text:
    pip_freeze_text = "설치된 패키지 목록이 비어 있거나 확인되지 않았습니다."


# ==========================================================
# 4. Markdown에서 보기 좋게 들여쓰기 처리
# ==========================================================

python_version_block = "\n".join(
    "    " + line for line in python_version.splitlines()
)

pip_freeze_block = "\n".join(
    "    " + line for line in pip_freeze_text.splitlines()
)


# ==========================================================
# 5. Markdown 기록 내용 생성
#    f""" 긴 문자열 대신 리스트 + join 방식 사용
# ==========================================================

record_lines = [
    "# 2주차 Day 3 3교시 venv 환경 기록",
    "",
    "## 1. 작성자",
    "",
    "student",
    "",
    "## 2. 실습 환경",
    "",
    "| 항목 | 값 |",
    "|---|---|",
    "| 중심 환경 | 개인 로컬 PC WSL2 Ubuntu |",
    "| OpenShift Local 사용 | 사용하지 않음 |",
    "| Developer Sandbox 사용 | 사용하지 않음 |",
    "| AWS g4dn.xlarge 사용 | 사용하지 않음 |",
    "| H200 사용 | 사용하지 않음 |",
    "",
    "## 3. 실행 시각",
    "",
    f"    {created_at}",
    "",
    "## 4. 현재 Notebook 실행 위치",
    "",
    f"    {current_working_dir}",
    "",
    "## 5. 프로젝트 루트 경로",
    "",
    f"    {BASE_DIR}",
    "",
    "## 6. Python 실행 파일",
    "",
    f"    {python_executable}",
    "",
    "## 7. Python 버전",
    "",
    python_version_block,
    "",
    "## 8. 운영체제 정보",
    "",
    f"    {os_info}",
    "",
    "## 9. 현재 커널 기준 패키지 목록",
    "",
    "아래 목록은 현재 Notebook 커널에서 사용하는 Python 환경의 pip freeze 결과입니다.",
    "",
    pip_freeze_block,
    "",
    "## 10. 정리",
    "",
    "이번 기록은 Day 3 재현성 실습을 위해 현재 Python 실행 환경을 사람이 읽기 좋은 Markdown 형식으로 저장한 것입니다.",
    "",
    "재현성을 높이려면 코드뿐만 아니라 아래 정보도 함께 기록해야 합니다.",
    "",
    "- 어떤 Python 실행 파일을 사용했는지",
    "- 어떤 Python 버전인지",
    "- 어떤 운영체제 환경인지",
    "- 어떤 프로젝트 경로에서 실행했는지",
    "- 어떤 패키지들이 설치되어 있는지",
    ""
]

record_text = "\n".join(record_lines)


# ==========================================================
# 6. Markdown 파일 저장
# ==========================================================

venv_record_path.write_text(record_text, encoding="utf-8")

print("venv 환경 기록 Markdown 저장 완료")
print("저장 경로:", venv_record_path)
print("파일 존재 여부:", venv_record_path.exists())

venv 환경 기록 Markdown 저장 완료
저장 경로: /home/soldesk/week2-reproducibility/outputs/venv_environment_record.md
파일 존재 여부: True

In [20]:
requirements_file = BASE_DIR / "requirements.txt"
print("requirements.txt 존재 여부:", requirements_file.exists())
print(requirements_file.read_text(encoding="utf-8")[:500])

requirements.txt 존재 여부: True
anyio==4.14.0
argon2-cffi==25.1.0
argon2-cffi-bindings==25.1.0
arrow==1.4.0
asttokens==3.0.1
async-lru==2.3.0
attrs==26.1.0
babel==2.18.0
beautifulsoup4==4.15.0
bleach==6.4.0
certifi==2026.6.17
cffi==2.0.0
charset-normalizer==3.4.7
comm==0.2.3
debugpy==1.8.21
decorator==5.3.1
defusedxml==0.7.1
executing==2.2.1
fastjsonschema==2.21.2
fqdn==1.5.1
h11==0.16.0
httpcore==1.0.9
httpx==0.28.1
idna==3.18
ipykernel==7.3.0
ipython==9.14.1
ipython_pygments_lexers==1.1.1
isoduration==20.11.0
jedi==0.20.0
Ji

In [21]:
if requirements_file.exists():
    requirements_lines = [
        line.strip()
        for line in requirements_file.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
else:
    requirements_lines = []
    print("requirements.txt 파일이 없습니다:", requirements_file)

print("requirements line count:", len(requirements_lines))

requirements_lines[:20]

requirements line count: 100

['anyio==4.14.0',
 'argon2-cffi==25.1.0',
 'argon2-cffi-bindings==25.1.0',
 'arrow==1.4.0',
 'asttokens==3.0.1',
 'async-lru==2.3.0',
 'attrs==26.1.0',
 'babel==2.18.0',
 'beautifulsoup4==4.15.0',
 'bleach==6.4.0',
 'certifi==2026.6.17',
 'cffi==2.0.0',
 'charset-normalizer==3.4.7',
 'comm==0.2.3',
 'debugpy==1.8.21',
 'decorator==5.3.1',
 'defusedxml==0.7.1',
 'executing==2.2.1',
 'fastjsonschema==2.21.2',
 'fqdn==1.5.1']

In [22]:
required_keywords = [
    "pandas",
    "numpy",
    "scikit-learn",
    "pyarrow",
    "jupyterlab",
    "python-dotenv"
]
for keyword in required_keywords:
    included = any(line.lower().startswith(keyword.lower()) for line in requirements_lines)
    print(keyword, "included:", included)

pandas included: True
numpy included: True
scikit-learn included: True
pyarrow included: True
jupyterlab included: True
python-dotenv included: True

In [23]:
import hashlib
requirements_text = requirements_file.read_text(encoding="utf-8")
requirements_sha256 = hashlib.sha256(
    requirements_text.encode("utf-8")
).hexdigest()
print("requirements sha256:", requirements_sha256)

requirements sha256: 37166d959eb47d01da022a1debedbe5dbf789835197fed6633d50a7ff2326c5e

In [24]:
import json
import hashlib
from pathlib import Path
from datetime import datetime
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = BASE_DIR / "outputs"
run_info_file = OUTPUT_DIR / "run_info.json"
requirements_file = BASE_DIR / "requirements.txt"
if run_info_file.exists():
    with open(run_info_file, "r", encoding="utf-8") as f:
        run_info = json.load(f)
else:
    run_info = {}
requirements_exists = requirements_file.exists()
if requirements_exists:
    requirements_text = requirements_file.read_text(encoding="utf-8")
    requirements_lines = [
        line.strip()
        for line in requirements_text.splitlines()
        if line.strip()
    ]
    requirements_sha256 = hashlib.sha256(
        requirements_text.encode("utf-8")
    ).hexdigest()
else:
    requirements_lines = []
    requirements_sha256 = None
run_info["period4_requirements"] = {
    "updated_at": datetime.now().isoformat(),
    "requirements_file": str(requirements_file),
    "requirements_file_exists": requirements_exists,
    "requirements_line_count": len(requirements_lines),
    "requirements_sha256": requirements_sha256,
    "install_command": "python -m pip install -r requirements.txt",
    "minimal_requirements_file": str(BASE_DIR / "requirements-minimal.txt"),
    "note": "4교시에서 requirements.txt를 생성하고 재설치 테스트 기준을 기록함"
}
with open(run_info_file, "w", encoding="utf-8") as f:
    json.dump(run_info, f, ensure_ascii=False, indent=2)
run_info["period4_requirements"]

{'updated_at': '2026-06-29T10:42:42.225919',
 'requirements_file': '/home/soldesk/week2-reproducibility/requirements.txt',
 'requirements_file_exists': True,
 'requirements_line_count': 100,
 'requirements_sha256': '37166d959eb47d01da022a1debedbe5dbf789835197fed6633d50a7ff2326c5e',
 'install_command': 'python -m pip install -r requirements.txt',
 'minimal_requirements_file': '/home/soldesk/week2-reproducibility/requirements-minimal.txt',
 'note': '4교시에서 requirements.txt를 생성하고 재설치 테스트 기준을 기록함'}

In [25]:
from pathlib import Path
import sys
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
print("BASE_DIR:", BASE_DIR)
print("Python executable:", sys.executable)
print(".venv 사용 여부:", ".venv" in sys.executable)

BASE_DIR: /home/soldesk/week2-reproducibility
Python executable: /home/soldesk/week2-reproducibility/.venv/bin/python
.venv 사용 여부: True

In [26]:
import random
import json
from pathlib import Path
from datetime import datetime
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
SEED = 42
print("SEED:", SEED)

SEED: 42

In [27]:
np.random.randint(0, 100, size=10)

array([78, 16, 61, 23, 14, 98, 34, 38, 41, 93])

In [28]:
np.random.randint(0, 100, size=10)

array([29, 21, 20, 90, 83, 88, 97, 48, 32, 90])

In [29]:
np.random.seed(SEED)
np.random.randint(0, 100, size=10)

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [30]:
np.random.seed(SEED)
np.random.randint(0, 100, size=10)

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [31]:
np.random.seed(SEED)
numpy_random_a = np.random.randint(0, 100, size=10)
np.random.seed(SEED)
numpy_random_b = np.random.randint(0, 100, size=10)
print("A:", numpy_random_a)
print("B:", numpy_random_b)
print("A와 B가 같은가?:", np.array_equal(numpy_random_a, numpy_random_b))

A: [51 92 14 71 60 20 82 86 74 74]
B: [51 92 14 71 60 20 82 86 74 74]
A와 B가 같은가?: True

In [32]:
items = np.array(["A", "B", "C", "D", "E"])
np.random.choice(items, size=3, replace=False)

array(['A', 'B', 'C'], dtype='<U1')

In [33]:
items = np.array(["A", "B", "C", "D", "E"])
np.random.choice(items, size=3, replace=False)

array(['A', 'C', 'D'], dtype='<U1')

In [34]:
items = np.array(["A", "B", "C", "D", "E"])
np.random.choice(items, size=3, replace=False)

array(['E', 'C', 'A'], dtype='<U1')

In [35]:
np.random.seed(SEED)
sample_a = np.random.choice(items, size=3, replace=False)
np.random.seed(SEED)
sample_b = np.random.choice(items, size=3, replace=False)
print("sample_a:", sample_a)
print("sample_b:", sample_b)
print("같은가?:", np.array_equal(sample_a, sample_b))

sample_a: ['B' 'E' 'C']
sample_b: ['B' 'E' 'C']
같은가?: True

In [36]:
np.random.seed(SEED)
sample_a = np.random.choice(items, size=3, replace=False)
np.random.seed(SEED)
sample_b = np.random.choice(items, size=3, replace=False)
print("sample_a:", sample_a)
print("sample_b:", sample_b)
print("같은가?:", np.array_equal(sample_a, sample_b))

sample_a: ['B' 'E' 'C']
sample_b: ['B' 'E' 'C']
같은가?: True

In [37]:
random.randint(0, 100)

20

In [38]:
random.randint(0, 100)

9

In [39]:
numbers = list(range(1, 21))
random.sample(numbers, 5)

[14, 11, 7, 5, 16]

In [40]:
numbers = list(range(1, 21))
random.sample(numbers, 5)

[20, 11, 2, 7, 4]

In [41]:
random.seed(SEED)
python_random_a = random.sample(numbers, 5)
random.seed(SEED)
python_random_b = random.sample(numbers, 5)
print("python_random_a:", python_random_a)
print("python_random_b:", python_random_b)
print("같은가?:", python_random_a == python_random_b)

python_random_a: [4, 1, 9, 8, 17]
python_random_b: [4, 1, 9, 8, 17]
같은가?: True

In [42]:
random.seed(SEED)
python_random_a = random.sample(numbers, 5)
random.seed(SEED)
python_random_b = random.sample(numbers, 5)
print("python_random_a:", python_random_a)
print("python_random_b:", python_random_b)
print("같은가?:", python_random_a == python_random_b)

python_random_a: [4, 1, 9, 8, 17]
python_random_b: [4, 1, 9, 8, 17]
같은가?: True

In [43]:
def set_seed(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    return seed

In [44]:
set_seed(SEED)
print(np.random.randint(0, 100, size=5))
print(random.sample(numbers, 5))

[51 92 14 71 60]
[4, 1, 9, 8, 17]

In [45]:
set_seed(SEED)
print(np.random.randint(0, 100, size=5))
print(random.sample(numbers, 5))

[51 92 14 71 60]
[4, 1, 9, 8, 17]

In [46]:
set_seed(SEED)
result_a_np = np.random.randint(0, 100, size=5)
result_a_py = random.sample(numbers, 5)
set_seed(SEED)
result_b_np = np.random.randint(0, 100, size=5)
result_b_py = random.sample(numbers, 5)
print("NumPy 같은가?:", np.array_equal(result_a_np, result_b_np))
print("Python random 같은가?:", result_a_py == result_b_py)

NumPy 같은가?: True
Python random 같은가?: True

In [47]:
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
CLEAN_DIR = BASE_DIR / "data" / "clean"
OUTPUT_DIR = BASE_DIR / "outputs"
input_file = CLEAN_DIR / "customers_clean_20260606_v2.csv"
print("input_file:", input_file)
print("exists:", input_file.exists())

input_file: /home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv
exists: True

In [48]:
df = pd.read_csv(input_file)
print("shape:", df.shape)
df.head()

shape: (9, 29)

,customer_id,age,monthly_fee,usage_days,support_calls,gender_standard,contract_type_standard,signup_date,last_login_date,signup_year,...,monthly_fee_outlier,support_calls_outlier,is_high_fee,is_short_user,has_many_support_calls,usage_group,is_long_contract,churn,gender,contract_type
0,C001,34,59000,120,1,female,monthly,2025-01-10,2026-06-01,2025,...,0,0,1,0,0,middle,0,0,female,month-to-month
1,C002,45,79000,380,3,male,one_year,2024-12-01,2026-05-10,2024,...,0,0,1,0,1,long,1,1,male,1-year
2,C003,41,72000,45,0,female,monthly,2026-04-20,2026-06-03,2026,...,0,0,1,0,0,middle,0,0,female,month-to-month
3,C004,52,99000,800,5,male,one_year,2023-05-15,2026-03-01,2023,...,0,0,1,0,1,long,1,1,male,1-year
4,C005,41,69000,220,2,female,unknown,2025-08-03,2026-05-30,2025,...,0,0,1,0,0,middle,0,0,female,unknown

In [49]:
print(df.columns.tolist())

['customer_id', 'age', 'monthly_fee', 'usage_days', 'support_calls', 'gender_standard', 'contract_type_standard', 'signup_date', 'last_login_date', 'signup_year', 'signup_month', 'last_login_dayofweek', 'last_login_day_name', 'days_since_signup', 'days_since_last_login', 'age_was_missing', 'monthly_fee_was_missing', 'gender_was_missing', 'contract_type_was_missing', 'monthly_fee_outlier', 'support_calls_outlier', 'is_high_fee', 'is_short_user', 'has_many_support_calls', 'usage_group', 'is_long_contract', 'churn', 'gender', 'contract_type']

In [50]:
df["churn"].value_counts(dropna=False)

churn
0    5
1    4
Name: count, dtype: int64

In [51]:
target_col = "churn"
drop_cols = [
    "churn",
    "customer_id"
]
X = df.drop(columns=[col for col in drop_cols if col in df.columns])
y = df[target_col]
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (9, 27)
y shape: (9,)

In [52]:
target_col = "churn"
drop_cols = [
    "churn",
    "customer_id"
]
X = df.drop(columns=[col for col in drop_cols if col in df.columns])
y = df[target_col]
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (9, 27)
y shape: (9,)

In [53]:
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(
    X,
    y,
    test_size=0.3,
    shuffle=True
)
print("X_train_1:", X_train_1.shape)
print("X_test_1:", X_test_1.shape)
print("y_test_1 index:", y_test_1.index.tolist())

X_train_1: (6, 27)
X_test_1: (3, 27)
y_test_1 index: [3, 7, 0]

In [54]:
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(
    X,
    y,
    test_size=0.3,
    shuffle=True
)
print("X_train_2:", X_train_2.shape)
print("X_test_2:", X_test_2.shape)
print("y_test_2 index:", y_test_2.index.tolist())

X_train_2: (6, 27)
X_test_2: (3, 27)
y_test_2 index: [0, 6, 3]

In [55]:
print("테스트 인덱스가 같은가?:", y_test_1.index.tolist() == y_test_2.index.tolist())

테스트 인덱스가 같은가?: False

In [56]:
X_train_a, X_test_a, y_train_a, y_test_a = train_test_split(
    X,
    y,
    test_size=0.3,
    shuffle=True,
    random_state=SEED
)
print("X_train_a:", X_train_a.shape)
print("X_test_a:", X_test_a.shape)
print("y_test_a index:", y_test_a.index.tolist())

X_train_a: (6, 27)
X_test_a: (3, 27)
y_test_a index: [7, 1, 5]

In [57]:
X_train_b, X_test_b, y_train_b, y_test_b = train_test_split(
    X,
    y,
    test_size=0.3,
    shuffle=True,
    random_state=SEED
)
print("X_train_b:", X_train_b.shape)
print("X_test_b:", X_test_b.shape)
print("y_test_b index:", y_test_b.index.tolist())

X_train_b: (6, 27)
X_test_b: (3, 27)
y_test_b index: [7, 1, 5]

In [58]:
print("테스트 인덱스가 같은가?:", y_test_a.index.tolist() == y_test_b.index.tolist())

테스트 인덱스가 같은가?: True

In [59]:
split_summary = pd.DataFrame({
    "dataset": ["train", "test"],
    "row_count": [len(X_train_a), len(X_test_a)],
    "ratio": [len(X_train_a) / len(df), len(X_test_a) / len(df)]
})
split_summary

  dataset  row_count     ratio
0   train          6  0.666667
1    test          3  0.333333

In [60]:
print("전체 churn 분포")
print(y.value_counts(normalize=True).sort_index())
print("\ntrain churn 분포")
print(y_train_a.value_counts(normalize=True).sort_index())
print("\ntest churn 분포")
print(y_test_a.value_counts(normalize=True).sort_index())

전체 churn 분포
churn
0    0.555556
1    0.444444
Name: proportion, dtype: float64

train churn 분포
churn
0    0.5
1    0.5
Name: proportion, dtype: float64

test churn 분포
churn
0    0.666667
1    0.333333
Name: proportion, dtype: float64

In [61]:
X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(
    X,
    y,
    test_size=0.3,
    shuffle=True,
    random_state=SEED,
    stratify=y
)
print("X_train_s:", X_train_s.shape)
print("X_test_s:", X_test_s.shape)
print("y_test_s index:", y_test_s.index.tolist())

X_train_s: (6, 27)
X_test_s: (3, 27)
y_test_s index: [8, 5, 0]

In [62]:
print("전체 churn 분포")
print(y.value_counts(normalize=True).sort_index())
print("\nstratified train churn 분포")
print(y_train_s.value_counts(normalize=True).sort_index())
print("\nstratified test churn 분포")
print(y_test_s.value_counts(normalize=True).sort_index())

전체 churn 분포
churn
0    0.555556
1    0.444444
Name: proportion, dtype: float64

stratified train churn 분포
churn
0    0.5
1    0.5
Name: proportion, dtype: float64

stratified test churn 분포
churn
0    0.666667
1    0.333333
Name: proportion, dtype: float64

In [63]:
try:
    X_train_final, X_test_final, y_train_final, y_test_final = train_test_split(
        X,
        y,
        test_size=0.3,
        shuffle=True,
        random_state=SEED,
        stratify=y
    )

    split_stratify = True
    split_note = "stratify=y 적용"

except ValueError as e:
    print("stratify 적용 실패:", e)
    print("데이터 수 또는 클래스 분포 문제로 stratify 없이 다시 분할합니다.")

    X_train_final, X_test_final, y_train_final, y_test_final = train_test_split(
        X,
        y,
        test_size=0.3,
        shuffle=True,
        random_state=SEED
    )

    split_stratify = False
    split_note = "stratify 실패로 stratify 없이 분할"


print("split_stratify:", split_stratify)
print("split_note:", split_note)
print("X_train_final:", X_train_final.shape)
print("X_test_final:", X_test_final.shape)
print("y_train_final:", y_train_final.shape)
print("y_test_final:", y_test_final.shape)

split_stratify: True
split_note: stratify=y 적용
X_train_final: (6, 27)
X_test_final: (3, 27)
y_train_final: (6,)
y_test_final: (3,)

In [64]:
split_result_summary = pd.DataFrame({
    "dataset": ["train", "test"],
    "row_count": [len(X_train_final), len(X_test_final)],
    "churn_0_count": [
        int((y_train_final == 0).sum()),
        int((y_test_final == 0).sum())
    ],
    "churn_1_count": [
        int((y_train_final == 1).sum()),
        int((y_test_final == 1).sum())
    ],
    "churn_rate": [
        float(y_train_final.mean()),
        float(y_test_final.mean())
    ]
})
split_result_summary

  dataset  row_count  churn_0_count  churn_1_count  churn_rate
0   train          6              3              3    0.500000
1    test          3              2              1    0.333333

In [65]:
train_indices = X_train_final.index.tolist()
test_indices = X_test_final.index.tolist()
print("train_indices:", train_indices)
print("test_indices:", test_indices)

train_indices: [1, 2, 3, 6, 4, 7]
test_indices: [8, 5, 0]

In [66]:
split_result = {
    "author": "student",
    "seed": SEED,
    "test_size": 0.3,
    "random_state": SEED,
    "shuffle": True,
    "stratify": split_stratify,
    "split_note": split_note,
    "input_file": str(input_file),
    "row_count": int(len(df)),
    "feature_column_count": int(X.shape[1]),
    "target_column": target_col,
    "train_row_count": int(len(X_train_final)),
    "test_row_count": int(len(X_test_final)),
    "train_indices": train_indices,
    "test_indices": test_indices,
    "train_churn_distribution": {
        str(k): int(v)
        for k, v in y_train_final.value_counts(dropna=False).to_dict().items()
    },
    "test_churn_distribution": {
        str(k): int(v)
        for k, v in y_test_final.value_counts(dropna=False).to_dict().items()
    },
    "created_at": datetime.now().isoformat(),
    "g4dn_used": False,
    "openshift_local_used": False,
    "developer_sandbox_used": False,
    "h200_used": False,
    "note": "Day 3 5교시 seed 고정과 train_test_split 재현성 실습 결과"
}
split_result_file = OUTPUT_DIR / "seed_split_result.json"
with open(split_result_file, "w", encoding="utf-8") as f:
    json.dump(split_result, f, ensure_ascii=False, indent=2)
print("saved:", split_result_file)
print("exists:", split_result_file.exists())

saved: /home/soldesk/week2-reproducibility/outputs/seed_split_result.json
exists: True

In [67]:
with open(split_result_file, "r", encoding="utf-8") as f:
    loaded_split_result = json.load(f)
loaded_split_result

{'author': 'student',
 'seed': 42,
 'test_size': 0.3,
 'random_state': 42,
 'shuffle': True,
 'stratify': True,
 'split_note': 'stratify=y 적용',
 'input_file': '/home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv',
 'row_count': 9,
 'feature_column_count': 27,
 'target_column': 'churn',
 'train_row_count': 6,
 'test_row_count': 3,
 'train_indices': [1, 2, 3, 6, 4, 7],
 'test_indices': [8, 5, 0],
 'train_churn_distribution': {'1': 3, '0': 3},
 'test_churn_distribution': {'0': 2, '1': 1},
 'created_at': '2026-06-29T10:44:34.397882',
 'g4dn_used': False,
 'openshift_local_used': False,
 'developer_sandbox_used': False,
 'h200_used': False,
 'note': 'Day 3 5교시 seed 고정과 train_test_split 재현성 실습 결과'}

In [68]:
run_info_file = OUTPUT_DIR / "run_info.json"
if run_info_file.exists():
    with open(run_info_file, "r", encoding="utf-8") as f:
        run_info = json.load(f)
else:
    run_info = {}
run_info["seed"] = SEED
run_info["split_test_size"] = 0.3
run_info["split_random_state"] = SEED
run_info["split_shuffle"] = True
run_info["split_stratify"] = split_stratify
run_info["split_note"] = split_note
run_info["split_result_file"] = str(split_result_file)
run_info["period5_seed_note"] = "random.seed, np.random.seed, train_test_split random_state 기준 기록"
run_info["updated_at_period5"] = datetime.now().isoformat()
with open(run_info_file, "w", encoding="utf-8") as f:
    json.dump(run_info, f, ensure_ascii=False, indent=2)
print("run_info.json 업데이트 완료:", run_info_file)

run_info.json 업데이트 완료: /home/soldesk/week2-reproducibility/outputs/run_info.json

In [69]:
with open(run_info_file, "r", encoding="utf-8") as f:
    loaded_run_info = json.load(f)
print("author:", loaded_run_info.get("author"))
print("seed:", loaded_run_info.get("seed"))
print("split_test_size:", loaded_run_info.get("split_test_size"))
print("split_random_state:", loaded_run_info.get("split_random_state"))
print("split_stratify:", loaded_run_info.get("split_stratify"))
print("split_result_file:", loaded_run_info.get("split_result_file"))

author: student
seed: 42
split_test_size: 0.3
split_random_state: 42
split_stratify: True
split_result_file: /home/soldesk/week2-reproducibility/outputs/seed_split_result.json

In [70]:
from pathlib import Path
current_dir = Path.cwd()
print("현재 실행 위치:", current_dir)
print("현재 폴더 이름:", current_dir.name)

현재 실행 위치: /home/soldesk/week2-reproducibility/notebooks
현재 폴더 이름: notebooks

In [71]:
bad_path = "data/clean/customers_clean_20260606_v2.csv"
good_path = Path("data") / "clean" / "customers_clean_20260606_v2.csv"
print("bad_path:", bad_path)
print("good_path:", good_path)

bad_path: data/clean/customers_clean_20260606_v2.csv
good_path: data/clean/customers_clean_20260606_v2.csv

In [72]:
from pathlib import Path
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
print("현재 위치:", Path.cwd())
print("프로젝트 루트 BASE_DIR:", BASE_DIR)

현재 위치: /home/soldesk/week2-reproducibility/notebooks
프로젝트 루트 BASE_DIR: /home/soldesk/week2-reproducibility

In [73]:
DATA_DIR = BASE_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
CLEAN_DIR = DATA_DIR / "clean"
FEATURE_DIR = DATA_DIR / "feature"
OUTPUT_DIR = BASE_DIR / "outputs"
REPORT_DIR = BASE_DIR / "reports" / "week2"
for path in [RAW_DIR, CLEAN_DIR, FEATURE_DIR, OUTPUT_DIR, REPORT_DIR]:
    path.mkdir(parents=True, exist_ok=True)
print("DATA_DIR:", DATA_DIR)
print("RAW_DIR:", RAW_DIR)
print("CLEAN_DIR:", CLEAN_DIR)
print("FEATURE_DIR:", FEATURE_DIR)
print("OUTPUT_DIR:", OUTPUT_DIR)
print("REPORT_DIR:", REPORT_DIR)

DATA_DIR: /home/soldesk/week2-reproducibility/data
RAW_DIR: /home/soldesk/week2-reproducibility/data/raw
CLEAN_DIR: /home/soldesk/week2-reproducibility/data/clean
FEATURE_DIR: /home/soldesk/week2-reproducibility/data/feature
OUTPUT_DIR: /home/soldesk/week2-reproducibility/outputs
REPORT_DIR: /home/soldesk/week2-reproducibility/reports/week2

In [74]:
input_file = CLEAN_DIR / "customers_clean_20260606_v2.csv"
print("input_file:", input_file)
print("exists:", input_file.exists())

input_file: /home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv
exists: True

In [75]:
import pandas as pd
if input_file.exists():
    df = pd.read_csv(input_file)
    print("shape:", df.shape)
    display(df.head())
else:
    raise FileNotFoundError(f"입력 파일이 없습니다: {input_file}")

shape: (9, 29)

,customer_id,age,monthly_fee,usage_days,support_calls,gender_standard,contract_type_standard,signup_date,last_login_date,signup_year,...,monthly_fee_outlier,support_calls_outlier,is_high_fee,is_short_user,has_many_support_calls,usage_group,is_long_contract,churn,gender,contract_type
0,C001,34,59000,120,1,female,monthly,2025-01-10,2026-06-01,2025,...,0,0,1,0,0,middle,0,0,female,month-to-month
1,C002,45,79000,380,3,male,one_year,2024-12-01,2026-05-10,2024,...,0,0,1,0,1,long,1,1,male,1-year
2,C003,41,72000,45,0,female,monthly,2026-04-20,2026-06-03,2026,...,0,0,1,0,0,middle,0,0,female,month-to-month
3,C004,52,99000,800,5,male,one_year,2023-05-15,2026-03-01,2023,...,0,0,1,0,1,long,1,1,male,1-year
4,C005,41,69000,220,2,female,unknown,2025-08-03,2026-05-30,2025,...,0,0,1,0,0,middle,0,0,female,unknown

In [76]:
import os
from pathlib import Path
from dotenv import load_dotenv
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
env_file = BASE_DIR / ".env"
print("BASE_DIR:", BASE_DIR)
print(".env path:", env_file)
print(".env exists:", env_file.exists())

BASE_DIR: /home/soldesk/week2-reproducibility
.env path: /home/soldesk/week2-reproducibility/.env
.env exists: True

In [77]:
load_dotenv(env_file)

True

In [78]:
SEED_RAW = os.getenv("SEED")
DATA_VERSION = os.getenv("DATA_VERSION")
INPUT_FILE_RAW = os.getenv("INPUT_FILE")
OUTPUT_DIR_RAW = os.getenv("OUTPUT_DIR")
AUTHOR = os.getenv("AUTHOR")
EXECUTION_ENVIRONMENT = os.getenv("EXECUTION_ENVIRONMENT")
print("SEED_RAW:", SEED_RAW)
print("DATA_VERSION:", DATA_VERSION)
print("INPUT_FILE_RAW:", INPUT_FILE_RAW)
print("OUTPUT_DIR_RAW:", OUTPUT_DIR_RAW)
print("AUTHOR:", AUTHOR)
print("EXECUTION_ENVIRONMENT:", EXECUTION_ENVIRONMENT)

SEED_RAW: 42
DATA_VERSION: 20260606_v2
INPUT_FILE_RAW: data/clean/customers_clean_20260606_v2.csv
OUTPUT_DIR_RAW: outputs
AUTHOR: kim-juil
EXECUTION_ENVIRONMENT: local_wsl2

In [79]:
SEED = int(SEED_RAW)
INPUT_FILE = BASE_DIR / INPUT_FILE_RAW
OUTPUT_DIR = BASE_DIR / OUTPUT_DIR_RAW
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
print("SEED:", SEED, type(SEED))
print("INPUT_FILE:", INPUT_FILE)
print("OUTPUT_DIR:", OUTPUT_DIR)
print("INPUT_FILE exists:", INPUT_FILE.exists())

SEED: 42 <class 'int'>
INPUT_FILE: /home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv
OUTPUT_DIR: /home/soldesk/week2-reproducibility/outputs
INPUT_FILE exists: True

In [80]:
if not INPUT_FILE.exists():
    raise FileNotFoundError(f"입력 파일이 없습니다: {INPUT_FILE}")
df_env = pd.read_csv(INPUT_FILE)
print("shape:", df_env.shape)
df_env.head()

shape: (9, 29)

,customer_id,age,monthly_fee,usage_days,support_calls,gender_standard,contract_type_standard,signup_date,last_login_date,signup_year,...,monthly_fee_outlier,support_calls_outlier,is_high_fee,is_short_user,has_many_support_calls,usage_group,is_long_contract,churn,gender,contract_type
0,C001,34,59000,120,1,female,monthly,2025-01-10,2026-06-01,2025,...,0,0,1,0,0,middle,0,0,female,month-to-month
1,C002,45,79000,380,3,male,one_year,2024-12-01,2026-05-10,2024,...,0,0,1,0,1,long,1,1,male,1-year
2,C003,41,72000,45,0,female,monthly,2026-04-20,2026-06-03,2026,...,0,0,1,0,0,middle,0,0,female,month-to-month
3,C004,52,99000,800,5,male,one_year,2023-05-15,2026-03-01,2023,...,0,0,1,0,1,long,1,1,male,1-year
4,C005,41,69000,220,2,female,unknown,2025-08-03,2026-05-30,2025,...,0,0,1,0,0,middle,0,0,female,unknown

In [81]:
df_env["churn"].value_counts(dropna=False)

churn
0    5
1    4
Name: count, dtype: int64

In [82]:
env_config_summary = {
    "author": AUTHOR,
    "execution_environment": EXECUTION_ENVIRONMENT,
    "seed": SEED,
    "data_version": DATA_VERSION,
    "input_file": str(INPUT_FILE),
    "input_file_exists": INPUT_FILE.exists(),
    "input_row_count": int(df_env.shape[0]),
    "input_column_count": int(df_env.shape[1]),
    "output_dir": str(OUTPUT_DIR),
    "env_file": str(env_file),
    "env_file_exists": env_file.exists(),
    "env_example_file": str(BASE_DIR / ".env.example"),
    "env_example_file_exists": (BASE_DIR / ".env.example").exists(),
    "g4dn_used": False,
    "openshift_local_used": False,
    "developer_sandbox_used": False,
    "h200_used": False,
    "note": "Day 3 6교시 .env와 환경 변수 기반 경로 설정 실습"
}
env_config_summary

{'author': 'kim-juil',
 'execution_environment': 'local_wsl2',
 'seed': 42,
 'data_version': '20260606_v2',
 'input_file': '/home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv',
 'input_file_exists': True,
 'input_row_count': 9,
 'input_column_count': 29,
 'output_dir': '/home/soldesk/week2-reproducibility/outputs',
 'env_file': '/home/soldesk/week2-reproducibility/.env',
 'env_file_exists': True,
 'env_example_file': '/home/soldesk/week2-reproducibility/.env.example',
 'env_example_file_exists': True,
 'g4dn_used': False,
 'openshift_local_used': False,
 'developer_sandbox_used': False,
 'h200_used': False,
 'note': 'Day 3 6교시 .env와 환경 변수 기반 경로 설정 실습'}

In [83]:
import json
from datetime import datetime
env_config_summary["created_at"] = datetime.now().isoformat()
env_config_summary_file = OUTPUT_DIR / "env_config_summary.json"
with open(env_config_summary_file, "w", encoding="utf-8") as f:
    json.dump(env_config_summary, f, ensure_ascii=False, indent=2)
print("saved:", env_config_summary_file)
print("exists:", env_config_summary_file.exists())

saved: /home/soldesk/week2-reproducibility/outputs/env_config_summary.json
exists: True

In [84]:
with open(env_config_summary_file, "r", encoding="utf-8") as f:
    loaded_env_config = json.load(f)
loaded_env_config

{'author': 'kim-juil',
 'execution_environment': 'local_wsl2',
 'seed': 42,
 'data_version': '20260606_v2',
 'input_file': '/home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv',
 'input_file_exists': True,
 'input_row_count': 9,
 'input_column_count': 29,
 'output_dir': '/home/soldesk/week2-reproducibility/outputs',
 'env_file': '/home/soldesk/week2-reproducibility/.env',
 'env_file_exists': True,
 'env_example_file': '/home/soldesk/week2-reproducibility/.env.example',
 'env_example_file_exists': True,
 'g4dn_used': False,
 'openshift_local_used': False,
 'developer_sandbox_used': False,
 'h200_used': False,
 'note': 'Day 3 6교시 .env와 환경 변수 기반 경로 설정 실습',
 'created_at': '2026-06-29T11:07:32.377349'}

In [85]:
run_info_file = OUTPUT_DIR / "run_info.json"
if run_info_file.exists():
    with open(run_info_file, "r", encoding="utf-8") as f:
        run_info = json.load(f)
else:
    run_info = {}
run_info["period6_env_config"] = {
    "updated_at": datetime.now().isoformat(),
    "author": AUTHOR,
    "execution_environment": EXECUTION_ENVIRONMENT,
    "seed_from_env": SEED,
    "data_version": DATA_VERSION,
    "input_file_from_env": str(INPUT_FILE),
    "input_file_exists": INPUT_FILE.exists(),
    "output_dir_from_env": str(OUTPUT_DIR),
    "env_file_exists": env_file.exists(),
    "env_example_file_exists": (BASE_DIR / ".env.example").exists(),
    "env_config_summary_file": str(env_config_summary_file),
    "path_strategy": "pathlib.Path + project-relative paths",
    "config_strategy": ".env + os.getenv + python-dotenv",
    "git_env_policy": ".env is ignored, .env.example is shared",
    "note": "6교시에서 경로 하드코딩을 제거하고 .env 기반 설정 구조를 기록함"
}
with open(run_info_file, "w", encoding="utf-8") as f:
    json.dump(run_info, f, ensure_ascii=False, indent=2)
print("run_info.json 업데이트 완료:", run_info_file)

run_info.json 업데이트 완료: /home/soldesk/week2-reproducibility/outputs/run_info.json

In [86]:
with open(run_info_file, "r", encoding="utf-8") as f:
    loaded_run_info = json.load(f)
loaded_run_info["period6_env_config"]

{'updated_at': '2026-06-29T11:07:57.181828',
 'author': 'kim-juil',
 'execution_environment': 'local_wsl2',
 'seed_from_env': 42,
 'data_version': '20260606_v2',
 'input_file_from_env': '/home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv',
 'input_file_exists': True,
 'output_dir_from_env': '/home/soldesk/week2-reproducibility/outputs',
 'env_file_exists': True,
 'env_example_file_exists': True,
 'env_config_summary_file': '/home/soldesk/week2-reproducibility/outputs/env_config_summary.json',
 'path_strategy': 'pathlib.Path + project-relative paths',
 'config_strategy': '.env + os.getenv + python-dotenv',
 'git_env_policy': '.env is ignored, .env.example is shared',
 'note': '6교시에서 경로 하드코딩을 제거하고 .env 기반 설정 구조를 기록함'}

In [87]:
SEED_RAW_SAFE = os.getenv("SEED", "42")
AUTHOR_SAFE = os.getenv("AUTHOR", "unknown-author")
INPUT_FILE_RAW_SAFE = os.getenv("INPUT_FILE", "data/clean/customers_clean_20260606_v2.csv")
OUTPUT_DIR_RAW_SAFE = os.getenv("OUTPUT_DIR", "outputs")
SEED_SAFE = int(SEED_RAW_SAFE)
INPUT_FILE_SAFE = BASE_DIR / INPUT_FILE_RAW_SAFE
OUTPUT_DIR_SAFE = BASE_DIR / OUTPUT_DIR_RAW_SAFE
print("SEED_SAFE:", SEED_SAFE)
print("AUTHOR_SAFE:", AUTHOR_SAFE)
print("INPUT_FILE_SAFE:", INPUT_FILE_SAFE)
print("OUTPUT_DIR_SAFE:", OUTPUT_DIR_SAFE)

SEED_SAFE: 42
AUTHOR_SAFE: kim-juil
INPUT_FILE_SAFE: /home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv
OUTPUT_DIR_SAFE: /home/soldesk/week2-reproducibility/outputs

In [88]:
def require_env(name: str) -> str:
    value = os.getenv(name)
    if value is None or value.strip() == "":
        raise ValueError(f"필수 환경 변수가 없습니다: {name}")
    return value

In [91]:
required_seed_raw = require_env("SEED")
required_input_file_raw = require_env("INPUT_FILE")
required_author = require_env("AUTHOR")
print(required_seed_raw)
print(required_input_file_raw)
print(required_author)

42
data/clean/customers_clean_20260606_v2.csv
kim-juil

In [92]:
required_seed_raw = require_env("SEED")
required_input_file_raw = require_env("INPUT_FILE")
required_author = require_env("AUTHOR")
print(required_seed_raw)
print(required_input_file_raw)
print(required_author)

42
data/clean/customers_clean_20260606_v2.csv
kim-juil

In [93]:
import sys
from pathlib import Path
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
if str(BASE_DIR) not in sys.path:
    sys.path.append(str(BASE_DIR))
print("BASE_DIR:", BASE_DIR)
print("BASE_DIR in sys.path:", str(BASE_DIR) in sys.path)

BASE_DIR: /home/soldesk/week2-reproducibility
BASE_DIR in sys.path: True

In [94]:
from src.seed import set_seed
from src.paths import get_project_root, get_project_dirs
from src.io_utils import read_csv, save_csv, read_json, save_json
print("src import 성공")

src import 성공

In [95]:
SEED = 42
applied_seed = set_seed(SEED)
print("applied_seed:", applied_seed)

applied_seed: 42

In [96]:
import numpy as np
import random
set_seed(SEED)
numpy_a = np.random.randint(0, 100, size=5)
python_a = random.sample(list(range(1, 21)), 5)
set_seed(SEED)
numpy_b = np.random.randint(0, 100, size=5)
python_b = random.sample(list(range(1, 21)), 5)
print("numpy_a:", numpy_a)
print("numpy_b:", numpy_b)
print("NumPy 같은가?:", np.array_equal(numpy_a, numpy_b))
print("python_a:", python_a)
print("python_b:", python_b)
print("Python random 같은가?:", python_a == python_b)

numpy_a: [51 92 14 71 60]
numpy_b: [51 92 14 71 60]
NumPy 같은가?: True
python_a: [4, 1, 9, 8, 17]
python_b: [4, 1, 9, 8, 17]
Python random 같은가?: True

In [97]:
dirs = get_project_dirs()
dirs

{'base': PosixPath('/home/soldesk/week2-reproducibility'),
 'raw': PosixPath('/home/soldesk/week2-reproducibility/data/raw'),
 'clean': PosixPath('/home/soldesk/week2-reproducibility/data/clean'),
 'feature': PosixPath('/home/soldesk/week2-reproducibility/data/feature'),
 'outputs': PosixPath('/home/soldesk/week2-reproducibility/outputs'),
 'reports': PosixPath('/home/soldesk/week2-reproducibility/reports/week2'),
 'notebooks': PosixPath('/home/soldesk/week2-reproducibility/notebooks'),
 'src': PosixPath('/home/soldesk/week2-reproducibility/src')}

In [98]:
for name, path in dirs.items():
    print(name, path, path.exists())

base /home/soldesk/week2-reproducibility True
raw /home/soldesk/week2-reproducibility/data/raw True
clean /home/soldesk/week2-reproducibility/data/clean True
feature /home/soldesk/week2-reproducibility/data/feature True
outputs /home/soldesk/week2-reproducibility/outputs True
reports /home/soldesk/week2-reproducibility/reports/week2 True
notebooks /home/soldesk/week2-reproducibility/notebooks True
src /home/soldesk/week2-reproducibility/src True

In [99]:
clean_file = dirs["clean"] / "customers_clean_20260606_v2.csv"
print("clean_file:", clean_file)
print("exists:", clean_file.exists())

clean_file: /home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv
exists: True

In [100]:
df_clean = read_csv(clean_file)
print("df_clean shape:", df_clean.shape)
df_clean.head()

df_clean shape: (9, 29)

,customer_id,age,monthly_fee,usage_days,support_calls,gender_standard,contract_type_standard,signup_date,last_login_date,signup_year,...,monthly_fee_outlier,support_calls_outlier,is_high_fee,is_short_user,has_many_support_calls,usage_group,is_long_contract,churn,gender,contract_type
0,C001,34,59000,120,1,female,monthly,2025-01-10,2026-06-01,2025,...,0,0,1,0,0,middle,0,0,female,month-to-month
1,C002,45,79000,380,3,male,one_year,2024-12-01,2026-05-10,2024,...,0,0,1,0,1,long,1,1,male,1-year
2,C003,41,72000,45,0,female,monthly,2026-04-20,2026-06-03,2026,...,0,0,1,0,0,middle,0,0,female,month-to-month
3,C004,52,99000,800,5,male,one_year,2023-05-15,2026-03-01,2023,...,0,0,1,0,1,long,1,1,male,1-year
4,C005,41,69000,220,2,female,unknown,2025-08-03,2026-05-30,2025,...,0,0,1,0,0,middle,0,0,female,unknown

In [101]:
df_clean.columns.tolist()

['customer_id',
 'age',
 'monthly_fee',
 'usage_days',
 'support_calls',
 'gender_standard',
 'contract_type_standard',
 'signup_date',
 'last_login_date',
 'signup_year',
 'signup_month',
 'last_login_dayofweek',
 'last_login_day_name',
 'days_since_signup',
 'days_since_last_login',
 'age_was_missing',
 'monthly_fee_was_missing',
 'gender_was_missing',
 'contract_type_was_missing',
 'monthly_fee_outlier',
 'support_calls_outlier',
 'is_high_fee',
 'is_short_user',
 'has_many_support_calls',
 'usage_group',
 'is_long_contract',
 'churn',
 'gender',
 'contract_type']

In [102]:
df_clean["churn"].value_counts(dropna=False)

churn
0    5
1    4
Name: count, dtype: int64

In [103]:
test_output_file = dirs["outputs"] / "src_io_test_customers_clean.csv"
saved_path = save_csv(df_clean.head(), test_output_file)
print("saved_path:", saved_path)
print("exists:", saved_path.exists())

saved_path: /home/soldesk/week2-reproducibility/outputs/src_io_test_customers_clean.csv
exists: True

In [104]:
df_saved_check = read_csv(saved_path)
print("df_saved_check shape:", df_saved_check.shape)
df_saved_check.head()

df_saved_check shape: (5, 29)

,customer_id,age,monthly_fee,usage_days,support_calls,gender_standard,contract_type_standard,signup_date,last_login_date,signup_year,...,monthly_fee_outlier,support_calls_outlier,is_high_fee,is_short_user,has_many_support_calls,usage_group,is_long_contract,churn,gender,contract_type
0,C001,34,59000,120,1,female,monthly,2025-01-10,2026-06-01,2025,...,0,0,1,0,0,middle,0,0,female,month-to-month
1,C002,45,79000,380,3,male,one_year,2024-12-01,2026-05-10,2024,...,0,0,1,0,1,long,1,1,male,1-year
2,C003,41,72000,45,0,female,monthly,2026-04-20,2026-06-03,2026,...,0,0,1,0,0,middle,0,0,female,month-to-month
3,C004,52,99000,800,5,male,one_year,2023-05-15,2026-03-01,2023,...,0,0,1,0,1,long,1,1,male,1-year
4,C005,41,69000,220,2,female,unknown,2025-08-03,2026-05-30,2025,...,0,0,1,0,0,middle,0,0,female,unknown

In [105]:
src_test_info = {
    "author": "student",
    "src_used": True,
    "modules": [
        "src.seed",
        "src.paths",
        "src.io_utils"
    ],
    "seed_function": "set_seed",
    "path_function": "get_project_dirs",
    "io_functions": [
        "read_csv",
        "save_csv",
        "read_json",
        "save_json"
    ],
    "note": "7교시 src 모듈 분리 테스트"
}
src_test_info_file = dirs["outputs"] / "src_test_info.json"
save_json(src_test_info, src_test_info_file)
print("saved:", src_test_info_file)
print("exists:", src_test_info_file.exists())

saved: /home/soldesk/week2-reproducibility/outputs/src_test_info.json
exists: True

In [106]:
loaded_src_test_info = read_json(src_test_info_file)
loaded_src_test_info

{'author': 'student',
 'src_used': True,
 'modules': ['src.seed', 'src.paths', 'src.io_utils'],
 'seed_function': 'set_seed',
 'path_function': 'get_project_dirs',
 'io_functions': ['read_csv', 'save_csv', 'read_json', 'save_json'],
 'note': '7교시 src 모듈 분리 테스트'}

In [107]:
from datetime import datetime
run_info_file = dirs["outputs"] / "run_info.json"
if run_info_file.exists():
    run_info = read_json(run_info_file)
else:
    run_info = {}
run_info["period7_src_split"] = {
    "updated_at": datetime.now().isoformat(),
    "src_used": True,
    "src_modules": [
        "src.seed",
        "src.paths",
        "src.io_utils"
    ],
    "created_files": [
        "src/__init__.py",
        "src/seed.py",
        "src/paths.py",
        "src/io_utils.py"
    ],
    "seed_function": "set_seed",
    "path_functions": [
        "get_project_root",
        "get_project_dirs"
    ],
    "io_functions": [
        "read_csv",
        "save_csv",
        "read_json",
        "save_json"
    ],
    "clean_file": str(clean_file),
    "clean_file_exists": clean_file.exists(),
    "read_test_shape": list(df_clean.shape),
    "save_test_file": str(saved_path),
    "save_test_file_exists": saved_path.exists(),
    "notebook_role": "experiment_and_record",
    "src_role": "reusable_python_code",
    "script_ready": True,
    "openshift_local_used": False,
    "developer_sandbox_used": False,
    "g4dn_used": False,
    "h200_used": False,
    "note": "7교시에서 Notebook 반복 코드를 src 모듈로 분리하고 import 테스트를 수행함"
}
save_json(run_info, run_info_file)
print("run_info.json 업데이트 완료:", run_info_file)

run_info.json 업데이트 완료: /home/soldesk/week2-reproducibility/outputs/run_info.json

In [108]:
loaded_run_info = read_json(run_info_file)
loaded_run_info["period7_src_split"]

{'updated_at': '2026-06-29T12:02:29.039018',
 'src_used': True,
 'src_modules': ['src.seed', 'src.paths', 'src.io_utils'],
 'created_files': ['src/__init__.py',
  'src/seed.py',
  'src/paths.py',
  'src/io_utils.py'],
 'seed_function': 'set_seed',
 'path_functions': ['get_project_root', 'get_project_dirs'],
 'io_functions': ['read_csv', 'save_csv', 'read_json', 'save_json'],
 'clean_file': '/home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv',
 'clean_file_exists': True,
 'read_test_shape': [9, 29],
 'save_test_file': '/home/soldesk/week2-reproducibility/outputs/src_io_test_customers_clean.csv',
 'save_test_file_exists': True,
 'notebook_role': 'experiment_and_record',
 'src_role': 'reusable_python_code',
 'script_ready': True,
 'openshift_local_used': False,
 'developer_sandbox_used': False,
 'g4dn_used': False,
 'h200_used': False,
 'note': '7교시에서 Notebook 반복 코드를 src 모듈로 분리하고 import 테스트를 수행함'}

In [109]:
from pathlib import Path
import pandas as pd
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
files = sorted([
    str(path.relative_to(BASE_DIR))
    for path in BASE_DIR.rglob("*")
    if path.is_file()
])
pd.DataFrame({"file": files})

                                        file
0                                       .env
1                               .env.example
2                        .git/COMMIT_EDITMSG
3                                  .git/HEAD
4                                .git/config
...                                      ...
24885  src/__pycache__/paths.cpython-312.pyc
24886   src/__pycache__/seed.cpython-312.pyc
24887                        src/io_utils.py
24888                           src/paths.py
24889                            src/seed.py

[24890 rows x 1 columns]

In [110]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

EXCLUDE_DIRS = {
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    ".ipynb_checkpoints",
    ".pytest_cache",
}

EXCLUDE_FILES = {
    ".env",
}

MAX_DEPTH = 3

files = []

for path in BASE_DIR.rglob("*"):
    if not path.is_file():
        continue

    relative_path = path.relative_to(BASE_DIR)
    parts = relative_path.parts

    # 제외할 폴더가 경로 안에 있으면 제외
    if any(part in EXCLUDE_DIRS for part in parts):
        continue

    # 제외할 파일이면 제외
    if relative_path.name in EXCLUDE_FILES:
        continue

    # WSL2 find . -maxdepth 3 과 비슷하게 깊이 제한
    if len(parts) > MAX_DEPTH:
        continue

    files.append(str(relative_path))

files = sorted(files)

pd.DataFrame({"file": files})

                                                 file
0                                        .env.example
1                                          .gitignore
2                                           README.md
3          data/clean/customers_clean_20260606_v2.csv
4      data/clean/customers_clean_20260606_v2.parquet
5                          data/raw/customers_raw.csv
6       notebooks/01_python_data_handling_basic.ipynb
7   notebooks/02_data_preprocessing_quality_check....
8      notebooks/03_reproducibility_environment.ipynb
9                     outputs/env_config_summary.json
10              outputs/reproducibility_run_record.md
11                              outputs/run_info.json
12                     outputs/seed_split_result.json
13            outputs/src_io_test_customers_clean.csv
14                         outputs/src_test_info.json
15                 outputs/venv_environment_record.md
16                                   requirements.txt
17                        scripts/check_clean_data.py
18                                    src/__init__.py
19                                    src/io_utils.py
20                                       src/paths.py
21                                        src/seed.py

In [111]:
required_artifacts = {
    "day3_notebook": BASE_DIR / "notebooks" / "03_reproducibility_environment.ipynb",
    "requirements": BASE_DIR / "requirements.txt",
    "requirements_minimal": BASE_DIR / "requirements-minimal.txt",
    "env_example": BASE_DIR / ".env.example",
    "gitignore": BASE_DIR / ".gitignore",
    "readme": BASE_DIR / "README.md",
    "src_init": BASE_DIR / "src" / "__init__.py",
    "src_seed": BASE_DIR / "src" / "seed.py",
    "src_paths": BASE_DIR / "src" / "paths.py",
    "src_io_utils": BASE_DIR / "src" / "io_utils.py",
    "run_info": BASE_DIR / "outputs" / "run_info.json",
    "seed_split_result": BASE_DIR / "outputs" / "seed_split_result.json",
    "env_config_summary": BASE_DIR / "outputs" / "env_config_summary.json",
    "src_test_info": BASE_DIR / "outputs" / "src_test_info.json",
    "openshift_guide": BASE_DIR / "outputs" / "openshift_same_execution_guide.md",
}
artifact_status = []
for name, path in required_artifacts.items():
    artifact_status.append({
        "name": name,
        "path": str(path.relative_to(BASE_DIR)),
        "exists": path.exists()
    })
artifact_status_df = pd.DataFrame(artifact_status)
artifact_status_df

,name,path,exists
0,day3_notebook,notebooks/03_reproducibility_environment.ipynb,True
1,requirements,requirements.txt,True
2,requirements_minimal,requirements-minimal.txt,False
3,env_example,.env.example,True
4,gitignore,.gitignore,True
5,readme,README.md,True
6,src_init,src/__init__.py,True
7,src_seed,src/seed.py,True
8,src_paths,src/paths.py,True
9,src_io_utils,src/io_utils.py,True
10,run_info,outputs/run_info.json,True
11,seed_split_result,outputs/seed_split_result.json,True
12,env_config_summary,outputs/env_config_summary.json,True
13,src_test_info,outputs/src_test_info.json,True
14,openshift_guide,outputs/openshift_same_execution_guide.md,False

In [112]:
import json
from datetime import datetime
day3_final_summary = {
    "author": "student",
    "day": "week2_day3",
    "topic": "reproducibility_and_environment_separation",
    "created_at": datetime.now().isoformat(),
    "execution_environment": "local_wsl2",
    "local_pc_used": True,
    "openshift_local_used": False,
    "developer_sandbox_used": False,
    "g4dn_used": False,
    "h200_used": False,
    "artifacts": artifact_status,
    "reproducibility_elements": {
        "venv": ".venv is created locally but not committed to Git",
        "requirements": "requirements.txt is used to recreate Python package environment",
        "env_example": ".env.example is shared as configuration template",
        "env": ".env is personal and ignored by Git",
        "seed": "SEED is recorded and used for random reproducibility",
        "path": "pathlib.Path and project-relative paths are used",
        "src": "reusable functions are separated into src/",
        "run_info": "outputs/run_info.json stores execution conditions",
        "readme": "README.md documents execution steps"
    },
    "openshift_same_execution_ready": True,
    "openshift_same_execution_guide": "outputs/openshift_same_execution_guide.md",
    "next_day": "week2_day4",
    "next_day_topic": "S3 data upload, versioning, lifecycle, prefix management",
    "note": "Day 3 8교시에서 개인 로컬 PC 기반 재현성 구조를 OpenShift Local/Developer Sandbox 동일 실행 구조로 정리함"
}
day3_final_summary_file = OUTPUT_DIR / "day3_final_artifact_summary.json"
with open(day3_final_summary_file, "w", encoding="utf-8") as f:
    json.dump(day3_final_summary, f, ensure_ascii=False, indent=2)
print("saved:", day3_final_summary_file)
print("exists:", day3_final_summary_file.exists())

saved: /home/soldesk/week2-reproducibility/outputs/day3_final_artifact_summary.json
exists: True

In [115]:
from pathlib import Path
from datetime import datetime
import json

# 현재 실행 위치 기준으로 프로젝트 루트 계산
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# outputs 폴더 준비
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Day 3 최종 산출물 요약 파일 경로
day3_final_summary_file = OUTPUT_DIR / "day3_final_artifact_summary.json"

# OpenShift 동일 실행 가이드 문서 경로
openshift_guide_path = OUTPUT_DIR / "openshift_same_execution_guide.md"

# run_info.json 경로
run_info_file = OUTPUT_DIR / "run_info.json"


def to_relative_path(path: Path) -> str:
    """
    프로젝트 루트 기준 상대 경로 문자열로 변환한다.
    프로젝트 외부 경로인 경우에는 전체 경로 문자열을 반환한다.
    """
    path = Path(path).resolve()

    try:
        return str(path.relative_to(BASE_DIR))
    except ValueError:
        return str(path)


# 기존 run_info.json이 있으면 읽고, 없으면 새 dict 생성
if run_info_file.exists():
    try:
        with open(run_info_file, "r", encoding="utf-8") as f:
            run_info = json.load(f)
    except json.JSONDecodeError:
        print("기존 run_info.json 형식이 올바르지 않아 새로 생성합니다.")
        run_info = {}
else:
    run_info = {}


# 8교시 최종 요약 정보 업데이트
run_info["period8_final_summary"] = {
    "updated_at": datetime.now().isoformat(timespec="seconds"),
    "day3_final_artifact_summary_file": to_relative_path(day3_final_summary_file),
    "openshift_same_execution_guide": to_relative_path(openshift_guide_path),
    "local_pc_execution_ready": True,
    "openshift_same_execution_ready": True,
    "developer_sandbox_same_execution_ready": True,
    "g4dn_used": False,
    "g4dn_note": "Day 3에서는 GPU가 필요 없으므로 g4dn.xlarge를 사용하지 않음. GPU 주차에서 같은 repo 구조를 사용 가능.",
    "day3_completed": True,
    "next_day": "week2_day4",
    "next_day_topic": "S3 data upload, versioning, lifecycle, prefix management",
    "note": "8교시에서 Day 3 산출물과 OpenShift 동일 실행 구조를 최종 정리함"
}


# run_info.json 저장
with open(run_info_file, "w", encoding="utf-8") as f:
    json.dump(run_info, f, ensure_ascii=False, indent=2)


print("run_info.json 최종 업데이트 완료:", run_info_file)
print("exists:", run_info_file.exists())
print("updated_key:", "period8_final_summary")

run_info.json 최종 업데이트 완료: /home/soldesk/week2-reproducibility/outputs/run_info.json
exists: True
updated_key: period8_final_summary

In [116]:
with open(run_info_file, "r", encoding="utf-8") as f:
    loaded_run_info = json.load(f)
loaded_run_info["period8_final_summary"]

{'updated_at': '2026-06-29T12:36:59',
 'day3_final_artifact_summary_file': 'outputs/day3_final_artifact_summary.json',
 'openshift_same_execution_guide': 'outputs/openshift_same_execution_guide.md',
 'local_pc_execution_ready': True,
 'openshift_same_execution_ready': True,
 'developer_sandbox_same_execution_ready': True,
 'g4dn_used': False,
 'g4dn_note': 'Day 3에서는 GPU가 필요 없으므로 g4dn.xlarge를 사용하지 않음. GPU 주차에서 같은 repo 구조를 사용 가능.',
 'day3_completed': True,
 'next_day': 'week2_day4',
 'next_day_topic': 'S3 data upload, versioning, lifecycle, prefix management',
 'note': '8교시에서 Day 3 산출물과 OpenShift 동일 실행 구조를 최종 정리함'}

In [117]:
REPORT_DIR = BASE_DIR / "reports" / "week2"
REPORT_DIR.mkdir(parents=True, exist_ok=True)
day3_report_path = REPORT_DIR / "day3_reproducibility_final_report.md"
day3_report_text = f"""# 2주차 Day 3 재현성 및 환경 분리 최종 리포트
## 1. 작성자
student
## 2. Day 3 주제
실험 재현성과 환경 분리
## 3. 핵심 목표
Day 3의 목표는 개인 로컬 PC에서만 실행되는 코드를 만드는 것이 아니라,
같은 저장소, 같은 requirements.txt, 같은 .env.example, 같은 src 구조,
같은 입력 데이터 기준으로 다른 환경에서도 다시 실행 가능한 구조를 만드는 것이다.
## 4. 실습 환경
| 항목 | 사용 여부 |
|---|---|
| 개인 로컬 PC WSL2 | 사용 |
| OpenShift Local | 앱 배포 없음, 동일 실행 구조만 정리 |
| Developer Sandbox | 앱 배포 없음, 동일 실행 구조만 정리 |
| AWS g4dn.xlarge | 사용하지 않음 |
| H200 | 사용하지 않음 |
## 5. 오늘 만든 핵심 구조
| 항목 | 설명 |
|---|---|
| .venv | 개인 로컬 프로젝트 전용 Python 환경 |
| requirements.txt | 패키지와 버전 기록 |
| .env.example | 공유 가능한 설정 예시 |
| .env | 개인 설정 파일, Git 제외 |
| src/seed.py | seed 고정 함수 |
| src/paths.py | 프로젝트 경로 함수 |
| src/io_utils.py | 파일 읽기/저장 함수 |
| outputs/run_info.json | 실행 조건 누적 기록 |
| README.md | 실행 방법 문서 |
## 6. OpenShift 동일 실행 구조
OpenShift Local 또는 Developer Sandbox에서는 같은 저장소를 가져온 뒤
requirements.txt로 패키지를 설치하고,
.env.example을 기반으로 환경 변수를 설정한 뒤,
src 구조를 사용해 같은 데이터 처리 코드를 실행할 수 있다.
이번 Day 3에서는 OpenShift Deployment, Service, Route를 만들지 않는다.
배포는 이후 OpenShift 배포 주차에서 수행한다.
## 7. g4dn.xlarge 연결
Day 3에서는 GPU 연산이 없으므로 g4dn.xlarge를 사용하지 않는다.
하지만 이후 GPU 실습 주차에서는 같은 저장소 구조,
requirements 파일,
.env.example,
src 구조,
run_info.json 기록 방식을 그대로 사용할 수 있다.
## 8. 최종 산출물
| 산출물 | 경로 |
|---|---|
| Day 3 Notebook | notebooks/03_reproducibility_environment.ipynb |
| requirements | requirements.txt |
| 환경 예시 | .env.example |
| seed 함수 | src/seed.py |
| 경로 함수 | src/paths.py |
| 입출력 함수 | src/io_utils.py |
| 실행 기록 | outputs/run_info.json |
| seed split 결과 | outputs/seed_split_result.json |
| 환경 변수 요약 | outputs/env_config_summary.json |
| src 테스트 결과 | outputs/src_test_info.json |
| OpenShift 동일 실행 가이드 | outputs/openshift_same_execution_guide.md |
| Day 3 최종 산출물 요약 | outputs/day3_final_artifact_summary.json |
## 9. Day 4 연결
Day 4에서는 오늘 만든 재현성 구조를 바탕으로
AWS S3 데이터 적재,
S3 Prefix 구조,
데이터 버전관리,
S3 Lifecycle,
raw/ clean/ feature/ 흐름을 다룬다.
## 10. 오늘 이해한 점
재현성은 seed 하나로 끝나지 않는다.
패키지, 경로, 환경 변수, src 구조, 실행 기록, README가 함께 있어야
다른 환경에서도 다시 실행 가능한 실험 구조가 된다.
"""
day3_report_path.write_text(day3_report_text, encoding="utf-8")
print("saved:", day3_report_path)
print("exists:", day3_report_path.exists())

saved: /home/soldesk/week2-reproducibility/reports/week2/day3_reproducibility_final_report.md
exists: True

In [118]:
from pathlib import Path
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
s3_draft_file = OUTPUT_DIR / "day4_s3_data_lake_draft.md"
s3_draft_text = """# Day 4 S3 데이터 레이크 구조 초안
## 1. 작성자
- author: student
## 2. Day 1~3 결과 연결
### Day 1
- 데이터 관찰
- raw 데이터 확인
- data/raw/customers_raw.csv 생성
### Day 2
- clean 데이터 생성
- 전처리 리포트 작성
- data/clean/customers_clean_20260606_v2.csv 생성
### Day 3
- 재현 가능한 실행 환경 구성
- requirements.txt 작성
- .env.example 작성
- src/ 구조 작성
- outputs/run_info.json 작성
## 3. S3를 사용하는 이유
- 개인 PC에만 있는 데이터를 기준 저장소로 옮기기 위해
- raw와 clean을 분리하기 위해
- 데이터 버전을 관리하기 위해
- 실행 로그와 산출물을 함께 보관하기 위해
- 오래된 데이터를 Lifecycle로 관리하기 위해
- OpenShift Local / Developer Sandbox / g4dn에서도 같은 데이터 기준을 사용하기 위해
## 4. Prefix 초안
- common/
- users/<author>/
- raw/
- clean/
- feature/
- notebook/
- artifact/
- log/
- archive/
## 5. raw 데이터 원칙
- 원본 데이터는 수정하지 않는다.
- 원본 데이터는 덮어쓰지 않는다.
- 원본 데이터는 쉽게 삭제하지 않는다.
- 변경이 필요하면 새 파일명과 새 버전으로 업로드한다.
## 6. clean 데이터 원칙
- 전처리 완료 데이터를 저장한다.
- 처리 기준을 리포트에 기록한다.
- 파일명에 날짜와 버전을 포함한다.
- raw와 같은 위치에 섞지 않는다.
## 7. feature 데이터 원칙
- 모델 학습용 특징 데이터를 저장한다.
- train/test split 기준을 기록한다.
- 데이터 누수 위험을 점검한다.
- feature_version을 기록한다.
## 8. log / artifact 원칙
- run_info.json은 log/에 저장한다.
- 리포트와 모델 파일은 artifact/에 저장한다.
- 제출 산출물은 쉽게 삭제하지 않는다.
## 9. 아직 결정해야 할 것
- 버킷 이름:
- 개인 author:
- 개인 Prefix:
- raw 보관 기간:
- clean 보관 기간:
- feature 보관 기간:
- 삭제 권한 기준:
- Versioning 확인 방법:
- Lifecycle 전환 기준:
"""
s3_draft_file.write_text(s3_draft_text, encoding="utf-8")
print("S3 구조 초안 저장:", s3_draft_file)
print("존재 여부:", s3_draft_file.exists())

S3 구조 초안 저장: /home/soldesk/week2-reproducibility/outputs/day4_s3_data_lake_draft.md
존재 여부: True

In [119]:
from pathlib import Path
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
author = "student"
bucket_name = "edu-ai-lake"
prefix_design_file = OUTPUT_DIR / "day4_s3_prefix_design.md"
prefix_design_text = f"""# Day 4 S3 Prefix 설계안
## 1. 작성자
- author: {author}
## 2. 버킷 이름
- bucket: {bucket_name}
## 3. 기본 전략
- strategy: single_bucket_with_user_prefix
- 설명: 버킷 1개 안에서 common/과 users/<author>/ Prefix를 분리한다.
## 4. 공통 Prefix 구조
- common/raw/customers/
- common/reference/week2/
## 5. 개인 Prefix 구조
- users/{author}/raw/customers/
- users/{author}/clean/customers/
- users/{author}/feature/customers/
- users/{author}/notebook/week2/
- users/{author}/artifact/week2/
- users/{author}/log/week2/
- users/{author}/archive/
## 6. 고객 데이터 저장 위치
- raw: users/{author}/raw/customers/
- clean: users/{author}/clean/customers/
- feature: users/{author}/feature/customers/
## 7. 산출물 저장 위치
- notebook: users/{author}/notebook/week2/
- artifact: users/{author}/artifact/week2/
- log: users/{author}/log/week2/
## 8. raw 데이터 원칙
- raw 데이터는 원본이다.
- raw 데이터는 수정하지 않는다.
- raw 데이터는 덮어쓰지 않는다.
- raw 데이터는 쉽게 삭제하지 않는다.
- 변경이 필요하면 새 파일명과 새 버전으로 업로드한다.
## 9. clean 데이터 원칙
- clean 데이터는 전처리 완료 데이터이다.
- 처리 기준은 리포트 또는 run_info에 기록한다.
- 파일명에 날짜와 버전을 포함한다.
- raw와 같은 위치에 섞지 않는다.
## 10. feature 데이터 원칙
- feature 데이터는 모델 학습용 특징 데이터이다.
- train/test split 기준을 기록한다.
- 데이터 누수 위험을 점검한다.
- feature_version을 기록한다.
## 11. log / artifact 원칙
- run_info.json은 log/에 저장한다.
- 업로드 기록 JSON은 log/에 저장한다.
- 리포트와 모델 파일은 artifact/에 저장한다.
- 제출 산출물은 쉽게 삭제하지 않는다.
## 12. OpenShift 연결
- OpenShift Local 또는 Developer Sandbox에서도 같은 S3 Prefix를 사용한다.
- 로컬 경로가 아니라 S3 Prefix 기준으로 데이터를 찾을 수 있어야 한다.
- OpenShift에서는 S3 접근 정보를 Secret 또는 환경 변수로 주입할 수 있다.
## 13. g4dn 연결
- Day 4에서는 g4dn.xlarge를 사용하지 않는다.
- GPU 실습 주차에서는 g4dn에서 생성한 결과물을 같은 users/{author}/artifact/ 또는 log/ Prefix에 저장한다.
## 14. 3교시 업로드 대상
- data/raw/customers_raw.csv → users/{author}/raw/customers/
- data/clean/customers_clean_20260606_v2.csv → users/{author}/clean/customers/
- outputs/run_info.json → users/{author}/log/week2/
"""
prefix_design_file.write_text(prefix_design_text, encoding="utf-8")
print("S3 Prefix 설계안 저장:", prefix_design_file)
print("존재 여부:", prefix_design_file.exists())

S3 Prefix 설계안 저장: /home/soldesk/week2-reproducibility/outputs/day4_s3_prefix_design.md
존재 여부: True

In [120]:
import json
from datetime import datetime
s3_design_info = {
    "day": "week2_day4",
    "lesson": "s3_bucket_prefix_design",
    "author": author,
    "bucket": bucket_name,
    "base_strategy": "single_bucket_with_user_prefix",
    "created_at": datetime.now().isoformat(),
    "common_prefixes": {
        "common_raw_customers": "common/raw/customers/",
        "common_reference_week2": "common/reference/week2/"
    },
    "user_prefix": f"users/{author}/",
    "prefixes": {
        "raw": f"users/{author}/raw/",
        "clean": f"users/{author}/clean/",
        "feature": f"users/{author}/feature/",
        "notebook": f"users/{author}/notebook/",
        "artifact": f"users/{author}/artifact/",
        "log": f"users/{author}/log/",
        "archive": f"users/{author}/archive/"
    },
    "dataset_prefixes": {
        "customers_raw": f"users/{author}/raw/customers/",
        "customers_clean": f"users/{author}/clean/customers/",
        "customers_feature": f"users/{author}/feature/customers/"
    },
    "week2_prefixes": {
        "notebook_week2": f"users/{author}/notebook/week2/",
        "artifact_week2": f"users/{author}/artifact/week2/",
        "log_week2": f"users/{author}/log/week2/"
    },
    "upload_plan_period3": {
        "raw_source": "data/raw/customers_raw.csv",
        "raw_s3_prefix": f"users/{author}/raw/customers/",
        "clean_source": "data/clean/customers_clean_20260606_v2.csv",
        "clean_s3_prefix": f"users/{author}/clean/customers/",
        "run_info_source": "outputs/run_info.json",
        "run_info_s3_prefix": f"users/{author}/log/week2/"
    },
    "environment_connection": {
        "local_pc_wsl2": True,
        "openshift_local_same_prefix": True,
        "developer_sandbox_same_prefix": True,
        "g4dn_used_in_day4": False,
        "g4dn_future_output_prefix": f"users/{author}/artifact/week7/"
    },
    "principles": {
        "raw": "raw data is original and should not be overwritten or casually deleted",
        "clean": "clean data is processed data and must include processing record",
        "feature": "feature data is model input candidate and must include split/leakage record",
        "log": "run_info and upload records are stored here",
        "artifact": "reports, model files, and submitted outputs are stored here"
    }
}
s3_design_info

{'day': 'week2_day4',
 'lesson': 's3_bucket_prefix_design',
 'author': 'student',
 'bucket': 'edu-ai-lake',
 'base_strategy': 'single_bucket_with_user_prefix',
 'created_at': '2026-06-29T12:57:47.400891',
 'common_prefixes': {'common_raw_customers': 'common/raw/customers/',
  'common_reference_week2': 'common/reference/week2/'},
 'user_prefix': 'users/student/',
 'prefixes': {'raw': 'users/student/raw/',
  'clean': 'users/student/clean/',
  'feature': 'users/student/feature/',
  'notebook': 'users/student/notebook/',
  'artifact': 'users/student/artifact/',
  'log': 'users/student/log/',
  'archive': 'users/student/archive/'},
 'dataset_prefixes': {'customers_raw': 'users/student/raw/customers/',
  'customers_clean': 'users/student/clean/customers/',
  'customers_feature': 'users/student/feature/customers/'},
 'week2_prefixes': {'notebook_week2': 'users/student/notebook/week2/',
  'artifact_week2': 'users/student/artifact/week2/',
  'log_week2': 'users/student/log/week2/'},
 'upload_plan_period3': {'raw_source': 'data/raw/customers_raw.csv',
  'raw_s3_prefix': 'users/student/raw/customers/',
  'clean_source': 'data/clean/customers_clean_20260606_v2.csv',
  'clean_s3_prefix': 'users/student/clean/customers/',
  'run_info_source': 'outputs/run_info.json',
  'run_info_s3_prefix': 'users/student/log/week2/'},
 'environment_connection': {'local_pc_wsl2': True,
  'openshift_local_same_prefix': True,
  'developer_sandbox_same_prefix': True,
  'g4dn_used_in_day4': False,
  'g4dn_future_output_prefix': 'users/student/artifact/week7/'},
 'principles': {'raw': 'raw data is original and should not be overwritten or casually deleted',
  'clean': 'clean data is processed data and must include processing record',
  'feature': 'feature data is model input candidate and must include split/leakage record',
  'log': 'run_info and upload records are stored here',
  'artifact': 'reports, model files, and submitted outputs are stored here'}}

In [121]:
s3_design_json_file = OUTPUT_DIR / "day4_s3_prefix_design.json"
with open(s3_design_json_file, "w", encoding="utf-8") as f:
    json.dump(s3_design_info, f, ensure_ascii=False, indent=2)
print("S3 Prefix 설계 JSON 저장:", s3_design_json_file)
print("존재 여부:", s3_design_json_file.exists())

S3 Prefix 설계 JSON 저장: /home/soldesk/week2-reproducibility/outputs/day4_s3_prefix_design.json
존재 여부: True

In [122]:
with open(s3_design_json_file, "r", encoding="utf-8") as f:
    loaded_s3_design_info = json.load(f)
loaded_s3_design_info

{'day': 'week2_day4',
 'lesson': 's3_bucket_prefix_design',
 'author': 'student',
 'bucket': 'edu-ai-lake',
 'base_strategy': 'single_bucket_with_user_prefix',
 'created_at': '2026-06-29T12:57:47.400891',
 'common_prefixes': {'common_raw_customers': 'common/raw/customers/',
  'common_reference_week2': 'common/reference/week2/'},
 'user_prefix': 'users/student/',
 'prefixes': {'raw': 'users/student/raw/',
  'clean': 'users/student/clean/',
  'feature': 'users/student/feature/',
  'notebook': 'users/student/notebook/',
  'artifact': 'users/student/artifact/',
  'log': 'users/student/log/',
  'archive': 'users/student/archive/'},
 'dataset_prefixes': {'customers_raw': 'users/student/raw/customers/',
  'customers_clean': 'users/student/clean/customers/',
  'customers_feature': 'users/student/feature/customers/'},
 'week2_prefixes': {'notebook_week2': 'users/student/notebook/week2/',
  'artifact_week2': 'users/student/artifact/week2/',
  'log_week2': 'users/student/log/week2/'},
 'upload_plan_period3': {'raw_source': 'data/raw/customers_raw.csv',
  'raw_s3_prefix': 'users/student/raw/customers/',
  'clean_source': 'data/clean/customers_clean_20260606_v2.csv',
  'clean_s3_prefix': 'users/student/clean/customers/',
  'run_info_source': 'outputs/run_info.json',
  'run_info_s3_prefix': 'users/student/log/week2/'},
 'environment_connection': {'local_pc_wsl2': True,
  'openshift_local_same_prefix': True,
  'developer_sandbox_same_prefix': True,
  'g4dn_used_in_day4': False,
  'g4dn_future_output_prefix': 'users/student/artifact/week7/'},
 'principles': {'raw': 'raw data is original and should not be overwritten or casually deleted',
  'clean': 'clean data is processed data and must include processing record',
  'feature': 'feature data is model input candidate and must include split/leakage record',
  'log': 'run_info and upload records are stored here',
  'artifact': 'reports, model files, and submitted outputs are stored here'}}

In [123]:
from pathlib import Path
import textwrap

# 현재 실행 위치가 notebooks/이면 부모 폴더를 프로젝트 루트로 사용
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# 저장할 reports/week2 폴더 생성
REPORT_DIR = BASE_DIR / "reports" / "week2"
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# 저장 파일 경로
record_file = REPORT_DIR / "day4_period2_s3_prefix_design_record.md"

# 실습 기록지 내용
record_text = textwrap.dedent("""
# 2주차 Day 4 2교시 실습 기록지

## 작성자

## 1. 오늘 주제

S3 버킷 / Prefix 구조 설계

## 2. 버킷 개념

- S3 버킷이란?

## 3. Prefix 개념

- Prefix란?

## 4. 버킷 이름

- bucket:

## 5. 개인 author

- author:

## 6. 기본 전략

- 선택 전략:
- 선택 이유:

## 7. 공통 Prefix

| Prefix | 목적 |
|---|---|
| common/raw/customers/ |  |
| common/reference/week2/ |  |

## 8. 개인 Prefix

| Prefix | 목적 |
|---|---|
| users/&lt;author&gt;/raw/customers/ |  |
| users/&lt;author&gt;/clean/customers/ |  |
| users/&lt;author&gt;/feature/customers/ |  |
| users/&lt;author&gt;/notebook/week2/ |  |
| users/&lt;author&gt;/artifact/week2/ |  |
| users/&lt;author&gt;/log/week2/ |  |
| users/&lt;author&gt;/archive/ |  |

## 9. 3교시 업로드 계획

| 로컬 파일 | S3 Prefix |
|---|---|
| data/raw/customers_raw.csv |  |
| data/clean/customers_clean_20260606_v2.csv |  |
| outputs/run_info.json |  |

## 10. OpenShift 연결

- OpenShift Local 또는 Developer Sandbox에서 같은 Prefix를 어떻게 사용할 것인가?

## 11. g4dn 연결

- g4dn GPU 실습 결과는 어느 Prefix에 저장할 것인가?

## 12. 오늘 이해한 점

-
""").strip() + "\n"

# 파일 저장
record_file.write_text(record_text, encoding="utf-8")

print("saved:", record_file)
print("exists:", record_file.exists())
print("relative_path:", record_file.relative_to(BASE_DIR))

saved: /home/soldesk/week2-reproducibility/reports/week2/day4_period2_s3_prefix_design_record.md
exists: True
relative_path: reports/week2/day4_period2_s3_prefix_design_record.md

In [124]:
import json
from pathlib import Path
from datetime import datetime
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
author = "student"
bucket_name = "edu-ai-lake"
upload_record = {
    "day": "week2_day4",
    "lesson": "period3_raw_clean_s3_upload",
    "author": author,
    "bucket": bucket_name,
    "created_at": datetime.now().isoformat(),
    "environment": {
        "local_pc_wsl2_used": True,
        "openshift_local_used": False,
        "developer_sandbox_used": False,
        "g4dn_used": False,
        "h200_used": False
    },
    "uploaded_objects": {
        "raw": {
            "local_file": "data/raw/customers_raw.csv",
            "s3_uri": f"s3://{bucket_name}/users/{author}/raw/customers/customers_raw_20260605_v1.csv",
            "data_state": "raw",
            "principle": "original data, do not overwrite casually"
        },
        "clean": {
            "local_file": "data/clean/customers_clean_20260606_v2.csv",
            "s3_uri": f"s3://{bucket_name}/users/{author}/clean/customers/customers_clean_20260606_v2.csv",
            "data_state": "clean",
            "principle": "processed data with date and version"
        },
        "log": {
            "local_file": "outputs/run_info.json",
            "s3_uri": f"s3://{bucket_name}/users/{author}/log/week2/run_info_20260606_{author}.json",
            "data_state": "log",
            "principle": "execution condition record"
        },
        "artifact": {
            "local_file": "reports/week2/day3_reproducibility_final_report.md",
            "s3_uri": f"s3://{bucket_name}/users/{author}/artifact/week2/day3_reproducibility_final_report_{author}.md",
            "data_state": "artifact",
            "principle": "report or output artifact"
        }
    },
    "upload_rules": {
        "raw_prefix": f"users/{author}/raw/customers/",
        "clean_prefix": f"users/{author}/clean/customers/",
        "log_prefix": f"users/{author}/log/week2/",
        "artifact_prefix": f"users/{author}/artifact/week2/",
        "do_not_mix_raw_and_clean": True,
        "raw_overwrite_allowed": False,
        "clean_filename_should_include_date_and_version": True
    },
    "next_lesson": "file naming rule and data loading rule documentation"
}
upload_record_file = OUTPUT_DIR / "day4_s3_upload_record.json"
with open(upload_record_file, "w", encoding="utf-8") as f:
    json.dump(upload_record, f, ensure_ascii=False, indent=2)
print("saved:", upload_record_file)
print("exists:", upload_record_file.exists())

saved: /home/soldesk/week2-reproducibility/outputs/day4_s3_upload_record.json
exists: True

In [125]:
with open(upload_record_file, "r", encoding="utf-8") as f:
    loaded_upload_record = json.load(f)
loaded_upload_record

{'day': 'week2_day4',
 'lesson': 'period3_raw_clean_s3_upload',
 'author': 'student',
 'bucket': 'edu-ai-lake',
 'created_at': '2026-06-29T15:02:16.863249',
 'environment': {'local_pc_wsl2_used': True,
  'openshift_local_used': False,
  'developer_sandbox_used': False,
  'g4dn_used': False,
  'h200_used': False},
 'uploaded_objects': {'raw': {'local_file': 'data/raw/customers_raw.csv',
   's3_uri': 's3://edu-ai-lake/users/student/raw/customers/customers_raw_20260605_v1.csv',
   'data_state': 'raw',
   'principle': 'original data, do not overwrite casually'},
  'clean': {'local_file': 'data/clean/customers_clean_20260606_v2.csv',
   's3_uri': 's3://edu-ai-lake/users/student/clean/customers/customers_clean_20260606_v2.csv',
   'data_state': 'clean',
   'principle': 'processed data with date and version'},
  'log': {'local_file': 'outputs/run_info.json',
   's3_uri': 's3://edu-ai-lake/users/student/log/week2/run_info_20260606_student.json',
   'data_state': 'log',
   'principle': 'execution condition record'},
  'artifact': {'local_file': 'reports/week2/day3_reproducibility_final_report.md',
   's3_uri': 's3://edu-ai-lake/users/student/artifact/week2/day3_reproducibility_final_report_student.md',
   'data_state': 'artifact',
   'principle': 'report or output artifact'}},
 'upload_rules': {'raw_prefix': 'users/student/raw/customers/',
  'clean_prefix': 'users/student/clean/customers/',
  'log_prefix': 'users/student/log/week2/',
  'artifact_prefix': 'users/student/artifact/week2/',
  'do_not_mix_raw_and_clean': True,
  'raw_overwrite_allowed': False,
  'clean_filename_should_include_date_and_version': True},
 'next_lesson': 'file naming rule and data loading rule documentation'}

In [126]:
from pathlib import Path
import os
import textwrap

# 현재 실행 위치가 notebooks/이면 부모 폴더를 프로젝트 루트로 사용
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# outputs 폴더 준비
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# 기존 셀에서 author, bucket_name 변수가 있으면 사용하고,
# 없으면 환경 변수 또는 기본값 사용
author = globals().get("author", os.environ.get("AUTHOR", "student"))
bucket_name = globals().get("bucket_name", os.environ.get("S3_BUCKET", "edu-ai-lake"))

# 저장 파일 경로
upload_record_md_file = OUTPUT_DIR / "day4_s3_upload_record.md"

# S3 업로드 기록 Markdown 내용
upload_record_md = f"""
# Day 4 3교시 S3 업로드 기록

## 1. 작성자

- author: {author}

## 2. 버킷

- bucket: {bucket_name}

## 3. 업로드 목적

Day 1~3에서 만든 raw 데이터, clean 데이터, 실행 기록, 리포트 산출물을  
S3 Prefix 구조에 맞게 업로드했다.

핵심은 파일을 올리는 것이 아니라  
데이터 상태에 맞는 위치에 올리는 것이다.

## 4. 업로드한 파일

| 구분 | 로컬 파일 | S3 위치 | 원칙 |
|---|---|---|---|
| raw | data/raw/customers_raw.csv | s3://{bucket_name}/users/{author}/raw/customers/customers_raw_20260605_v1.csv | 원본, 덮어쓰기 금지 |
| clean | data/clean/customers_clean_20260606_v2.csv | s3://{bucket_name}/users/{author}/clean/customers/customers_clean_20260606_v2.csv | 전처리 완료, 날짜/버전 포함 |
| log | outputs/run_info.json | s3://{bucket_name}/users/{author}/log/week2/run_info_20260606_{author}.json | 실행 조건 기록 |
| artifact | reports/week2/day3_reproducibility_final_report.md | s3://{bucket_name}/users/{author}/artifact/week2/day3_reproducibility_final_report_{author}.md | 리포트 산출물 |

## 5. 업로드 확인 명령

```bash
aws s3 ls s3://{bucket_name}/users/{author}/ --recursive
```

## 6. raw 데이터 원칙

- raw 데이터는 원본이다.
- raw 데이터는 수정하지 않는다.
- raw 데이터는 같은 이름으로 무심코 덮어쓰지 않는다.
- raw 데이터는 쉽게 삭제하지 않는다.
- 변경이 필요하면 새 파일명과 새 버전으로 업로드한다.

## 7. clean 데이터 원칙

- clean 데이터는 전처리 완료 데이터이다.
- raw와 같은 위치에 섞지 않는다.
- 파일명에 날짜와 버전을 포함한다.
- 처리 기준은 log 또는 artifact와 함께 보관한다.

## 8. log / artifact 원칙

- run_info.json은 log/에 저장한다.
- 리포트와 제출 산출물은 artifact/에 저장한다.
- log는 실행 조건 추적용이다.
- artifact는 결과 산출물 보관용이다.

## 9. OpenShift / g4dn 연결

- OpenShift Local 또는 Developer Sandbox에서도 같은 S3 Prefix를 사용할 수 있다.
- g4dn.xlarge는 이번 교시에서 사용하지 않는다.
- 이후 GPU 실습 결과는 users/{author}/artifact/week7/ 또는 users/{author}/log/week7/에 저장할 수 있다.

## 10. 다음 교시 연결

4교시에서는 final.csv, new.csv 같은 애매한 파일명을 피하고,  
dataset_stage_yyyymmdd_version 형식의 파일명 규칙과 데이터 적재 규칙을 문서화한다.
"""

# 불필요한 앞뒤 공백 정리 후 저장
upload_record_md = textwrap.dedent(upload_record_md).strip() + "\n"

upload_record_md_file.write_text(upload_record_md, encoding="utf-8")

print("saved:", upload_record_md_file)
print("exists:", upload_record_md_file.exists())
print("relative_path:", upload_record_md_file.relative_to(BASE_DIR))

saved: /home/soldesk/week2-reproducibility/outputs/day4_s3_upload_record.md
exists: True
relative_path: outputs/day4_s3_upload_record.md

In [127]:
from pathlib import Path
import os
import textwrap

# 현재 실행 위치가 notebooks/이면 부모 폴더를 프로젝트 루트로 사용
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# reports/week2 폴더 준비
REPORT_DIR = BASE_DIR / "reports" / "week2"
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# 기존 셀에서 author, bucket_name 변수가 있으면 사용하고,
# 없으면 환경 변수 또는 기본값 사용
author = globals().get("author", os.environ.get("AUTHOR", "student"))
bucket_name = globals().get("bucket_name", os.environ.get("S3_BUCKET", "edu-ai-lake"))

# Prefix 정의
raw_prefix = f"users/{author}/raw/customers/"
clean_prefix = f"users/{author}/clean/customers/"
log_prefix = f"users/{author}/log/week2/"
artifact_prefix = f"users/{author}/artifact/week2/"

# 업로드 대상 로컬 파일
raw_local_file = "data/raw/customers_raw.csv"
clean_local_file = "data/clean/customers_clean_20260606_v2.csv"
log_local_file = "outputs/run_info.json"
artifact_local_file = "reports/week2/day3_reproducibility_final_report.md"

# S3 URI 정의
raw_s3_uri = f"s3://{bucket_name}/{raw_prefix}customers_raw_20260605_v1.csv"
clean_s3_uri = f"s3://{bucket_name}/{clean_prefix}customers_clean_20260606_v2.csv"
log_s3_uri = f"s3://{bucket_name}/{log_prefix}run_info_20260606_{author}.json"
artifact_s3_uri = f"s3://{bucket_name}/{artifact_prefix}day3_reproducibility_final_report_{author}.md"

# 저장 파일 경로
record_file = REPORT_DIR / "day4_period3_s3_upload_record.md"

# Markdown 내용
record_text = f"""
# 2주차 Day 4 3교시 실습 기록지

## 작성자

- author: {author}

## 1. 오늘 주제

raw / clean 데이터 업로드 실습

## 2. 사용한 버킷

- bucket: {bucket_name}

## 3. 사용한 author

- author: {author}

## 4. 사용한 Prefix

| 구분 | Prefix |
|---|---|
| raw | {raw_prefix} |
| clean | {clean_prefix} |
| log | {log_prefix} |
| artifact | {artifact_prefix} |

## 5. 업로드한 파일

| 구분 | 로컬 파일 | 업로드 여부 |
|---|---|---|
| raw | {raw_local_file} | 확인 필요 |
| clean | {clean_local_file} | 확인 필요 |
| log | {log_local_file} | 확인 필요 |
| artifact | {artifact_local_file} | 확인 필요 |

## 6. S3 업로드 경로

| 구분 | S3 URI |
|---|---|
| raw | {raw_s3_uri} |
| clean | {clean_s3_uri} |
| log | {log_s3_uri} |
| artifact | {artifact_s3_uri} |

## 7. 업로드 확인 명령

```bash
aws s3 ls s3://{bucket_name}/users/{author}/ --recursive
```

## 8. 업로드 결과

| 항목 | 결과 |
|---|---|
| raw 객체 확인 |  |
| clean 객체 확인 |  |
| log 객체 확인 |  |
| artifact 객체 확인 |  |

## 9. raw 데이터 원칙

- raw 데이터는 왜 덮어쓰면 안 되는가?

## 10. clean 데이터 원칙

- clean 데이터 파일명에는 왜 날짜와 버전이 들어가야 하는가?

## 11. OpenShift 연결

- OpenShift Local 또는 Developer Sandbox에서 같은 S3 Prefix를 어떻게 사용할 것인가?

## 12. g4dn 연결

- g4dn GPU 실습 결과는 어느 Prefix에 저장할 것인가?

## 13. 오늘 이해한 점

-

## 14. 다음 교시에서 할 일

파일명 규칙 + 데이터 적재 규칙 문서화
"""

# 불필요한 앞뒤 공백 정리 후 저장
record_text = textwrap.dedent(record_text).strip() + "\n"

record_file.write_text(record_text, encoding="utf-8")

print("saved:", record_file)
print("exists:", record_file.exists())
print("relative_path:", record_file.relative_to(BASE_DIR))

saved: /home/soldesk/week2-reproducibility/reports/week2/day4_period3_s3_upload_record.md
exists: True
relative_path: reports/week2/day4_period3_s3_upload_record.md

In [128]:
from pathlib import Path
import os
import textwrap

# 현재 실행 위치가 notebooks/이면 부모 폴더를 프로젝트 루트로 사용
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# outputs 폴더 준비
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# 기존 셀에서 AUTHOR, BUCKET 변수가 있으면 사용하고,
# 없으면 환경 변수 또는 기본값 사용
AUTHOR = globals().get("AUTHOR", os.environ.get("AUTHOR", "student"))
BUCKET = globals().get("BUCKET", os.environ.get("S3_BUCKET", "edu-ai-lake"))

# 저장 파일 경로
file_naming_rules_file = OUTPUT_DIR / "day4_s3_file_naming_rules.md"

# Markdown 문서 내용
file_naming_rules_text = f"""
# Day 4 S3 파일명 규칙

## 1. 작성자

- author: {AUTHOR}

## 2. 버킷

- bucket: {BUCKET}

## 3. 기본 파일명 규칙

```text
{{dataset}}_{{stage}}_{{yyyymmdd}}_v{{version}}.{{ext}}
```

## 4. 구성 요소

| 요소 | 의미 | 예시 |
|---|---|---|
| dataset | 데이터셋 이름 | customers |
| stage | 데이터 상태 또는 산출물 유형 | raw, clean, feature, log, report |
| yyyymmdd | 생성일 또는 기준일 | 20260606 |
| version | 버전 | v1, v2 |
| ext | 확장자 | csv, parquet, json, md, ipynb |

## 5. 나쁜 파일명 예시

- customers.csv
- customers_new.csv
- customers_final.csv
- customers_final2.csv
- customers_real_final.csv
- new.csv
- final.csv
- result.csv
- data.csv

## 6. 좋은 파일명 예시

- customers_raw_20260605_v1.csv
- customers_clean_20260606_v2.csv
- customers_feature_20260607_v1.parquet
- run_info_week2_day4_20260606_v1.json
- day4_s3_upload_record_20260606_v1.md

## 7. 데이터 상태별 예시

| stage | 예시 파일명 | 저장 Prefix |
|---|---|---|
| raw | customers_raw_20260605_v1.csv | users/{AUTHOR}/raw/customers/ |
| clean | customers_clean_20260606_v2.csv | users/{AUTHOR}/clean/customers/ |
| feature | customers_feature_20260607_v1.parquet | users/{AUTHOR}/feature/customers/ |
| log | run_info_week2_day4_20260606_v1.json | users/{AUTHOR}/log/week2/ |
| report | day4_s3_data_loading_rules_20260606_v1.md | users/{AUTHOR}/artifact/week2/ |
| notebook | 03_reproducibility_environment_20260606_v1.ipynb | users/{AUTHOR}/notebook/week2/ |

## 8. 버전 증가 기준

- 전처리 기준이 바뀌면 버전을 증가시킨다.
- 컬럼이 추가되면 버전을 증가시킨다.
- 컬럼이 삭제되면 버전을 증가시킨다.
- target 정의가 바뀌면 버전을 증가시킨다.
- feature 생성 기준이 바뀌면 버전을 증가시킨다.
- 단순 파일 이동은 버전 증가 대상이 아닐 수 있으나 기록은 남긴다.

## 9. 파일명 버전과 S3 Versioning의 차이

| 구분 | 파일명 버전 | S3 Versioning |
|---|---|---|
| 예시 | customers_clean_20260606_v2.csv | S3 VersionId |
| 목적 | 사람이 이해하는 데이터 버전 | 덮어쓰기와 삭제 실수 복구 |
| 관리 위치 | 파일명 | S3 내부 객체 버전 |
| 운영 기준 | 반드시 필요 | 버킷 설정으로 보완 |

## 10. 핵심 원칙

좋은 파일명은 파일을 열어보지 않아도  
데이터셋, 상태, 생성일, 버전을 알 수 있어야 한다.
"""

# 불필요한 앞뒤 공백 정리 후 저장
file_naming_rules_text = textwrap.dedent(file_naming_rules_text).strip() + "\n"

file_naming_rules_file.write_text(file_naming_rules_text, encoding="utf-8")

print("파일명 규칙 문서 저장:", file_naming_rules_file)
print("존재 여부:", file_naming_rules_file.exists())
print("상대 경로:", file_naming_rules_file.relative_to(BASE_DIR))

파일명 규칙 문서 저장: /home/soldesk/week2-reproducibility/outputs/day4_s3_file_naming_rules.md
존재 여부: True
상대 경로: outputs/day4_s3_file_naming_rules.md

In [129]:
from pathlib import Path
import os
import textwrap

# 현재 실행 위치가 notebooks/이면 부모 폴더를 프로젝트 루트로 사용
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# outputs 폴더 준비
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# 기존 셀에서 AUTHOR 또는 author 변수가 있으면 사용하고,
# 없으면 환경 변수 또는 기본값 사용
AUTHOR = globals().get(
    "AUTHOR",
    globals().get("author", os.environ.get("AUTHOR", "student"))
)

# 기존 셀에서 BUCKET 또는 bucket_name 변수가 있으면 사용하고,
# 없으면 환경 변수 또는 기본값 사용
BUCKET = globals().get(
    "BUCKET",
    globals().get("bucket_name", os.environ.get("S3_BUCKET", "edu-ai-lake"))
)

# 저장 파일 경로
data_loading_rules_file = OUTPUT_DIR / "day4_s3_data_loading_rules.md"

# Markdown 문서 내용
data_loading_rules_text = f"""
# Day 4 S3 데이터 적재 규칙

## 1. 작성자

- author: {AUTHOR}

## 2. 버킷

- bucket: {BUCKET}

## 3. Prefix 구조

| Prefix | 역할 |
|---|---|
| users/{AUTHOR}/raw/customers/ | 원본 고객 데이터 |
| users/{AUTHOR}/clean/customers/ | 전처리 완료 고객 데이터 |
| users/{AUTHOR}/feature/customers/ | 모델 학습용 고객 feature 데이터 |
| users/{AUTHOR}/notebook/week2/ | Week 2 Notebook |
| users/{AUTHOR}/artifact/week2/ | Week 2 리포트와 산출물 |
| users/{AUTHOR}/log/week2/ | Week 2 실행 기록과 업로드 기록 |
| users/{AUTHOR}/archive/ | 장기 보관 데이터 |

## 4. 파일명 규칙

형식:

```text
{{dataset}}_{{stage}}_{{yyyymmdd}}_v{{version}}.{{ext}}
```

예:

```text
customers_clean_20260606_v2.csv
```

## 5. raw 데이터 규칙

- 원본 데이터만 저장한다.
- 수정하지 않는다.
- 덮어쓰지 않는다.
- 쉽게 삭제하지 않는다.
- 변경이 필요하면 새 파일명과 새 버전으로 업로드한다.
- 원본 출처와 업로드 시각을 기록한다.

## 6. clean 데이터 규칙

- 전처리 완료 데이터를 저장한다.
- 처리 기준은 리포트 또는 run_info에 기록한다.
- 파일명에 날짜와 버전을 포함한다.
- raw 데이터와 같은 위치에 섞지 않는다.
- 어떤 raw 데이터에서 만들어졌는지 기록한다.

## 7. feature 데이터 규칙

- 모델 학습용 특징 데이터를 저장한다.
- train/test split 기준을 기록한다.
- 데이터 누수 위험 여부를 점검한다.
- 어떤 clean 데이터에서 만들어졌는지 기록한다.
- 재생성 가능 여부를 기록한다.
- 가능하면 Parquet 형식을 우선 검토한다.

## 8. log 데이터 규칙

- run_info.json을 저장한다.
- 업로드 기록 JSON과 Markdown을 저장한다.
- 실행 날짜, 입력 파일, 출력 파일, seed, author를 기록한다.
- 실험 결과가 달라졌을 때 원인 추적에 사용한다.
- 임의 삭제하지 않는다.

## 9. artifact 데이터 규칙

- 리포트, 결과 산출물, 모델 파일을 저장한다.
- 최종 제출 산출물은 쉽게 삭제하지 않는다.
- 파일명에 날짜와 author를 포함한다.
- log와 artifact의 역할을 구분한다.
- log는 실행 조건 기록이고 artifact는 결과 산출물이다.

## 10. notebook 데이터 규칙

- 실습 Notebook을 저장한다.
- 실행 순서와 Markdown 설명을 포함한다.
- 필요 시 출력 결과 포함 여부를 교육 기준에 맞춘다.
- 파일명에 주차, Day, 날짜, 버전을 포함할 수 있다.

## 11. archive 규칙

- 오래되었지만 보존해야 하는 데이터를 저장한다.
- Lifecycle 정책 또는 승인 기준에 따라 이동한다.
- 삭제 전 확인 절차를 거친다.

## 12. 삭제 제한 대상

- raw/
- log/
- 최종 제출 artifact/
- 다른 개인의 users/ Prefix
- 출처 확인이 되지 않은 공통 데이터

## 13. OpenShift 연결

- OpenShift Local 또는 Developer Sandbox에서도 같은 S3 Prefix를 사용한다.
- S3_BUCKET, S3_CLEAN_PREFIX, S3_LOG_PREFIX는 환경 변수 또는 ConfigMap으로 주입할 수 있다.
- AWS 인증 정보는 Secret 또는 더 안전한 인증 방식으로 다룬다.

## 14. g4dn 연결

- Day 4에서는 g4dn.xlarge를 사용하지 않는다.
- GPU 실습 주차에서는 g4dn 실행 결과를 users/{AUTHOR}/artifact/week7/ 또는 users/{AUTHOR}/log/week7/에 저장한다.
- GPU 실행 로그에도 파일명 규칙을 적용한다.

## 15. 다음 교시 연결

5교시에서는 같은 파일명으로 다시 업로드했을 때  
S3 Versioning이 어떻게 동작하는지 확인한다.
"""

# 불필요한 앞뒤 공백 정리 후 저장
data_loading_rules_text = textwrap.dedent(data_loading_rules_text).strip() + "\n"

data_loading_rules_file.write_text(data_loading_rules_text, encoding="utf-8")

print("S3 데이터 적재 규칙 문서 저장:", data_loading_rules_file)
print("존재 여부:", data_loading_rules_file.exists())
print("상대 경로:", data_loading_rules_file.relative_to(BASE_DIR))

S3 데이터 적재 규칙 문서 저장: /home/soldesk/week2-reproducibility/outputs/day4_s3_data_loading_rules.md
존재 여부: True
상대 경로: outputs/day4_s3_data_loading_rules.md

In [130]:
print(data_loading_rules_file.read_text(encoding="utf-8")[:1000])

# Day 4 S3 데이터 적재 규칙

## 1. 작성자

- author: kim-juil

## 2. 버킷

- bucket: edu-ai-lake

## 3. Prefix 구조

| Prefix | 역할 |
|---|---|
| users/kim-juil/raw/customers/ | 원본 고객 데이터 |
| users/kim-juil/clean/customers/ | 전처리 완료 고객 데이터 |
| users/kim-juil/feature/customers/ | 모델 학습용 고객 feature 데이터 |
| users/kim-juil/notebook/week2/ | Week 2 Notebook |
| users/kim-juil/artifact/week2/ | Week 2 리포트와 산출물 |
| users/kim-juil/log/week2/ | Week 2 실행 기록과 업로드 기록 |
| users/kim-juil/archive/ | 장기 보관 데이터 |

## 4. 파일명 규칙

형식:

```text
{dataset}_{stage}_{yyyymmdd}_v{version}.{ext}
```

예:

```text
customers_clean_20260606_v2.csv
```

## 5. raw 데이터 규칙

- 원본 데이터만 저장한다.
- 수정하지 않는다.
- 덮어쓰지 않는다.
- 쉽게 삭제하지 않는다.
- 변경이 필요하면 새 파일명과 새 버전으로 업로드한다.
- 원본 출처와 업로드 시각을 기록한다.

## 6. clean 데이터 규칙

- 전처리 완료 데이터를 저장한다.
- 처리 기준은 리포트 또는 run_info에 기록한다.
- 파일명에 날짜와 버전을 포함한다.
- raw 데이터와 같은 위치에 섞지 않는다.
- 어떤 raw 데이터에서 만들어졌는지 기록한다.

## 7. feature 데이터 규칙

- 모델 학습용 특징 데이터를 저장한다.
- train/test split 기준을 기록한다.
- 데이터 누수 위험 여부를 점검한다.
- 어떤 clean

In [131]:
import json
from datetime import datetime
data_loading_rules_json = {
    "day": "week2_day4",
    "lesson": "period4_file_naming_and_data_loading_rules",
    "author": AUTHOR,
    "bucket": BUCKET,
    "created_at": datetime.now().isoformat(),
    "file_naming_pattern": "{dataset}_{stage}_{yyyymmdd}_v{version}.{ext}",
    "bad_filename_examples": [
        "customers.csv",
        "customers_new.csv",
        "customers_final.csv",
        "customers_final2.csv",
        "customers_real_final.csv",
        "new.csv",
        "final.csv",
        "result.csv",
        "data.csv"
    ],
    "good_filename_examples": [
        "customers_raw_20260605_v1.csv",
        "customers_clean_20260606_v2.csv",
        "customers_feature_20260607_v1.parquet",
        "run_info_week2_day4_20260606_v1.json",
        "day4_s3_upload_record_20260606_v1.md"
    ],
    "prefixes": {
        "raw": f"users/{AUTHOR}/raw/customers/",
        "clean": f"users/{AUTHOR}/clean/customers/",
        "feature": f"users/{AUTHOR}/feature/customers/",
        "notebook": f"users/{AUTHOR}/notebook/week2/",
        "artifact": f"users/{AUTHOR}/artifact/week2/",
        "log": f"users/{AUTHOR}/log/week2/",
        "archive": f"users/{AUTHOR}/archive/"
    },
    "rules": {
        "raw": {
            "description": "original data",
            "overwrite_allowed": False,
            "delete_allowed_by_student": False,
            "filename_example": "customers_raw_20260605_v1.csv"
        },
        "clean": {
            "description": "processed data",
            "must_include_processing_record": True,
            "must_include_date_and_version": True,
            "filename_example": "customers_clean_20260606_v2.csv"
        },
        "feature": {
            "description": "model input features",
            "must_record_split_rule": True,
            "must_check_leakage": True,
            "filename_example": "customers_feature_20260607_v1.parquet"
        },
        "log": {
            "description": "execution and upload records",
            "delete_allowed_by_student": False,
            "filename_examples": [
                "run_info_week2_day4_20260606_v1.json",
                "day4_s3_upload_record_20260606_v1.json"
            ]
        },
        "artifact": {
            "description": "reports and submitted outputs",
            "final_artifact_delete_allowed": False,
            "filename_example": "day4_s3_data_loading_rules_20260606_v1.md"
        }
    },
    "environment_connection": {
        "local_pc_wsl2": True,
        "openshift_local_same_rules": True,
        "developer_sandbox_same_rules": True,
        "g4dn_used_in_day4": False,
        "g4dn_future_rules": "store GPU outputs under artifact/week7 and logs under log/week7"
    },
    "next_lesson": "S3 Versioning concept and overwrite test"
}
data_loading_rules_json_file = OUTPUT_DIR / "day4_s3_data_loading_rules.json"
with open(data_loading_rules_json_file, "w", encoding="utf-8") as f:
    json.dump(data_loading_rules_json, f, ensure_ascii=False, indent=2)
print("S3 데이터 적재 규칙 JSON 저장:", data_loading_rules_json_file)
print("존재 여부:", data_loading_rules_json_file.exists())

S3 데이터 적재 규칙 JSON 저장: /home/soldesk/week2-reproducibility/outputs/day4_s3_data_loading_rules.json
존재 여부: True

In [132]:
with open(data_loading_rules_json_file, "r", encoding="utf-8") as f:
    loaded_rules = json.load(f)
loaded_rules

{'day': 'week2_day4',
 'lesson': 'period4_file_naming_and_data_loading_rules',
 'author': 'kim-juil',
 'bucket': 'edu-ai-lake',
 'created_at': '2026-06-29T15:40:18.587112',
 'file_naming_pattern': '{dataset}_{stage}_{yyyymmdd}_v{version}.{ext}',
 'bad_filename_examples': ['customers.csv',
  'customers_new.csv',
  'customers_final.csv',
  'customers_final2.csv',
  'customers_real_final.csv',
  'new.csv',
  'final.csv',
  'result.csv',
  'data.csv'],
 'good_filename_examples': ['customers_raw_20260605_v1.csv',
  'customers_clean_20260606_v2.csv',
  'customers_feature_20260607_v1.parquet',
  'run_info_week2_day4_20260606_v1.json',
  'day4_s3_upload_record_20260606_v1.md'],
 'prefixes': {'raw': 'users/kim-juil/raw/customers/',
  'clean': 'users/kim-juil/clean/customers/',
  'feature': 'users/kim-juil/feature/customers/',
  'notebook': 'users/kim-juil/notebook/week2/',
  'artifact': 'users/kim-juil/artifact/week2/',
  'log': 'users/kim-juil/log/week2/',
  'archive': 'users/kim-juil/archive/'},
 'rules': {'raw': {'description': 'original data',
   'overwrite_allowed': False,
   'delete_allowed_by_student': False,
   'filename_example': 'customers_raw_20260605_v1.csv'},
  'clean': {'description': 'processed data',
   'must_include_processing_record': True,
   'must_include_date_and_version': True,
   'filename_example': 'customers_clean_20260606_v2.csv'},
  'feature': {'description': 'model input features',
   'must_record_split_rule': True,
   'must_check_leakage': True,
   'filename_example': 'customers_feature_20260607_v1.parquet'},
  'log': {'description': 'execution and upload records',
   'delete_allowed_by_student': False,
   'filename_examples': ['run_info_week2_day4_20260606_v1.json',
    'day4_s3_upload_record_20260606_v1.json']},
  'artifact': {'description': 'reports and submitted outputs',
   'final_artifact_delete_allowed': False,
   'filename_example': 'day4_s3_data_loading_rules_20260606_v1.md'}},
 'environment_connection': {'local_pc_wsl2': True,
  'openshift_local_same_rules': True,
  'developer_sandbox_same_rules': True,
  'g4dn_used_in_day4': False,
  'g4dn_future_rules': 'store GPU outputs under artifact/week7 and logs under log/week7'},
 'next_lesson': 'S3 Versioning concept and overwrite test'}

In [133]:
print("author:", loaded_rules["author"])
print("pattern:", loaded_rules["file_naming_pattern"])
print("raw prefix:", loaded_rules["prefixes"]["raw"])
print("clean prefix:", loaded_rules["prefixes"]["clean"])
print("next lesson:", loaded_rules["next_lesson"])

author: kim-juil
pattern: {dataset}_{stage}_{yyyymmdd}_v{version}.{ext}
raw prefix: users/kim-juil/raw/customers/
clean prefix: users/kim-juil/clean/customers/
next lesson: S3 Versioning concept and overwrite test

In [134]:
from pathlib import Path
import os
import textwrap

# 현재 실행 위치가 notebooks/이면 부모 폴더를 프로젝트 루트로 사용
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# reports/week2 폴더 준비
REPORT_DIR = BASE_DIR / "reports" / "week2"
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# 기존 셀에서 AUTHOR 또는 author 변수가 있으면 사용하고,
# 없으면 환경 변수 또는 기본값 사용
AUTHOR = globals().get(
    "AUTHOR",
    globals().get("author", os.environ.get("AUTHOR", "student"))
)

# 저장 파일 경로
record_file = REPORT_DIR / "day4_period4_file_naming_rules_record.md"

# Prefix 정의
raw_prefix = f"users/{AUTHOR}/raw/customers/"
clean_prefix = f"users/{AUTHOR}/clean/customers/"
feature_prefix = f"users/{AUTHOR}/feature/customers/"
log_prefix = f"users/{AUTHOR}/log/week2/"
artifact_prefix = f"users/{AUTHOR}/artifact/week2/"
notebook_prefix = f"users/{AUTHOR}/notebook/week2/"
archive_prefix = f"users/{AUTHOR}/archive/"

# Markdown 기록지 내용
record_text = f"""
# 2주차 Day 4 4교시 실습 기록지

## 작성자

- author: {AUTHOR}

## 1. 오늘 주제

파일명 규칙 + 데이터 적재 규칙 문서화

## 2. 나쁜 파일명 예시

- customers.csv
- customers_final.csv
- final.csv

## 3. 좋은 파일명 예시

- customers_raw_20260605_v1.csv
- customers_clean_20260606_v2.csv
- customers_feature_20260607_v1.parquet

## 4. 기본 파일명 규칙

- 형식: `{{dataset}}_{{stage}}_{{yyyymmdd}}_v{{version}}.{{ext}}`
- dataset 의미: 데이터셋 이름
- stage 의미: 데이터 상태 또는 산출물 유형
- yyyymmdd 의미: 생성일 또는 기준일
- version 의미: 데이터 또는 산출물 버전
- ext 의미: 파일 확장자

## 5. stage별 저장 위치

| stage | 의미 | 저장 Prefix |
|---|---|---|
| raw | 원본 데이터 | {raw_prefix} |
| clean | 전처리 완료 데이터 | {clean_prefix} |
| feature | 모델 학습용 특징 데이터 | {feature_prefix} |
| log | 실행 기록과 업로드 기록 | {log_prefix} |
| report/artifact | 리포트와 결과 산출물 | {artifact_prefix} |
| notebook | 실습 Notebook | {notebook_prefix} |
| archive | 장기 보관 데이터 | {archive_prefix} |

## 6. raw 데이터 규칙

- raw 데이터는 원본이므로 수정하지 않는다.
- raw 데이터는 같은 이름으로 덮어쓰지 않는다.
- 변경이 필요하면 새 파일명과 새 버전으로 업로드한다.

## 7. clean 데이터 규칙

- clean 데이터는 전처리 완료 데이터를 의미한다.
- raw 데이터와 같은 Prefix에 섞지 않는다.
- 파일명에 날짜와 버전을 포함한다.

## 8. feature 데이터 규칙

- feature 데이터는 모델 학습에 사용할 특징 데이터를 의미한다.
- 어떤 clean 데이터에서 만들어졌는지 기록한다.
- train/test split 기준과 데이터 누수 여부를 함께 확인한다.

## 9. log 데이터 규칙

- 실행 조건, 입력 파일, 출력 파일, seed, author를 기록한다.
- run_info.json, 업로드 기록 JSON, 업로드 기록 Markdown을 저장한다.
- 문제 발생 시 원인 추적에 사용할 수 있도록 임의 삭제하지 않는다.

## 10. artifact 데이터 규칙

- 리포트, 결과 산출물, 모델 파일 등을 저장한다.
- 최종 제출 산출물은 쉽게 삭제하지 않는다.
- log는 실행 조건 기록이고 artifact는 결과 산출물이라는 점을 구분한다.

## 11. 삭제 제한 대상

- raw/
- log/
- 최종 제출 artifact/
- 다른 개인의 users/ Prefix
- 출처 확인이 되지 않은 공통 데이터

## 12. OpenShift 연결

- OpenShift Local 또는 Developer Sandbox에서도 같은 파일명 규칙을 어떻게 사용할 것인가?

## 13. g4dn 연결

- g4dn GPU 실습 결과에는 어떤 파일명 규칙을 적용할 것인가?

## 14. 생성한 산출물

| 산출물 | 경로 |
|---|---|
| 파일명 규칙 문서 | outputs/day4_s3_file_naming_rules.md |
| 데이터 적재 규칙 문서 | outputs/day4_s3_data_loading_rules.md |
| 데이터 적재 규칙 JSON | outputs/day4_s3_data_loading_rules.json |

## 15. 오늘 이해한 점

-

## 16. 다음 교시에서 할 일

S3 Versioning 개념 + 덮어쓰기 실습
"""

# 불필요한 앞뒤 공백 정리 후 저장
record_text = textwrap.dedent(record_text).strip() + "\n"

record_file.write_text(record_text, encoding="utf-8")

print("실습 기록지 저장:", record_file)
print("존재 여부:", record_file.exists())
print("상대 경로:", record_file.relative_to(BASE_DIR))

실습 기록지 저장: /home/soldesk/week2-reproducibility/reports/week2/day4_period4_file_naming_rules_record.md
존재 여부: True
상대 경로: reports/week2/day4_period4_file_naming_rules_record.md

In [135]:
import json
from pathlib import Path
from datetime import datetime
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
AUTHOR = "student"
BUCKET = "edu-ai-lake"
version_ids_file = OUTPUT_DIR / "day4_s3_versioning_version_ids.json"
versions_raw_file = OUTPUT_DIR / "day4_s3_versioning_versions_raw.json"
version_ids = {}
if version_ids_file.exists():
    version_ids = json.loads(version_ids_file.read_text(encoding="utf-8"))
versions_raw = {}
if versions_raw_file.exists():
    versions_raw = json.loads(versions_raw_file.read_text(encoding="utf-8"))
versioning_record = {
    "day": "week2_day4",
    "lesson": "period5_s3_versioning_overwrite_test",
    "author": AUTHOR,
    "bucket": BUCKET,
    "created_at": datetime.now().isoformat(),
    "environment": {
        "local_pc_wsl2_used": True,
        "openshift_local_used": False,
        "developer_sandbox_used": False,
        "g4dn_used": False,
        "h200_used": False
    },
    "test_object": {
        "key": f"users/{AUTHOR}/clean/customers/versioning-test/customers_clean_versioning_test_same_key.csv",
        "reason": "clean 테스트 객체로 Versioning 실습을 수행함",
        "raw_overwrite_test": False
    },
    "local_test_files": {
        "v1": "tmp/versioning-test/customers_clean_versioning_test_v1.csv",
        "v2": "tmp/versioning-test/customers_clean_versioning_test_v2.csv"
    },
    "versioning_concept": {
        "purpose": "same key overwrite and previous version preservation",
        "versioning_is_safety_net": True,
        "versioning_replaces_file_naming_rule": False,
        "raw_overwrite_recommended": False,
        "recommended_operation": "new filename, new date, new version, and execution record"
    },
    "version_ids": version_ids,
    "version_count": len(versions_raw.get("Versions", [])),
    "delete_marker_count": len(versions_raw.get("DeleteMarkers", [])),
    "outputs": {
        "versions_raw_file": "outputs/day4_s3_versioning_versions_raw.json",
        "version_ids_file": "outputs/day4_s3_versioning_version_ids.json",
        "record_file": "outputs/day4_s3_versioning_record.json"
    },
    "next_lesson": "S3 Lifecycle concept and retention policy design"
}
versioning_record_file = OUTPUT_DIR / "day4_s3_versioning_record.json"
versioning_record_file.write_text(
    json.dumps(versioning_record, ensure_ascii=False, indent=2),
    encoding="utf-8"
)
print("S3 Versioning JSON 기록 저장:", versioning_record_file)
print("존재 여부:", versioning_record_file.exists())

S3 Versioning JSON 기록 저장: /home/soldesk/week2-reproducibility/outputs/day4_s3_versioning_record.json
존재 여부: True

In [136]:
versioning_md_file = OUTPUT_DIR / "day4_s3_versioning_record.md"
versioning_md_text = f"""# Day 4 5교시 S3 Versioning 실습 기록
## 1. 작성자
- author: {AUTHOR}
## 2. 버킷
- bucket: {BUCKET}
## 3. 오늘 주제
S3 Versioning 개념 + 덮어쓰기 실습
## 4. 핵심 개념
S3 Versioning은 같은 객체 Key에 여러 버전을 보존할 수 있게 해주는 기능이다.
Versioning은 덮어쓰기와 삭제 실수에 대비하는 안전망이다.
하지만 Versioning은 파일명 규칙을 대체하지 않는다.
raw 데이터 덮어쓰기도 권장하지 않는다.
## 5. 실습 대상
이번 실습은 raw 데이터가 아니라 clean 테스트 객체로 진행했다.
| 항목 | 값 |
|---|---|
| 실습 S3 Key | users/{AUTHOR}/clean/customers/versioning-test/customers_clean_versioning_test_same_key.csv |
| 첫 번째 로컬 파일 | tmp/versioning-test/customers_clean_versioning_test_v1.csv |
| 두 번째 로컬 파일 | tmp/versioning-test/customers_clean_versioning_test_v2.csv |
| raw 덮어쓰기 실습 여부 | 하지 않음 |
## 6. 실습 흐름
1. 버킷 Versioning 상태 확인
2. v1 테스트 파일 생성
3. v1을 같은 S3 Key에 업로드
4. v2 테스트 파일 생성
5. v2를 같은 S3 Key에 다시 업로드
6. list-object-versions로 VersionId 확인
7. 최신 버전 다운로드 확인
8. 이전 VersionId 지정 다운로드 확인
9. 복구 개념 이해
10. Delete Marker 개념 이해
## 7. 생성된 로컬 기록 파일
| 파일 | 설명 |
|---|---|
| outputs/day4_s3_versioning_versions_raw.json | S3 버전 목록 원본 |
| outputs/day4_s3_versioning_version_ids.json | 최신/이전 VersionId 요약 |
| outputs/day4_s3_versioning_record.json | Versioning 실습 기록 |
| outputs/day4_s3_versioning_record.md | 사람이 읽는 Versioning 기록 |
## 8. 운영 원칙
- Versioning은 안전망이다.
- 파일명 규칙을 대체하지 않는다.
- raw 데이터는 덮어쓰지 않는다.
- raw 데이터는 새 파일명과 새 버전으로 업로드한다.
- clean 데이터도 가능하면 새 날짜와 새 버전으로 관리한다.
- 복구가 필요하면 VersionId를 확인한다.
- Versioning은 저장 비용을 증가시킬 수 있으므로 Lifecycle과 함께 설계한다.
## 9. OpenShift 연결
OpenShift Local 또는 Developer Sandbox에서 S3 객체를 읽고 쓰더라도 같은 Versioning 원칙을 따라야 한다.
ConfigMap으로 S3_BUCKET과 Prefix를 주입하고,
Secret으로 인증 정보를 관리하며,
실행 로그는 log/ Prefix에 남기는 것이 좋다.
## 10. g4dn 연결
Day 4에서는 g4dn.xlarge를 사용하지 않는다.
GPU 실습 주차에서는 모델 파일, GPU 실행 결과, CUDA 테스트 로그가 같은 S3 Versioning 원칙의 적용 대상이 될 수 있다.
예:
- users/{AUTHOR}/artifact/week7/model_gpu_test_artifact_20260710_v1.pt
- users/{AUTHOR}/log/week7/g4dn_run_info_20260710_v1.json
## 11. 다음 교시 연결
6교시에서는 오래된 객체와 이전 버전을 어떻게 보관하고 비용을 줄일지 S3 Lifecycle 개념과 보관 정책을 설계한다.
"""
versioning_md_file.write_text(versioning_md_text, encoding="utf-8")
print("S3 Versioning Markdown 기록 저장:", versioning_md_file)
print("존재 여부:", versioning_md_file.exists())

S3 Versioning Markdown 기록 저장: /home/soldesk/week2-reproducibility/outputs/day4_s3_versioning_record.md
존재 여부: True

In [137]:
from pathlib import Path
import os
import json
import csv
from collections import Counter
import textwrap

# 현재 실행 위치가 notebooks/이면 부모 폴더를 프로젝트 루트로 사용
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# 폴더 준비
OUTPUT_DIR = BASE_DIR / "outputs"
REPORT_DIR = BASE_DIR / "reports" / "week2"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# 기존 셀에서 AUTHOR 또는 author 변수가 있으면 사용하고,
# 없으면 환경 변수 또는 기본값 사용
AUTHOR = globals().get(
    "AUTHOR",
    globals().get("author", os.environ.get("AUTHOR", "student"))
)

# 기존 셀에서 BUCKET 또는 bucket_name 변수가 있으면 사용하고,
# 없으면 환경 변수 또는 기본값 사용
BUCKET = globals().get(
    "BUCKET",
    globals().get("bucket_name", os.environ.get("S3_BUCKET", "edu-ai-lake"))
)

# Versioning 실습용 Prefix / Key
versioning_test_prefix = f"users/{AUTHOR}/clean/customers/versioning-test/"
versioning_test_key = f"{versioning_test_prefix}customers_clean_versioning_test_same_key.csv"

# 실습에서 사용했을 가능성이 높은 로컬 파일 경로
v1_local_file = "tmp/versioning-test/customers_clean_versioning_test_v1.csv"
v2_local_file = "tmp/versioning-test/customers_clean_versioning_test_v2.csv"
previous_download_file = "tmp/versioning-test/download_previous.csv"

# 산출물 경로
versions_raw_json_file = OUTPUT_DIR / "day4_s3_versioning_versions_raw.json"
version_ids_json_file = OUTPUT_DIR / "day4_s3_versioning_version_ids.json"
versioning_record_json_file = OUTPUT_DIR / "day4_s3_versioning_record.json"
versioning_record_md_file = OUTPUT_DIR / "day4_s3_versioning_record.md"

# 개인 실습 기록지 저장 경로
practice_record_file = REPORT_DIR / "day4_period5_s3_versioning_record.md"


def safe_read_json(path: Path) -> dict:
    """
    JSON 파일이 있으면 읽고, 없거나 형식이 다르면 빈 dict를 반환한다.
    """
    if not path.exists():
        return {}

    try:
        text = path.read_text(encoding="utf-8").strip()
        if not text:
            return {}
        return json.loads(text)
    except json.JSONDecodeError:
        return {}


def get_marker_summary(csv_file: str, marker_column: str = "versioning_test_marker") -> str:
    """
    CSV 파일에서 versioning_test_marker 컬럼 값의 개수를 요약한다.
    파일이 없거나 컬럼이 없으면 확인 필요 메시지를 반환한다.
    """
    path = BASE_DIR / csv_file

    if not path.exists():
        return "확인 필요"

    try:
        with open(path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)

            if marker_column not in (reader.fieldnames or []):
                return f"{marker_column} 컬럼 없음"

            values = [
                row.get(marker_column, "")
                for row in reader
            ]

        counter = Counter(values)

        if not counter:
            return "값 없음"

        return ", ".join(
            f"{value}: {count}개"
            for value, count in counter.items()
        )

    except Exception as e:
        return f"확인 실패: {e}"


# 기존 JSON 산출물이 있으면 최대한 읽어서 VersionId를 자동 채움
versions_raw_data = safe_read_json(versions_raw_json_file)
version_ids_data = safe_read_json(version_ids_json_file)
versioning_record_data = safe_read_json(versioning_record_json_file)

versions = versions_raw_data.get("Versions", [])
delete_markers = versions_raw_data.get("DeleteMarkers", [])

latest_version = {}
previous_version = {}

if versions:
    latest_version = next(
        (v for v in versions if v.get("IsLatest") is True),
        versions[0]
    )

    previous_candidates = [
        v for v in versions
        if v.get("VersionId") != latest_version.get("VersionId")
    ]

    if previous_candidates:
        previous_version = previous_candidates[0]

# VersionId 자동 추출
latest_version_id = (
    version_ids_data.get("latest_version_id")
    or version_ids_data.get("v2_version_id")
    or versioning_record_data.get("latest_version_id")
    or latest_version.get("VersionId")
    or ""
)

previous_version_id = (
    version_ids_data.get("previous_version_id")
    or version_ids_data.get("v1_version_id")
    or versioning_record_data.get("previous_version_id")
    or previous_version.get("VersionId")
    or ""
)

latest_is_latest = (
    latest_version.get("IsLatest")
    if latest_version
    else ""
)

previous_is_latest = (
    previous_version.get("IsLatest")
    if previous_version
    else ""
)

# 이전 버전 다운로드 marker 확인
previous_marker_summary = get_marker_summary(previous_download_file)

# Versioning 상태는 기존 기록에서 있으면 사용, 없으면 확인 필요
bucket_versioning_status = (
    versioning_record_data.get("bucket_versioning_status")
    or version_ids_data.get("bucket_versioning_status")
    or "확인 필요"
)

bucket_versioning_check_command = f"aws s3api get-bucket-versioning --bucket {BUCKET}"

# Markdown 기록지 내용
practice_record_text = f"""
# 2주차 Day 4 5교시 실습 기록지

## 작성자

- author: {AUTHOR}

## 1. 오늘 주제

S3 Versioning 개념 + 덮어쓰기 실습

## 2. Versioning 개념

- S3 Versioning이란?
- 같은 S3 Key에 객체를 다시 업로드해도 이전 객체를 바로 없애지 않고, 여러 버전으로 보관할 수 있게 하는 기능이다.

## 3. 버킷 Versioning 상태

| 항목 | 값 |
|---|---|
| 버킷 이름 | {BUCKET} |
| Versioning 상태 | {bucket_versioning_status} |
| 확인 명령 | `{bucket_versioning_check_command}` |

## 4. 실습 대상

| 항목 | 값 |
|---|---|
| 실습 대상 Prefix | {versioning_test_prefix} |
| 실습 대상 Key | {versioning_test_key} |
| raw 데이터 사용 여부 | 사용하지 않음 |
| clean 테스트 객체 사용 여부 | 사용 |

## 5. 업로드 파일

| 구분 | 로컬 파일 | S3 Key |
|---|---|---|
| v1 | {v1_local_file} | {versioning_test_key} |
| v2 | {v2_local_file} | {versioning_test_key} |

## 6. VersionId 기록

| 구분 | VersionId | IsLatest |
|---|---|---|
| 최신 버전 | {latest_version_id} | {latest_is_latest} |
| 이전 버전 | {previous_version_id} | {previous_is_latest} |

## 7. 이전 버전 다운로드 결과

| 항목 | 결과 |
|---|---|
| 다운로드 파일 | {previous_download_file} |
| marker 값 | {previous_marker_summary} |
| 이전 버전 확인 성공 여부 | 확인 필요 |

## 8. 복구 개념

- 이전 버전을 복구하려면 어떤 값이 필요한가?
- 복구하려면 보통 복구 대상 객체의 `Key`와 이전 버전의 `VersionId`가 필요하다.
- 특정 VersionId를 다운로드하거나, 이전 버전을 다시 같은 Key로 업로드해서 최신 버전으로 만들 수 있다.

## 9. Delete Marker 개념

- Versioning 상태에서 삭제하면 어떤 개념이 생길 수 있는가?
- Versioning이 켜진 버킷에서 객체를 일반 삭제하면 실제 이전 버전이 바로 지워지지 않고 Delete Marker가 최신 버전으로 생길 수 있다.
- Delete Marker는 파일 내용이 아니라 삭제된 것처럼 보이게 하는 표시용 버전이다.

## 10. 운영 원칙

- Versioning이 파일명 규칙을 대체할 수 있는가?
  - 대체할 수 없다. Versioning은 복구 보조 기능이고, 파일명 규칙은 사람이 데이터 상태를 이해하기 위한 운영 기준이다.
- Versioning이 raw 덮어쓰기를 허용하는 근거가 되는가?
  - 아니다. raw 데이터는 원본이므로 같은 Key로 덮어쓰지 않는 것이 원칙이다.
- 좋은 운영 원칙은 무엇인가?
  - raw, clean, feature, log, artifact를 Prefix로 분리한다.
  - 파일명에 데이터셋, 상태, 날짜, 버전을 포함한다.
  - Versioning은 실수 복구용 보조 장치로 사용한다.
  - 중요한 삭제 작업 전에는 VersionId와 Delete Marker를 확인한다.

## 11. OpenShift 연결

- OpenShift Local 또는 Developer Sandbox에서 Versioning 원칙이 필요한 이유는?
- OpenShift에서 실행되는 Pod도 같은 S3 Prefix에 접근할 수 있으므로, 잘못된 업로드나 덮어쓰기 실수를 줄이기 위해 Versioning과 파일명 규칙이 필요하다.

## 12. g4dn 연결

- g4dn GPU 실습 결과에 Versioning이 필요한 이유는?
- GPU 실습 결과는 모델 파일, 추론 결과, 로그처럼 다시 만들기 어렵거나 비용이 드는 산출물이 포함될 수 있으므로 Versioning과 명확한 파일명 규칙이 필요하다.

## 13. 생성한 산출물

| 산출물 | 경로 |
|---|---|
| 버전 목록 원본 JSON | outputs/day4_s3_versioning_versions_raw.json |
| VersionId 요약 JSON | outputs/day4_s3_versioning_version_ids.json |
| Versioning 기록 JSON | outputs/day4_s3_versioning_record.json |
| Versioning 기록 Markdown | outputs/day4_s3_versioning_record.md |

## 14. 오늘 이해한 점

-

## 15. 다음 교시에서 할 일

S3 Lifecycle 개념 + 보관 정책 설계
"""

# 불필요한 앞뒤 공백 정리 후 저장
practice_record_text = textwrap.dedent(practice_record_text).strip() + "\n"

practice_record_file.write_text(practice_record_text, encoding="utf-8")

print("실습 기록지 저장:", practice_record_file)
print("존재 여부:", practice_record_file.exists())
print("상대 경로:", practice_record_file.relative_to(BASE_DIR))

실습 기록지 저장: /home/soldesk/week2-reproducibility/reports/week2/day4_period5_s3_versioning_record.md
존재 여부: True
상대 경로: reports/week2/day4_period5_s3_versioning_record.md

In [138]:
from pathlib import Path
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
AUTHOR = "student"
BUCKET = "edu-ai-lake"
lifecycle_design_file = OUTPUT_DIR / "day4_s3_lifecycle_design.md"
lifecycle_design_text = f"""# Day 4 S3 Lifecycle 보관 정책 설계
## 1. 작성자
- author: {AUTHOR}
## 2. 버킷
- bucket: {BUCKET}
## 3. 주제
S3 Lifecycle 개념 + 보관 정책 설계
## 4. 핵심 개념
S3 Lifecycle은 객체를 일정 조건에 따라 다른 스토리지 클래스로 전환하거나,
일정 기간 후 만료 처리하는 규칙이다.
Lifecycle은 삭제 도구가 아니라 보관 정책이다.
Versioning은 복구 가능성을 높이고,
Lifecycle은 오래된 객체와 이전 버전의 보관 비용을 관리한다.
## 5. Transition
Transition은 객체를 다른 스토리지 클래스로 전환하는 것이다.
예:
- 오래된 log를 저비용 스토리지로 전환
- 오래된 artifact를 장기 보관 스토리지로 전환
- archive 데이터를 장기 보관 스토리지로 전환 검토
## 6. Expiration
Expiration은 일정 기간 후 객체를 만료 처리하는 것이다.
자동 삭제에 가까운 동작이므로 매우 조심해야 한다.
raw, 최종 artifact, 주요 log에는 자동 만료 정책을 신중하게 적용해야 한다.
## 7. Prefix별 보관 정책
| Prefix | 의미 | 보관 기준 | 전환 기준 | 만료 기준 | 주의 |
|---|---|---|---|---|---|
| users/{AUTHOR}/raw/customers/ | 원본 데이터 | 장기 보관 | 장기 보관 전환 검토 | 자동 만료 금지 | 삭제 전 승인 |
| users/{AUTHOR}/clean/customers/ | 전처리 완료 데이터 | 중기/장기 | 일정 기간 후 전환 검토 | 재생성 가능성 확인 후 검토 | Day 5 입력 |
| users/{AUTHOR}/feature/customers/ | 모델 학습용 데이터 | 단기/중기 | 모델 연결 종료 후 전환 검토 | 재생성 가능 시 검토 | 모델 버전 확인 |
| users/{AUTHOR}/notebook/week2/ | 실습 Notebook | 과정 기간 보관 | 과정 종료 후 전환 검토 | 교육 기준에 따름 | 실행 과정 근거 |
| users/{AUTHOR}/artifact/week2/ | 리포트/산출물 | 평가 기간 보관 | 평가 후 전환 검토 | 최종 산출물 자동 삭제 제한 | 평가 근거 |
| users/{AUTHOR}/log/week2/ | 실행 기록 | 추적 기간 보관 | 일정 기간 후 archive 검토 | 자동 삭제 신중 | 원인 분석 근거 |
| users/{AUTHOR}/archive/ | 장기 보관 | 장기 보관 | 장기 보관 스토리지 검토 | 승인 전 삭제 금지 | 휴지통 아님 |
| users/{AUTHOR}/tmp/ | 임시 파일 | 짧게 보관 | 보통 불필요 | 7~30일 만료 후보 | 실제 적용 후보 |
| users/{AUTHOR}/clean/customers/versioning-test/ | Versioning 실습 파일 | 짧게 보관 | 보통 불필요 | 14~30일 만료 후보 | 실습 객체 |
## 8. raw 보관 원칙
- raw는 원본이다.
- raw는 모든 clean, feature, model 실험의 재현 기준이다.
- raw는 자동 삭제하지 않는다.
- raw 삭제는 개인이 임의로 하지 않는다.
- raw 삭제 전에는 강사 또는 관리자 승인이 필요하다.
## 9. clean 보관 원칙
- clean은 분석과 모델링 입력 후보이다.
- Day 5에서 clean 데이터를 다시 읽어 baseline 준비로 연결한다.
- clean 삭제 전에는 raw, 전처리 코드, run_info가 남아 있는지 확인한다.
- 일정 기간 후 저비용 스토리지 전환을 검토할 수 있다.
## 10. feature 보관 원칙
- feature는 모델 학습용 데이터이다.
- 재생성 가능하면 단기/중기 보관 후 정리할 수 있다.
- 특정 모델 버전과 연결되어 있다면 삭제 전 모델 기록을 확인해야 한다.
- split 기준과 누수 점검 기록이 필요하다.
## 11. log 보관 원칙
- log는 실행 조건 추적용이다.
- run_info, upload record, versioning record, lifecycle design record를 보관한다.
- 결과가 달라졌을 때 원인 분석에 필요하다.
- 자동 삭제는 신중하게 검토한다.
## 12. artifact 보관 원칙
- artifact는 리포트, 제출물, 모델 파일 같은 결과 산출물이다.
- 최종 제출 산출물은 자동 삭제하지 않는다.
- 평가 기간 이후 전환을 검토할 수 있다.
## 13. tmp / versioning-test 정책
- tmp는 임시 파일이므로 짧은 기간 후 만료 후보이다.
- versioning-test는 실습용 객체이므로 장기 보관할 필요가 낮다.
- 실제 Lifecycle 적용 실습은 raw가 아니라 tmp 또는 versioning-test에만 진행한다.
## 14. Versioning과 Lifecycle 연결
- Versioning은 이전 버전을 보존한다.
- 이전 버전도 저장 공간을 사용한다.
- 오래된 이전 버전은 일정 기간 후 전환 또는 만료 검토가 필요하다.
- 단, raw와 최종 산출물의 이전 버전은 삭제 전 승인 기준이 필요하다.
## 15. OpenShift 연결
- OpenShift Local 또는 Developer Sandbox에서 생성한 파일도 같은 S3 Prefix와 Lifecycle 기준을 따른다.
- OpenShift Job이나 Workbench에서 생성한 log는 log/ Prefix에 저장한다.
- S3_BUCKET, S3_LOG_PREFIX, S3_ARTIFACT_PREFIX는 환경 변수 또는 ConfigMap으로 주입할 수 있다.
- AWS 인증 정보는 Secret 또는 더 안전한 인증 방식으로 관리한다.
## 16. g4dn 연결
- Day 4에서는 g4dn.xlarge를 사용하지 않는다.
- GPU 실습 주차에서 생성되는 모델 파일, CUDA 결과, GPU 실행 로그도 Lifecycle 대상이 될 수 있다.
- 모델 파일은 artifact/week7/ 또는 model/ 확장 Prefix에서 장기 보관을 검토한다.
- GPU 임시 결과는 tmp/ 또는 log/week7/ 기준으로 보관 기간을 정한다.
## 17. 다음 교시 연결
7교시에서는 이 보관 정책을 누가 적용하고,
누가 삭제할 수 있으며,
누가 raw를 보호해야 하는지 IAM 최소 권한과 개인 운영 규칙으로 연결한다.
"""
lifecycle_design_file.write_text(lifecycle_design_text, encoding="utf-8")
print("Lifecycle 설계 Markdown 저장:", lifecycle_design_file)
print("존재 여부:", lifecycle_design_file.exists())

Lifecycle 설계 Markdown 저장: /home/soldesk/week2-reproducibility/outputs/day4_s3_lifecycle_design.md
존재 여부: True

In [139]:
import json
from pathlib import Path
from datetime import datetime
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
AUTHOR = "student"
BUCKET = "edu-ai-lake"
lifecycle_design = {
    "day": "week2_day4",
    "lesson": "period6_s3_lifecycle_design",
    "author": AUTHOR,
    "bucket": BUCKET,
    "created_at": datetime.now().isoformat(),
    "environment": {
        "local_pc_wsl2_used": True,
        "openshift_local_used": False,
        "developer_sandbox_used": False,
        "g4dn_used": False,
        "h200_used": False
    },
    "concepts": {
        "lifecycle": "object transition or expiration rule",
        "transition": "move objects to another storage class after a period",
        "expiration": "expire objects after a period",
        "noncurrent_version": "previous version retained by S3 Versioning",
        "delete_marker": "marker that can be created when deleting in a versioned bucket"
    },
    "principles": {
        "lifecycle_is_retention_policy": True,
        "lifecycle_is_not_just_delete_tool": True,
        "raw_auto_expiration_recommended": False,
        "tmp_expiration_candidate": True,
        "versioning_and_lifecycle_should_be_designed_together": True
    },
    "prefix_policies": {
        "raw": {
            "prefix": f"users/{AUTHOR}/raw/customers/",
            "meaning": "original data",
            "retention": "long_term",
            "transition": "review_after_long_period",
            "expiration": "do_not_auto_expire",
            "delete_requires_approval": True,
            "reason": "raw is the reproducibility source"
        },
        "clean": {
            "prefix": f"users/{AUTHOR}/clean/customers/",
            "meaning": "processed data",
            "retention": "mid_to_long_term",
            "transition": "review_after_analysis_period",
            "expiration": "review_only_if_reproducible",
            "delete_requires_approval": True,
            "reason": "clean is used for analysis and Day 5 baseline preparation"
        },
        "feature": {
            "prefix": f"users/{AUTHOR}/feature/customers/",
            "meaning": "model input features",
            "retention": "short_to_mid_term",
            "transition": "review_after_model_link_check",
            "expiration": "possible_if_reproducible",
            "delete_requires_approval": True,
            "reason": "feature may be reproducible but can be linked to model versions"
        },
        "notebook": {
            "prefix": f"users/{AUTHOR}/notebook/week2/",
            "meaning": "notebook backup",
            "retention": "course_period",
            "transition": "review_after_course",
            "expiration": "depends_on_training_policy",
            "delete_requires_approval": False,
            "reason": "notebooks explain experiment process"
        },
        "artifact": {
            "prefix": f"users/{AUTHOR}/artifact/week2/",
            "meaning": "reports and submitted outputs",
            "retention": "evaluation_period",
            "transition": "review_after_evaluation",
            "expiration": "do_not_auto_expire_final_outputs",
            "delete_requires_approval": True,
            "reason": "artifacts can be evaluation evidence"
        },
        "log": {
            "prefix": f"users/{AUTHOR}/log/week2/",
            "meaning": "execution and upload records",
            "retention": "trace_period",
            "transition": "review_for_archive_after_trace_period",
            "expiration": "be_careful",
            "delete_requires_approval": True,
            "reason": "logs are needed for troubleshooting and traceability"
        },
        "archive": {
            "prefix": f"users/{AUTHOR}/archive/",
            "meaning": "long-term preserved data",
            "retention": "long_term",
            "transition": "long_term_storage_review",
            "expiration": "approval_required",
            "delete_requires_approval": True,
            "reason": "archive is not a trash folder"
        },
        "tmp": {
            "prefix": f"users/{AUTHOR}/tmp/",
            "meaning": "temporary files",
            "retention": "short_term",
            "transition": "not_required",
            "expiration": "7_to_30_days_candidate",
            "delete_requires_approval": False,
            "reason": "temporary files should not accumulate"
        },
        "versioning_test": {
            "prefix": f"users/{AUTHOR}/clean/customers/versioning-test/",
            "meaning": "versioning practice objects",
            "retention": "short_term",
            "transition": "not_required",
            "expiration": "14_to_30_days_candidate",
            "delete_requires_approval": False,
            "reason": "test objects are not production data"
        }
    },
    "safe_apply_scope": {
        "apply_to_raw": False,
        "apply_to_clean": False,
        "apply_to_artifact": False,
        "apply_to_log": False,
        "apply_to_tmp_only_if_instructor_allows": True,
        "safe_test_prefix": f"users/{AUTHOR}/tmp/lifecycle-test/"
    },
    "next_lesson": "IAM least privilege and personal operation rules"
}
lifecycle_design_json_file = OUTPUT_DIR / "day4_s3_lifecycle_design.json"
lifecycle_design_json_file.write_text(
    json.dumps(lifecycle_design, ensure_ascii=False, indent=2),
    encoding="utf-8"
)
print("Lifecycle 설계 JSON 저장:", lifecycle_design_json_file)
print("존재 여부:", lifecycle_design_json_file.exists())

Lifecycle 설계 JSON 저장: /home/soldesk/week2-reproducibility/outputs/day4_s3_lifecycle_design.json
존재 여부: True

In [140]:
loaded = json.loads(lifecycle_design_json_file.read_text(encoding="utf-8"))
print("author:", loaded["author"])
print("bucket:", loaded["bucket"])
print("raw expiration:", loaded["prefix_policies"]["raw"]["expiration"])
print("tmp expiration:", loaded["prefix_policies"]["tmp"]["expiration"])
print("next lesson:", loaded["next_lesson"])

author: student
bucket: edu-ai-lake
raw expiration: do_not_auto_expire
tmp expiration: 7_to_30_days_candidate
next lesson: IAM least privilege and personal operation rules

In [141]:
import json
from pathlib import Path
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
AUTHOR = "student"
tmp_lifecycle_policy = {
    "Rules": [
        {
            "ID": f"expire-{AUTHOR}-tmp-lifecycle-test-after-7-days",
            "Status": "Disabled",
            "Filter": {
                "Prefix": f"users/{AUTHOR}/tmp/lifecycle-test/"
            },
            "Expiration": {
                "Days": 7
            },
            "AbortIncompleteMultipartUpload": {
                "DaysAfterInitiation": 7
            }
        },
        {
            "ID": f"expire-{AUTHOR}-versioning-test-noncurrent-after-30-days",
            "Status": "Disabled",
            "Filter": {
                "Prefix": f"users/{AUTHOR}/clean/customers/versioning-test/"
            },
            "NoncurrentVersionExpiration": {
                "NoncurrentDays": 30
            }
        }
    ]
}
tmp_policy_file = OUTPUT_DIR / "day4_s3_lifecycle_tmp_policy_example.json"
tmp_policy_file.write_text(
    json.dumps(tmp_lifecycle_policy, ensure_ascii=False, indent=2),
    encoding="utf-8"
)
print("실습용 tmp Lifecycle 정책 예시 저장:", tmp_policy_file)
print("존재 여부:", tmp_policy_file.exists())

실습용 tmp Lifecycle 정책 예시 저장: /home/soldesk/week2-reproducibility/outputs/day4_s3_lifecycle_tmp_policy_example.json
존재 여부: True

In [142]:
from pathlib import Path
from datetime import datetime
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
AUTHOR = "student"
BUCKET = "edu-ai-lake"
lifecycle_record_file = OUTPUT_DIR / "day4_s3_lifecycle_record.md"
lifecycle_record_text = f"""# Day 4 6교시 S3 Lifecycle 실습 기록
## 1. 작성자
- author: {AUTHOR}
## 2. 버킷
- bucket: {BUCKET}
## 3. 오늘 주제
S3 Lifecycle 개념 + 보관 정책 설계
## 4. 오늘 이해한 핵심
Lifecycle은 오래된 객체를 저비용 스토리지로 전환하거나
일정 기간 후 만료 처리하는 S3 보관 정책이다.
Versioning은 복구 가능성을 높이고,
Lifecycle은 오래된 객체와 이전 버전의 보관 비용을 관리한다.
## 5. Transition
Transition은 객체를 다른 스토리지 클래스로 전환하는 것이다.
예:
- 오래된 log 전환
- 오래된 artifact 전환
- archive 데이터 장기 보관 전환
## 6. Expiration
Expiration은 일정 기간 후 객체를 만료 처리하는 것이다.
자동 삭제와 연결되므로 매우 조심해야 한다.
## 7. Prefix별 보관 설계 요약
| Prefix | 보관 기준 | 만료 기준 |
|---|---|---|
| raw | 장기 보관 | 자동 만료 금지 |
| clean | 중기/장기 보관 | 재생성 가능성 확인 후 검토 |
| feature | 단기/중기 보관 | 모델 연결 확인 후 검토 |
| notebook | 과정 기간 보관 | 교육 기준에 따름 |
| artifact | 평가 기간 보관 | 최종 산출물 자동 삭제 제한 |
| log | 추적 기간 보관 | 자동 삭제 신중 |
| archive | 장기 보관 | 승인 전 삭제 금지 |
| tmp | 짧게 보관 | 7~30일 만료 후보 |
| versioning-test | 짧게 보관 | 14~30일 만료 후보 |
## 8. raw 삭제 제한 이유
raw는 원본 재현 기준이다.
raw가 삭제되면 clean, feature, model 실험을 다시 재현하기 어려워진다.
따라서 raw는 자동 삭제 정책 대상에서 제외하거나, 삭제 전 승인을 요구해야 한다.
## 9. Versioning과 Lifecycle 연결
Versioning이 켜지면 이전 버전이 계속 쌓일 수 있다.
이전 버전도 저장 비용을 발생시킨다.
따라서 오래된 이전 버전 관리 정책이 필요하다.
단, raw와 최종 산출물의 이전 버전은 삭제 전 승인이 필요하다.
## 10. 생성한 산출물
| 산출물 | 경로 |
|---|---|
| Lifecycle 설계 Markdown | outputs/day4_s3_lifecycle_design.md |
| Lifecycle 설계 JSON | outputs/day4_s3_lifecycle_design.json |
| 실습용 tmp 정책 예시 JSON | outputs/day4_s3_lifecycle_tmp_policy_example.json |
| Lifecycle 기록 Markdown | outputs/day4_s3_lifecycle_record.md |
## 11. OpenShift 연결
OpenShift Local 또는 Developer Sandbox에서 생성한 log, artifact, feature도 같은 S3 Lifecycle 기준을 따른다.
## 12. g4dn 연결
GPU 실습 주차에서 생성한 모델 파일, GPU 결과, 실행 로그도 Lifecycle 정책 설계 대상이 된다.
## 13. 다음 교시 연결
7교시에서는 이 보관 정책을 누가 적용하고,
누가 삭제할 수 있으며,
누가 raw와 artifact를 보호해야 하는지 IAM 최소 권한과 개인 운영 규칙으로 연결한다.
"""
lifecycle_record_file.write_text(lifecycle_record_text, encoding="utf-8")
print("Lifecycle 기록 Markdown 저장:", lifecycle_record_file)
print("존재 여부:", lifecycle_record_file.exists())

Lifecycle 기록 Markdown 저장: /home/soldesk/week2-reproducibility/outputs/day4_s3_lifecycle_record.md
존재 여부: True

In [143]:
from pathlib import Path
import os
import textwrap

# 현재 실행 위치가 notebooks/이면 부모 폴더를 프로젝트 루트로 사용
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# reports/week2 폴더 준비
REPORT_DIR = BASE_DIR / "reports" / "week2"
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# 기존 셀에서 AUTHOR 또는 author 변수가 있으면 사용하고,
# 없으면 환경 변수 또는 기본값 사용
AUTHOR = globals().get(
    "AUTHOR",
    globals().get("author", os.environ.get("AUTHOR", "student"))
)

# Prefix 정의
raw_prefix = f"users/{AUTHOR}/raw/customers/"
clean_prefix = f"users/{AUTHOR}/clean/customers/"
feature_prefix = f"users/{AUTHOR}/feature/customers/"
log_prefix = f"users/{AUTHOR}/log/week2/"
artifact_prefix = f"users/{AUTHOR}/artifact/week2/"
tmp_prefix = f"users/{AUTHOR}/tmp/"
versioning_test_prefix = f"users/{AUTHOR}/clean/customers/versioning-test/"

# 저장 파일 경로
practice_record_file = REPORT_DIR / "day4_period6_s3_lifecycle_record.md"

# Markdown 실습 기록지 내용
practice_record_text = f"""
# 2주차 Day 4 6교시 실습 기록지

## 작성자

- author: {AUTHOR}

## 1. 오늘 주제

S3 Lifecycle 개념 + 보관 정책 설계

## 2. Lifecycle 개념

- Lifecycle이란?
- S3 객체의 보관 기간, 스토리지 클래스 전환, 만료, 이전 버전 정리, 미완료 멀티파트 업로드 정리 등을 자동화하는 수명 주기 관리 기능이다.

## 3. Transition

- 의미:
  - 객체를 일정 기간이 지난 뒤 더 저렴한 스토리지 클래스로 이동하는 작업이다.
- 적용 후보 Prefix:
  - {clean_prefix}
  - {feature_prefix}
  - {log_prefix}
  - {artifact_prefix}
- 주의할 점:
  - 자주 조회하는 데이터는 너무 빨리 전환하지 않는다.
  - raw 데이터는 원본성이 중요하므로 전환 전 보관 기준을 명확히 정한다.
  - 복원이 필요한 스토리지 클래스로 전환하면 조회 지연이나 복원 비용이 발생할 수 있다.

## 4. Expiration

- 의미:
  - 객체를 일정 기간이 지난 뒤 만료 처리하거나 삭제 대상으로 만드는 작업이다.
- 적용 후보 Prefix:
  - {tmp_prefix}
  - {versioning_test_prefix}
- 주의할 점:
  - raw, log, 최종 artifact에는 위험한 자동 삭제를 바로 적용하지 않는다.
  - 실습용 tmp Prefix처럼 재생성 가능하고 중요도가 낮은 데이터에 먼저 적용한다.
  - 정책 적용 전 Prefix 범위를 반드시 확인한다.

## 5. Versioning과 Lifecycle 관계

- Versioning이 왜 비용과 연결되는가?
  - 같은 Key에 여러 번 업로드하면 이전 버전이 계속 남을 수 있고, 남아 있는 모든 버전이 저장 비용에 포함될 수 있기 때문이다.
- Noncurrent version은 무엇인가?
  - 현재 최신 버전이 아닌 이전 객체 버전을 의미한다.
- 오래된 이전 버전은 어떻게 관리해야 하는가?
  - 중요 데이터는 충분한 보관 기간을 둔다.
  - 실습용 또는 테스트용 이전 버전은 일정 기간 후 정리하는 Lifecycle 규칙을 검토한다.
  - 삭제 전 VersionId, Prefix, 보관 필요 여부를 확인한다.

## 6. raw 보관 정책

| 항목 | 내용 |
|---|---|
| Prefix | {raw_prefix} |
| 보관 기준 | 원본 데이터이므로 장기 보관 |
| 자동 삭제 여부 | 기본적으로 자동 삭제하지 않음 |
| 삭제 전 승인 필요 여부 | 필요 |
| 이유 | raw 데이터는 원본이므로 재현성과 감사 추적의 기준이 된다. |

## 7. clean 보관 정책

| 항목 | 내용 |
|---|---|
| Prefix | {clean_prefix} |
| 보관 기준 | 전처리 기준과 버전이 명확한 데이터는 보관 |
| 전환 기준 | 장기간 조회하지 않는 clean 데이터는 저비용 스토리지 전환 검토 |
| 만료 기준 | 운영 기준 없이 자동 만료 금지 |
| 이유 | clean 데이터는 모델 학습과 분석의 기준 데이터로 다시 사용될 수 있다. |

## 8. feature 보관 정책

| 항목 | 내용 |
|---|---|
| Prefix | {feature_prefix} |
| 보관 기준 | 모델 학습에 사용한 feature 데이터는 모델 버전과 함께 보관 |
| 재생성 가능 여부 | clean 데이터와 feature 생성 코드가 있으면 재생성 가능 |
| 모델 연결 확인 여부 | 필요 |
| 이유 | 모델 성능 재현과 데이터 누수 검증에 필요하다. |

## 9. log 보관 정책

| 항목 | 내용 |
|---|---|
| Prefix | {log_prefix} |
| 보관 기준 | 실행 조건, 입력 파일, 출력 파일, seed, author 추적용으로 보관 |
| 전환 기준 | 오래된 로그는 저비용 스토리지 전환 검토 |
| 자동 삭제 주의 여부 | 매우 주의 필요 |
| 이유 | 장애 분석, 실험 재현, 업로드 추적에 필요하다. |

## 10. artifact 보관 정책

| 항목 | 내용 |
|---|---|
| Prefix | {artifact_prefix} |
| 보관 기준 | 리포트, 제출물, 모델 파일, 결과 산출물 보관 |
| 최종 산출물 삭제 제한 여부 | 제한 필요 |
| 이유 | 교육 제출물과 실험 결과의 증빙 자료이기 때문이다. |

## 11. tmp / versioning-test 정책

| Prefix | 보관 기준 | 만료 후보 기간 |
|---|---|---|
| {tmp_prefix} | 실습용 임시 파일만 저장 | 7일 |
| {versioning_test_prefix} | Versioning 실습용 테스트 객체만 저장 | 이전 버전 30일 |

## 12. 생성한 산출물

| 산출물 | 경로 |
|---|---|
| Lifecycle 설계 Markdown | outputs/day4_s3_lifecycle_design.md |
| Lifecycle 설계 JSON | outputs/day4_s3_lifecycle_design.json |
| 실습용 tmp 정책 예시 JSON | outputs/day4_s3_lifecycle_tmp_policy_example.json |
| Lifecycle 기록 Markdown | outputs/day4_s3_lifecycle_record.md |

## 13. OpenShift 연결

- OpenShift Local 또는 Developer Sandbox에서 Lifecycle 기준이 필요한 이유는?
- OpenShift에서 실행되는 Pod가 S3에 로그, 결과 파일, 중간 산출물을 계속 저장할 수 있기 때문이다.
- Prefix별 보관 정책이 없으면 임시 파일과 중요한 산출물이 섞여 관리가 어려워진다.
- tmp, log, artifact의 보관 기준을 분리하면 운영 실수와 비용 증가를 줄일 수 있다.

## 14. g4dn 연결

- g4dn GPU 실습 결과에 Lifecycle이 필요한 이유는?
- GPU 실습 결과는 모델 파일, 추론 결과, 로그, 성능 측정 결과처럼 용량이 커질 수 있는 산출물을 만들 수 있다.
- 비용이 큰 산출물은 보관 기준, 전환 기준, 삭제 승인 기준을 미리 정해야 한다.
- 최종 모델과 제출 산출물은 artifact로 보관하고, 임시 테스트 결과는 tmp 또는 log 기준으로 관리한다.

## 15. 오늘 이해한 점

-

## 16. 다음 교시에서 할 일

IAM 최소 권한 + 개인 운영 규칙
"""

# 불필요한 앞뒤 공백 정리 후 저장
practice_record_text = textwrap.dedent(practice_record_text).strip() + "\n"

practice_record_file.write_text(practice_record_text, encoding="utf-8")

print("실습 기록지 저장:", practice_record_file)
print("존재 여부:", practice_record_file.exists())
print("상대 경로:", practice_record_file.relative_to(BASE_DIR))

실습 기록지 저장: /home/soldesk/week2-reproducibility/reports/week2/day4_period6_s3_lifecycle_record.md
존재 여부: True
상대 경로: reports/week2/day4_period6_s3_lifecycle_record.md

In [144]:
from pathlib import Path
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
AUTHOR = "student"
BUCKET = "edu-ai-lake"
AWS_REGION = "ap-northeast-2"
iam_rules_file = OUTPUT_DIR / "day4_s3_iam_operation_rules.md"
iam_rules_text = f"""# Day 4 S3 IAM 최소 권한 + 개인 운영 규칙
## 1. 작성자
- author: {AUTHOR}
## 2. 실습 리전
- region: {AWS_REGION}
## 3. 사용 버킷
- bucket: {BUCKET}
## 4. 개인 Prefix
- user_prefix: users/{AUTHOR}/
## 5. IAM 최소 권한 원칙
필요한 사람에게,
필요한 Prefix에 대해서,
필요한 Action만 허용한다.
모든 학생에게 S3 FullAccess 또는 AdministratorAccess를 주지 않는다.
## 6. 개인 Prefix 구조
| Prefix | 역할 |
|---|---|
| users/{AUTHOR}/raw/customers/ | 원본 고객 데이터 |
| users/{AUTHOR}/clean/customers/ | 전처리 완료 고객 데이터 |
| users/{AUTHOR}/feature/customers/ | 모델 학습용 feature 데이터 |
| users/{AUTHOR}/notebook/week2/ | Week 2 Notebook |
| users/{AUTHOR}/artifact/week2/ | Week 2 리포트와 산출물 |
| users/{AUTHOR}/log/week2/ | Week 2 실행 기록과 업로드 기록 |
| users/{AUTHOR}/archive/ | 장기 보관 데이터 |
| users/{AUTHOR}/tmp/ | 임시 파일 |
## 7. 학생 개인 권한 원칙
- 본인 Prefix 중심으로 작업한다.
- 다른 개인 Prefix에 쓰기 권한을 갖지 않는다.
- raw 데이터는 읽을 수 있지만 삭제하지 않는다.
- clean 데이터는 본인 Prefix에 업로드할 수 있다.
- feature 데이터는 본인 Prefix에 업로드할 수 있다.
- log는 쓰고 읽을 수 있지만 삭제하지 않는다.
- artifact는 업로드할 수 있지만 최종 산출물은 삭제하지 않는다.
- tmp는 본인 Prefix 안에서 정리할 수 있다.
- Versioning 설정을 바꾸지 않는다.
- Lifecycle 설정을 바꾸지 않는다.
- 버킷 정책을 바꾸지 않는다.
## 8. 강사 또는 관리자 권한 원칙
- 교육용 버킷 구조를 관리한다.
- Versioning 상태를 확인하고 필요 시 설정한다.
- Lifecycle 정책을 검토하고 필요 시 적용한다.
- 학생 산출물을 조회한다.
- raw 삭제 또는 복구는 승인 절차에 따라 수행한다.
- 사고 발생 시 CloudTrail과 S3 log를 확인한다.
## 9. 파이프라인 권한 원칙
- 정해진 입력 Prefix를 읽는다.
- 정해진 출력 Prefix에 결과를 쓴다.
- 실행 로그를 log Prefix에 남긴다.
- raw 데이터를 삭제하지 않는다.
- Lifecycle이나 Versioning 설정을 변경하지 않는다.
## 10. 감사자 권한 원칙
- log와 감사 기록을 조회한다.
- 데이터를 업로드하지 않는다.
- 데이터를 삭제하지 않는다.
- 권한 변경을 수행하지 않는다.
## 11. Prefix별 권한 설계
| Prefix | Get | Put | Delete | 비고 |
|---|---|---|---|---|
| raw/customers | 허용 | 제한 | 금지 | 원본 보호 |
| clean/customers | 허용 | 허용 | 제한 | 전처리 결과 |
| feature/customers | 허용 | 허용 | 제한 | 모델 입력 |
| notebook/week2 | 허용 | 허용 | 제한 | 실습 기록 |
| artifact/week2 | 허용 | 허용 | 제한 | 평가 산출물 |
| log/week2 | 허용 | 허용 | 금지 | 실행 추적 |
| archive | 허용 | 제한 | 승인 필요 | 장기 보관 |
| tmp | 허용 | 허용 | 허용 | 임시 파일 |
## 12. 명시적으로 제한해야 할 작업
- raw DeleteObject
- raw DeleteObjectVersion
- log DeleteObject
- artifact 최종 산출물 DeleteObject
- PutBucketVersioning
- PutLifecycleConfiguration
- PutBucketPolicy
- DeleteBucket
- 다른 개인 Prefix PutObject
- 다른 개인 Prefix DeleteObject
## 13. OpenShift 연결
OpenShift Local 또는 Developer Sandbox에서는 S3_BUCKET, S3_USER_PREFIX, S3_CLEAN_PREFIX, S3_LOG_PREFIX를 환경 변수 또는 ConfigMap으로 주입한다.
AWS 인증 정보는 Secret 또는 더 안전한 인증 방식으로 관리한다.
OpenShift에서 실행되는 Notebook, Job, FastAPI도 최소 권한 원칙을 따른다.
## 14. g4dn 연결
Day 4에서는 g4dn.xlarge를 사용하지 않는다.
GPU 실습 주차에서는 g4dn 인스턴스에 필요한 S3 Prefix 권한만 부여한다.
가능하면 Access Key 파일 저장보다 EC2 IAM Role을 사용한다.
g4dn 결과는 artifact/week7/과 log/week7/에 저장한다.
## 15. 사고 예방 규칙
- raw 삭제는 관리자 승인 없이는 수행하지 않는다.
- log 삭제는 수행하지 않는다.
- artifact 최종 산출물 삭제는 승인 후 수행한다.
- Lifecycle 정책은 학생 개인이 임의 변경하지 않는다.
- Versioning 설정은 학생 개인이 임의 변경하지 않는다.
- Access Key와 Secret Key는 코드, README, Notebook, Git 저장소에 남기지 않는다.
- 업로드 후 S3 URI와 author를 기록한다.
- 본인 Prefix가 맞는지 업로드 전에 확인한다.
## 16. 다음 교시 연결
8교시에서는 Day 4 전체 산출물을 정리하고,
Day 5에서 S3 clean 데이터를 읽어 baseline 준비로 연결한다.
"""
iam_rules_file.write_text(iam_rules_text, encoding="utf-8")
print("IAM 운영 규칙 Markdown 저장:", iam_rules_file)
print("존재 여부:", iam_rules_file.exists())

IAM 운영 규칙 Markdown 저장: /home/soldesk/week2-reproducibility/outputs/day4_s3_iam_operation_rules.md
존재 여부: True

In [145]:
import json
from pathlib import Path
from datetime import datetime
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
AUTHOR = "student"
BUCKET = "edu-ai-lake"
AWS_REGION = "ap-northeast-2"
iam_rules = {
    "day": "week2_day4",
    "lesson": "period7_iam_least_privilege_and_personal_operation_rules",
    "author": AUTHOR,
    "bucket": BUCKET,
    "region": AWS_REGION,
    "created_at": datetime.now().isoformat(),
    "environment": {
        "local_pc_wsl2_used": True,
        "openshift_local_used": False,
        "developer_sandbox_used": False,
        "g4dn_used": False,
        "h200_used": False
    },
    "least_privilege_principle": {
        "summary": "grant only required actions on required prefixes",
        "do_not_grant_s3_full_access_to_students": True,
        "do_not_grant_admin_access_to_students": True
    },
    "user_prefix": f"users/{AUTHOR}/",
    "prefixes": {
        "raw": f"users/{AUTHOR}/raw/customers/",
        "clean": f"users/{AUTHOR}/clean/customers/",
        "feature": f"users/{AUTHOR}/feature/customers/",
        "notebook": f"users/{AUTHOR}/notebook/week2/",
        "artifact": f"users/{AUTHOR}/artifact/week2/",
        "log": f"users/{AUTHOR}/log/week2/",
        "archive": f"users/{AUTHOR}/archive/",
        "tmp": f"users/{AUTHOR}/tmp/"
    },
    "role_design": {
        "student_personal": {
            "name_example": "ai-student-personal-s3-user",
            "allowed": [
                "List own prefix",
                "GetObject on own prefixes",
                "PutObject on own clean, feature, notebook, artifact, log prefixes",
                "DeleteObject only on own tmp prefix"
            ],
            "denied_or_not_allowed": [
                "Delete raw",
                "Delete log",
                "Delete final artifact",
                "Write other user prefix",
                "PutBucketVersioning",
                "PutLifecycleConfiguration",
                "PutBucketPolicy",
                "DeleteBucket"
            ]
        },
        "instructor_admin": {
            "name_example": "ai-instructor-s3-admin",
            "allowed": [
                "Review student artifacts",
                "Manage educational bucket structure",
                "Review Versioning and Lifecycle settings",
                "Approve recovery or deletion if needed"
            ],
            "caution": [
                "Use approval and audit for destructive actions"
            ]
        },
        "pipeline": {
            "name_example": "ai-pipeline-role",
            "allowed": [
                "Read required input prefixes",
                "Write feature, artifact, and log prefixes",
                "Write execution logs"
            ],
            "denied_or_not_allowed": [
                "Delete raw",
                "Change bucket lifecycle",
                "Change bucket versioning"
            ]
        },
        "auditor": {
            "name_example": "ai-auditor-readonly",
            "allowed": [
                "Read logs",
                "Review CloudTrail events",
                "List relevant prefixes"
            ],
            "denied_or_not_allowed": [
                "PutObject",
                "DeleteObject",
                "Change IAM or S3 bucket settings"
            ]
        }
    },
    "prefix_permission_matrix": {
        "raw": {
            "get": True,
            "put": "limited",
            "delete": False,
            "reason": "raw is original reproducibility source"
        },
        "clean": {
            "get": True,
            "put": True,
            "delete": "restricted",
            "reason": "clean is processed data and Day 5 input"
        },
        "feature": {
            "get": True,
            "put": True,
            "delete": "restricted",
            "reason": "feature may be linked to model versions"
        },
        "log": {
            "get": True,
            "put": True,
            "delete": False,
            "reason": "logs are traceability records"
        },
        "artifact": {
            "get": True,
            "put": True,
            "delete": "restricted",
            "reason": "artifacts can be evaluation evidence"
        },
        "tmp": {
            "get": True,
            "put": True,
            "delete": True,
            "reason": "temporary personal files"
        }
    },
    "dangerous_actions_for_students": [
        "s3:DeleteObject on raw/log/final artifact",
        "s3:DeleteObjectVersion",
        "s3:PutBucketVersioning",
        "s3:PutLifecycleConfiguration",
        "s3:PutBucketPolicy",
        "s3:DeleteBucket",
        "s3:PutObject to another user's prefix"
    ],
    "accident_prevention": {
        "raw_delete": "deny or restrict raw DeleteObject",
        "wrong_prefix_upload": "limit PutObject to users/<author>/ only",
        "log_delete": "deny or restrict log DeleteObject",
        "artifact_delete": "restrict final artifact deletion",
        "lifecycle_misconfiguration": "students should not have PutLifecycleConfiguration",
        "access_key_leak": "do not store credentials in code, README, notebook, or Git"
    },
    "openshift_connection": {
        "use_configmap_for": [
            "S3_BUCKET",
            "S3_USER_PREFIX",
            "S3_CLEAN_PREFIX",
            "S3_LOG_PREFIX"
        ],
        "use_secret_for": [
            "AWS credentials if needed"
        ],
        "principle": "OpenShift workloads should have only required S3 prefix permissions"
    },
    "g4dn_connection": {
        "used_in_day4": False,
        "recommended_auth": "EC2 IAM Role instead of storing access keys",
        "needed_permissions_future": [
            "GetObject on clean data",
            "PutObject on artifact/week7",
            "PutObject on log/week7"
        ],
        "not_needed": [
            "raw DeleteObject",
            "PutBucketVersioning",
            "PutLifecycleConfiguration"
        ]
    },
    "next_lesson": "Day 4 final artifact summary and Day 5 preview"
}
iam_rules_json_file = OUTPUT_DIR / "day4_s3_iam_operation_rules.json"
iam_rules_json_file.write_text(
    json.dumps(iam_rules, ensure_ascii=False, indent=2),
    encoding="utf-8"
)
print("IAM 운영 규칙 JSON 저장:", iam_rules_json_file)
print("존재 여부:", iam_rules_json_file.exists())

IAM 운영 규칙 JSON 저장: /home/soldesk/week2-reproducibility/outputs/day4_s3_iam_operation_rules.json
존재 여부: True

In [146]:
loaded = json.loads(iam_rules_json_file.read_text(encoding="utf-8"))
print("author:", loaded["author"])
print("bucket:", loaded["bucket"])
print("user_prefix:", loaded["user_prefix"])
print("raw delete allowed:", loaded["prefix_permission_matrix"]["raw"]["delete"])
print("next lesson:", loaded["next_lesson"])

author: student
bucket: edu-ai-lake
user_prefix: users/student/
raw delete allowed: False
next lesson: Day 4 final artifact summary and Day 5 preview

In [147]:
from pathlib import Path
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
AUTHOR = "student"
BUCKET = "edu-ai-lake"
permission_matrix_file = OUTPUT_DIR / "day4_s3_personal_permission_matrix.md"
permission_matrix_text = f"""# Day 4 개인 S3 권한 매트릭스
## 1. 작성자
- author: {AUTHOR}
## 2. 버킷
- bucket: {BUCKET}
## 3. 개인 Prefix
- users/{AUTHOR}/
## 4. Prefix별 권한 매트릭스
| Prefix | List | Get | Put | Delete | 비고 |
|---|---|---|---|---|---|
| users/{AUTHOR}/raw/customers/ | 허용 | 허용 | 제한 | 금지 | 원본 보호 |
| users/{AUTHOR}/clean/customers/ | 허용 | 허용 | 허용 | 제한 | Day 5 입력 |
| users/{AUTHOR}/feature/customers/ | 허용 | 허용 | 허용 | 제한 | 모델 연결 확인 |
| users/{AUTHOR}/notebook/week2/ | 허용 | 허용 | 허용 | 제한 | 실습 기록 |
| users/{AUTHOR}/artifact/week2/ | 허용 | 허용 | 허용 | 제한 | 평가 산출물 |
| users/{AUTHOR}/log/week2/ | 허용 | 허용 | 허용 | 금지 | 실행 추적 |
| users/{AUTHOR}/archive/ | 허용 | 허용 | 제한 | 승인 필요 | 장기 보관 |
| users/{AUTHOR}/tmp/ | 허용 | 허용 | 허용 | 허용 | 임시 파일 |
## 5. 학생 개인에게 허용하지 않는 작업
- raw DeleteObject
- log DeleteObject
- artifact 최종 산출물 DeleteObject
- DeleteObjectVersion
- PutBucketVersioning
- PutLifecycleConfiguration
- PutBucketPolicy
- DeleteBucket
- 다른 개인 Prefix PutObject
- 다른 개인 Prefix DeleteObject
## 6. 권한 설계 이유
raw는 원본 재현 기준이므로 삭제를 제한한다.
log는 실행 추적 근거이므로 삭제를 제한한다.
artifact는 평가와 제출 근거가 될 수 있으므로 삭제를 제한한다.
tmp는 임시 파일이므로 본인 Prefix 안에서는 삭제를 허용할 수 있다.
## 7. Day 5 연결
Day 5에서는 S3 clean 데이터를 다시 읽어 baseline 준비로 연결한다.
따라서 clean Prefix에 대한 GetObject 권한이 필요하다.
"""
permission_matrix_file.write_text(permission_matrix_text, encoding="utf-8")
print("개인 권한 매트릭스 저장:", permission_matrix_file)
print("존재 여부:", permission_matrix_file.exists())

개인 권한 매트릭스 저장: /home/soldesk/week2-reproducibility/outputs/day4_s3_personal_permission_matrix.md
존재 여부: True

In [148]:
from pathlib import Path
import os
import textwrap

# 현재 실행 위치가 notebooks/이면 부모 폴더를 프로젝트 루트로 사용
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# reports/week2 폴더 준비
REPORT_DIR = BASE_DIR / "reports" / "week2"
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# 기존 셀에서 AUTHOR 또는 author 변수가 있으면 사용하고,
# 없으면 환경 변수 또는 기본값 사용
AUTHOR = globals().get(
    "AUTHOR",
    globals().get("author", os.environ.get("AUTHOR", "student"))
)

# 기존 셀에서 BUCKET 또는 bucket_name 변수가 있으면 사용하고,
# 없으면 환경 변수 또는 기본값 사용
BUCKET = globals().get(
    "BUCKET",
    globals().get("bucket_name", os.environ.get("S3_BUCKET", "edu-ai-lake"))
)

# Prefix 정의
user_prefix = f"users/{AUTHOR}/"
raw_prefix = f"{user_prefix}raw/"
clean_prefix = f"{user_prefix}clean/"
feature_prefix = f"{user_prefix}feature/"
log_prefix = f"{user_prefix}log/"
artifact_prefix = f"{user_prefix}artifact/"
tmp_prefix = f"{user_prefix}tmp/"

# 저장 파일 경로
practice_record_file = REPORT_DIR / "day4_period7_iam_operation_rules_record.md"

# Markdown 실습 기록지 내용
practice_record_text = f"""
# 2주차 Day 4 7교시 실습 기록지

## 작성자

- author: {AUTHOR}

## 1. 오늘 주제

IAM 최소 권한 + 개인 운영 규칙

## 2. IAM 최소 권한 정의

- 최소 권한이란?
- 사용자, 역할, 애플리케이션이 작업에 필요한 권한만 가지도록 제한하는 보안 원칙이다.
- 필요 이상으로 넓은 권한을 주지 않고, 필요한 Prefix와 필요한 작업만 허용한다.

## 3. 개인 Prefix

| 항목 | 값 |
|---|---|
| bucket | {BUCKET} |
| author | {AUTHOR} |
| user_prefix | {user_prefix} |

## 4. 학생 개인 권한

| Prefix | 허용할 작업 | 제한할 작업 |
|---|---|---|
| raw | 조회, 업로드 | 삭제, 덮어쓰기, 버전 삭제 |
| clean | 조회, 업로드 | 무분별한 삭제, 다른 사람 Prefix 접근 |
| feature | 조회, 업로드 | 무분별한 삭제, 다른 사람 Prefix 접근 |
| log | 조회, 업로드 | 삭제 |
| artifact | 조회, 업로드 | 최종 산출물 삭제 |
| tmp | 조회, 업로드, 실습용 삭제 | 다른 Prefix 삭제, Lifecycle 전체 설정 변경 |

## 5. raw 삭제 제한 이유

- raw 데이터는 원본 데이터이다.
- raw 데이터가 삭제되면 전처리 결과와 모델 학습 결과를 재현하기 어렵다.
- raw 데이터는 감사, 추적, 재실행의 기준이 된다.
- 따라서 학생 개인이 임의로 삭제하지 못하도록 제한하는 것이 안전하다.

## 6. log 삭제 제한 이유

- log는 실행 조건, 입력 파일, 출력 파일, seed, author, 업로드 기록을 추적하는 자료이다.
- log가 삭제되면 문제가 발생했을 때 원인을 추적하기 어렵다.
- 실험 결과가 달라졌을 때 비교 기준이 사라진다.
- 따라서 log는 쉽게 삭제하지 않는 것이 좋다.

## 7. artifact 삭제 제한 이유

- artifact는 리포트, 제출 산출물, 모델 파일, 결과 문서 등을 의미한다.
- 최종 제출물이나 모델 산출물이 삭제되면 교육 평가나 운영 확인에 문제가 생길 수 있다.
- 중요한 artifact는 삭제 전 승인 절차가 필요하다.

## 8. Versioning / Lifecycle 설정 권한

| 권한 | 학생 개인에게 허용 여부 | 이유 |
|---|---|---|
| PutBucketVersioning | 허용하지 않음 | 버킷 전체 Versioning 설정을 바꾸는 권한이므로 관리자 권한에 가깝다. |
| PutLifecycleConfiguration | 허용하지 않음 | Lifecycle 오설정 시 중요한 데이터가 자동 삭제될 수 있다. |
| PutBucketPolicy | 허용하지 않음 | 버킷 전체 접근 정책을 바꾸는 매우 민감한 권한이다. |
| DeleteObjectVersion | 기본적으로 허용하지 않음 | 특정 VersionId를 삭제하면 복구가 어려울 수 있다. |

## 9. 역할별 권한 설계

| 역할 | 주요 권한 | 제한 권한 |
|---|---|---|
| 학생 개인 | 본인 users/{AUTHOR}/ Prefix 안에서 조회, 업로드, 실습용 tmp 삭제 | 버킷 정책 변경, Versioning 변경, Lifecycle 변경, 다른 사용자 Prefix 접근 |
| 강사/관리자 | 전체 실습 Prefix 조회, 정책 관리, 문제 복구 | 불필요한 운영 데이터 직접 삭제는 제한 |
| 파이프라인 | 지정된 Prefix에 자동 업로드, 로그 저장, 산출물 저장 | 버킷 전체 정책 변경, 다른 Prefix 삭제 |
| 감사자 | 로그와 산출물 조회 | 업로드, 삭제, 정책 변경 |

## 10. OpenShift 연결

- OpenShift Local 또는 Developer Sandbox에서 S3 권한을 어떻게 관리할 것인가?
- 애플리케이션 Pod에는 필요한 S3 Prefix에 대한 최소 권한만 제공한다.
- S3_BUCKET, S3_PREFIX 같은 일반 설정은 ConfigMap으로 관리할 수 있다.
- AWS Access Key, Secret Access Key 같은 민감 정보는 Secret으로 관리해야 한다.
- Pod가 raw, clean, feature, log, artifact 전체를 무제한으로 삭제할 수 있게 하면 안 된다.
- OpenShift에서 실행되는 앱은 주로 필요한 Prefix에 읽기 또는 쓰기 권한만 갖도록 설계한다.

## 11. g4dn 연결

- g4dn GPU 실습에서는 어떤 S3 권한이 필요한가?
- GPU 실습 서버는 학습 데이터 읽기 권한이 필요하다.
- 모델 파일, 추론 결과, 실행 로그를 저장할 Prefix에 쓰기 권한이 필요하다.
- raw 원본 삭제 권한은 필요하지 않다.
- 모델 산출물 저장 위치는 users/{AUTHOR}/artifact/week7/ 또는 users/{AUTHOR}/log/week7/처럼 분리하는 것이 좋다.
- GPU 실습 결과는 용량이 커질 수 있으므로 Lifecycle 기준과 삭제 승인 기준을 함께 정해야 한다.

## 12. 사고 예방 시나리오

| 사고 | 예방 방법 |
|---|---|
| raw 삭제 | raw Prefix에는 DeleteObject 권한을 기본적으로 부여하지 않는다. |
| 다른 개인 Prefix 업로드 | users/{AUTHOR}/ Prefix로 접근 범위를 제한한다. |
| log 삭제 | log Prefix에는 삭제 권한을 제한하고, 조회와 업로드 중심으로 허용한다. |
| artifact 삭제 | 최종 산출물 Prefix는 삭제 전 승인 절차를 둔다. |
| Lifecycle 오설정 | PutLifecycleConfiguration 권한은 강사/관리자에게만 허용한다. |
| Access Key 노출 | .env를 Git에 올리지 않고, Secret과 환경 변수 관리를 분리한다. |

## 13. 생성한 산출물

| 산출물 | 경로 |
|---|---|
| IAM 운영 규칙 Markdown | outputs/day4_s3_iam_operation_rules.md |
| IAM 운영 규칙 JSON | outputs/day4_s3_iam_operation_rules.json |
| 개인 권한 매트릭스 | outputs/day4_s3_personal_permission_matrix.md |

## 14. 오늘 이해한 점

-

## 15. 다음 교시에서 할 일

Day 4 산출물 정리 + Day 5 예고
"""

# 불필요한 앞뒤 공백 정리 후 저장
practice_record_text = textwrap.dedent(practice_record_text).strip() + "\n"

practice_record_file.write_text(practice_record_text, encoding="utf-8")

print("실습 기록지 저장:", practice_record_file)
print("존재 여부:", practice_record_file.exists())
print("상대 경로:", practice_record_file.relative_to(BASE_DIR))

실습 기록지 저장: /home/soldesk/week2-reproducibility/reports/week2/day4_period7_iam_operation_rules_record.md
존재 여부: True
상대 경로: reports/week2/day4_period7_iam_operation_rules_record.md

In [149]:
from pathlib import Path
import pandas as pd
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = BASE_DIR / "outputs"
REPORT_DIR = BASE_DIR / "reports" / "week2"
required_outputs = {
    "s3_data_lake_draft": OUTPUT_DIR / "day4_s3_data_lake_draft.md",
    "s3_prefix_design_md": OUTPUT_DIR / "day4_s3_prefix_design.md",
    "s3_prefix_design_json": OUTPUT_DIR / "day4_s3_prefix_design.json",
    "s3_upload_record_json": OUTPUT_DIR / "day4_s3_upload_record.json",
    "s3_upload_record_md": OUTPUT_DIR / "day4_s3_upload_record.md",
    "s3_file_naming_rules": OUTPUT_DIR / "day4_s3_file_naming_rules.md",
    "s3_data_loading_rules_md": OUTPUT_DIR / "day4_s3_data_loading_rules.md",
    "s3_data_loading_rules_json": OUTPUT_DIR / "day4_s3_data_loading_rules.json",
    "s3_versioning_versions_raw": OUTPUT_DIR / "day4_s3_versioning_versions_raw.json",
    "s3_versioning_version_ids": OUTPUT_DIR / "day4_s3_versioning_version_ids.json",
    "s3_versioning_record_json": OUTPUT_DIR / "day4_s3_versioning_record.json",
    "s3_versioning_record_md": OUTPUT_DIR / "day4_s3_versioning_record.md",
    "s3_lifecycle_design_md": OUTPUT_DIR / "day4_s3_lifecycle_design.md",
    "s3_lifecycle_design_json": OUTPUT_DIR / "day4_s3_lifecycle_design.json",
    "s3_lifecycle_policy_example": OUTPUT_DIR / "day4_s3_lifecycle_tmp_policy_example.json",
    "s3_lifecycle_record_md": OUTPUT_DIR / "day4_s3_lifecycle_record.md",
    "s3_iam_rules_md": OUTPUT_DIR / "day4_s3_iam_operation_rules.md",
    "s3_iam_rules_json": OUTPUT_DIR / "day4_s3_iam_operation_rules.json",
    "s3_permission_matrix": OUTPUT_DIR / "day4_s3_personal_permission_matrix.md",
    "run_info": OUTPUT_DIR / "run_info.json",
}
local_artifact_status = []
for name, path in required_outputs.items():
    local_artifact_status.append({
        "name": name,
        "path": str(path.relative_to(BASE_DIR)),
        "exists": path.exists()
    })
local_artifact_status_df = pd.DataFrame(local_artifact_status)
local_artifact_status_df

,name,path,exists
0,s3_data_lake_draft,outputs/day4_s3_data_lake_draft.md,True
1,s3_prefix_design_md,outputs/day4_s3_prefix_design.md,True
2,s3_prefix_design_json,outputs/day4_s3_prefix_design.json,True
3,s3_upload_record_json,outputs/day4_s3_upload_record.json,True
4,s3_upload_record_md,outputs/day4_s3_upload_record.md,True
5,s3_file_naming_rules,outputs/day4_s3_file_naming_rules.md,True
6,s3_data_loading_rules_md,outputs/day4_s3_data_loading_rules.md,True
7,s3_data_loading_rules_json,outputs/day4_s3_data_loading_rules.json,True
8,s3_versioning_versions_raw,outputs/day4_s3_versioning_versions_raw.json,True
9,s3_versioning_version_ids,outputs/day4_s3_versioning_version_ids.json,True
10,s3_versioning_record_json,outputs/day4_s3_versioning_record.json,True
11,s3_versioning_record_md,outputs/day4_s3_versioning_record.md,True
12,s3_lifecycle_design_md,outputs/day4_s3_lifecycle_design.md,True
13,s3_lifecycle_design_json,outputs/day4_s3_lifecycle_design.json,True
14,s3_lifecycle_policy_example,outputs/day4_s3_lifecycle_tmp_policy_example.json,True
15,s3_lifecycle_record_md,outputs/day4_s3_lifecycle_record.md,True
16,s3_iam_rules_md,outputs/day4_s3_iam_operation_rules.md,True
17,s3_iam_rules_json,outputs/day4_s3_iam_operation_rules.json,True
18,s3_permission_matrix,outputs/day4_s3_personal_permission_matrix.md,True
19,run_info,outputs/run_info.json,True

In [150]:
from pathlib import Path
import json
from datetime import datetime
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
AUTHOR = "student"
BUCKET = "edu-ai-lake"
S3_CLEAN_DATA_URI = f"s3://{BUCKET}/users/{AUTHOR}/clean/customers/customers_clean_20260606_v2.csv"
day5_ready_info = {
    "day": "week2_day4",
    "lesson": "period8_day4_final_summary",
    "author": AUTHOR,
    "bucket": BUCKET,
    "created_at": datetime.now().isoformat(),
    "day5_input": {
        "s3_clean_data_uri": S3_CLEAN_DATA_URI,
        "local_clean_data": "data/clean/customers_clean_20260606_v2.csv",
        "expected_stage": "clean",
        "next_use": "Day 5 baseline preparation"
    },
    "day5_expected_work": [
        "Read S3 clean data",
        "Validate shape and columns",
        "Separate feature candidates and target",
        "Prepare train/test split",
        "Create baseline model preparation record"
    ],
    "environment_connection": {
        "local_pc_wsl2": True,
        "openshift_local_same_s3_uri": True,
        "developer_sandbox_same_s3_uri": True,
        "g4dn_used_in_day4": False,
        "g4dn_future_usage": "GPU 실습 주차에서 같은 S3 Prefix 체계를 사용"
    }
}
day5_ready_file = OUTPUT_DIR / "day4_day5_ready_info.json"
day5_ready_file.write_text(
    json.dumps(day5_ready_info, ensure_ascii=False, indent=2),
    encoding="utf-8"
)
print("Day 5 준비 정보 저장:", day5_ready_file)
print("존재 여부:", day5_ready_file.exists())

Day 5 준비 정보 저장: /home/soldesk/week2-reproducibility/outputs/day4_day5_ready_info.json
존재 여부: True

In [151]:
import json
from pathlib import Path
from datetime import datetime
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
AUTHOR = "student"
BUCKET = "edu-ai-lake"
AWS_REGION = "ap-northeast-2"
day4_final_summary = {
    "day": "week2_day4",
    "topic": "s3_data_upload_versioning_lifecycle_iam",
    "author": AUTHOR,
    "bucket": BUCKET,
    "region": AWS_REGION,
    "created_at": datetime.now().isoformat(),
    "environment": {
        "local_pc_wsl2_used": True,
        "openshift_local_used": False,
        "developer_sandbox_used": False,
        "g4dn_used": False,
        "h200_used": False,
        "reason_g4dn_not_used": "Day 4는 S3 데이터 운영 실습이므로 GPU가 필요하지 않음"
    },
    "s3_prefixes": {
        "user_prefix": f"users/{AUTHOR}/",
        "raw": f"users/{AUTHOR}/raw/customers/",
        "clean": f"users/{AUTHOR}/clean/customers/",
        "feature": f"users/{AUTHOR}/feature/customers/",
        "notebook": f"users/{AUTHOR}/notebook/week2/",
        "artifact": f"users/{AUTHOR}/artifact/week2/",
        "log": f"users/{AUTHOR}/log/week2/",
        "archive": f"users/{AUTHOR}/archive/",
        "tmp": f"users/{AUTHOR}/tmp/"
    },
    "uploaded_s3_objects": {
        "raw": f"s3://{BUCKET}/users/{AUTHOR}/raw/customers/customers_raw_20260605_v1.csv",
        "clean": f"s3://{BUCKET}/users/{AUTHOR}/clean/customers/customers_clean_20260606_v2.csv",
        "run_info": f"s3://{BUCKET}/users/{AUTHOR}/log/week2/run_info_20260606_{AUTHOR}.json",
        "upload_record": f"s3://{BUCKET}/users/{AUTHOR}/log/week2/day4_s3_upload_record_{AUTHOR}.json",
        "artifact": f"s3://{BUCKET}/users/{AUTHOR}/artifact/week2/"
    },
    "file_naming_rule": {
        "pattern": "{dataset}_{stage}_{yyyymmdd}_v{version}.{ext}",
        "examples": [
            "customers_raw_20260605_v1.csv",
            "customers_clean_20260606_v2.csv",
            "customers_feature_20260607_v1.parquet",
            "run_info_week2_day4_20260606_v1.json"
        ]
    },
    "versioning_summary": {
        "concept": "same S3 key can keep multiple versions when Versioning is enabled",
        "versioning_is_safety_net": True,
        "versioning_replaces_file_naming_rule": False,
        "raw_overwrite_recommended": False,
        "record_files": [
            "outputs/day4_s3_versioning_versions_raw.json",
            "outputs/day4_s3_versioning_version_ids.json",
            "outputs/day4_s3_versioning_record.json",
            "outputs/day4_s3_versioning_record.md"
        ]
    },
    "lifecycle_summary": {
        "concept": "retention policy for transition and expiration",
        "raw_auto_expiration_recommended": False,
        "tmp_expiration_candidate": True,
        "record_files": [
            "outputs/day4_s3_lifecycle_design.md",
            "outputs/day4_s3_lifecycle_design.json",
            "outputs/day4_s3_lifecycle_tmp_policy_example.json",
            "outputs/day4_s3_lifecycle_record.md"
        ]
    },
    "iam_summary": {
        "principle": "least privilege",
        "student_scope": f"users/{AUTHOR}/ only",
        "raw_delete_allowed": False,
        "log_delete_allowed": False,
        "final_artifact_delete_allowed": False,
        "student_can_change_versioning": False,
        "student_can_change_lifecycle": False,
        "record_files": [
            "outputs/day4_s3_iam_operation_rules.md",
            "outputs/day4_s3_iam_operation_rules.json",
            "outputs/day4_s3_personal_permission_matrix.md"
        ]
    },
    "local_artifacts": local_artifact_status,
    "day5_ready": {
        "s3_clean_data_uri": f"s3://{BUCKET}/users/{AUTHOR}/clean/customers/customers_clean_20260606_v2.csv",
        "ready_to_read_s3_clean_data": True,
        "next_topic": "S3 clean data reading and baseline preparation"
    },
    "next_day": "week2_day5",
    "next_day_topic": "S3 clean 데이터 읽기 + baseline 준비"
}
day4_final_summary_file = OUTPUT_DIR / "day4_final_summary.json"
day4_final_summary_file.write_text(
    json.dumps(day4_final_summary, ensure_ascii=False, indent=2),
    encoding="utf-8"
)
print("Day 4 최종 요약 JSON 저장:", day4_final_summary_file)
print("존재 여부:", day4_final_summary_file.exists())

Day 4 최종 요약 JSON 저장: /home/soldesk/week2-reproducibility/outputs/day4_final_summary.json
존재 여부: True

In [152]:
from pathlib import Path
import os
import textwrap

# 현재 실행 위치가 notebooks/이면 부모 폴더를 프로젝트 루트로 사용
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# outputs 폴더 준비
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# 기존 셀에서 AUTHOR 또는 author 변수가 있으면 사용하고,
# 없으면 환경 변수 또는 기본값 사용
AUTHOR = globals().get(
    "AUTHOR",
    globals().get("author", os.environ.get("AUTHOR", "student"))
)

# 기존 셀에서 BUCKET 또는 bucket_name 변수가 있으면 사용하고,
# 없으면 환경 변수 또는 기본값 사용
BUCKET = globals().get(
    "BUCKET",
    globals().get("bucket_name", os.environ.get("S3_BUCKET", "edu-ai-lake"))
)

# 기존 셀에서 AWS_REGION 변수가 있으면 사용하고,
# 없으면 환경 변수 또는 기본값 사용
AWS_REGION = globals().get(
    "AWS_REGION",
    os.environ.get("AWS_REGION", "ap-northeast-2")
)

# Prefix 정의
user_prefix = f"users/{AUTHOR}/"
raw_prefix = f"{user_prefix}raw/customers/"
clean_prefix = f"{user_prefix}clean/customers/"
feature_prefix = f"{user_prefix}feature/customers/"
notebook_prefix = f"{user_prefix}notebook/week2/"
artifact_prefix = f"{user_prefix}artifact/week2/"
log_prefix = f"{user_prefix}log/week2/"
archive_prefix = f"{user_prefix}archive/"
tmp_prefix = f"{user_prefix}tmp/"

# S3 URI 정의
raw_s3_uri = f"s3://{BUCKET}/{raw_prefix}customers_raw_20260605_v1.csv"
clean_s3_uri = f"s3://{BUCKET}/{clean_prefix}customers_clean_20260606_v2.csv"
run_info_s3_uri = f"s3://{BUCKET}/{log_prefix}run_info_20260606_{AUTHOR}.json"
artifact_s3_uri = f"s3://{BUCKET}/{artifact_prefix}"

# 저장 파일 경로
day4_final_summary_md_file = OUTPUT_DIR / "day4_final_summary.md"

# Markdown 문서 내용
day4_final_summary_md = f"""
# 2주차 Day 4 최종 요약

## 1. 작성자

- author: {AUTHOR}

## 2. 실습 리전

- region: {AWS_REGION}

## 3. 사용한 S3 버킷

- bucket: {BUCKET}

## 4. Day 4 주제

S3 데이터 적재 / 버전관리 / 수명주기

S3는 Simple Storage Service의 약자이며, AWS에서 객체 파일을 저장하는 스토리지 서비스이다.

## 5. Day 4 핵심 메시지

Day 4의 목표는 S3에 파일을 올리는 것에서 끝나지 않는다.

S3 Prefix, 업로드 기록, 파일명 규칙, Versioning, Lifecycle, IAM 최소 권한을 함께 정리해야  
운영 가능한 AI 실험 데이터 자산 구조가 된다.

IAM은 Identity and Access Management의 약자이며, AWS에서 사용자와 권한을 관리하는 서비스이다.

## 6. 개인 Prefix 구조

| 구분 | Prefix |
|---|---|
| user | {user_prefix} |
| raw | {raw_prefix} |
| clean | {clean_prefix} |
| feature | {feature_prefix} |
| notebook | {notebook_prefix} |
| artifact | {artifact_prefix} |
| log | {log_prefix} |
| archive | {archive_prefix} |
| tmp | {tmp_prefix} |

## 7. 업로드한 핵심 데이터

| 구분 | S3 URI |
|---|---|
| raw | {raw_s3_uri} |
| clean | {clean_s3_uri} |
| run_info | {run_info_s3_uri} |
| artifact | {artifact_s3_uri} |

## 8. 파일명 규칙

기본 형식:

```text
{{dataset}}_{{stage}}_{{yyyymmdd}}_v{{version}}.{{ext}}
```

예시:

```text
customers_raw_20260605_v1.csv
customers_clean_20260606_v2.csv
customers_feature_20260607_v1.parquet
run_info_week2_day4_20260606_v1.json
```

좋은 파일명은 파일을 열어보지 않아도 데이터셋, 상태, 생성일, 버전을 알 수 있어야 한다.

## 9. Versioning 요약

S3 Versioning은 같은 객체 Key에 여러 버전을 보존할 수 있게 해주는 안전망이다.

하지만 Versioning은 파일명 규칙을 대체하지 않는다.

Versioning이 있다고 raw 데이터를 덮어써도 되는 것도 아니다.

운영 원칙은 다음과 같다.

- raw 데이터는 같은 Key로 덮어쓰지 않는다.
- clean 데이터는 날짜와 버전을 포함한 파일명으로 관리한다.
- 이전 버전 복구에는 Key와 VersionId가 중요하다.
- Delete Marker는 삭제된 것처럼 보이게 하는 표시용 버전이다.

## 10. Lifecycle 요약

Lifecycle은 오래된 객체를 다른 스토리지 클래스로 전환하거나 일정 기간 후 만료 처리하는 보관 정책이다.

raw는 원본 재현 기준이므로 자동 삭제 정책을 매우 조심해야 한다.

tmp와 versioning-test 같은 실습용 Prefix는 짧은 기간 후 정리 후보가 될 수 있다.

Lifecycle 운영 원칙은 다음과 같다.

- raw Prefix에는 위험한 자동 삭제를 걸지 않는다.
- log Prefix는 실행 추적에 필요하므로 삭제에 주의한다.
- artifact Prefix는 결과 산출물 보관용이므로 삭제 제한이 필요하다.
- tmp Prefix는 실습용 임시 파일 정리 후보가 될 수 있다.
- versioning-test Prefix는 이전 버전 정리 실습 후보가 될 수 있다.

## 11. IAM 최소 권한 요약

필요한 사람에게, 필요한 Prefix에 대해서, 필요한 Action만 허용한다.

학생 개인은 본인 {user_prefix} Prefix 중심으로 작업한다.

권한 운영 원칙은 다음과 같다.

- raw 삭제는 제한한다.
- log 삭제는 제한한다.
- artifact 최종 산출물 삭제는 제한한다.
- 다른 개인의 Prefix 접근은 제한한다.
- Versioning과 Lifecycle 설정 변경은 학생 개인이 임의로 수행하지 않는다.
- PutBucketPolicy, PutBucketVersioning, PutLifecycleConfiguration 같은 버킷 전체 설정 권한은 관리자 중심으로 관리한다.

## 12. OpenShift Local / Developer Sandbox 연결

Day 4에서는 OpenShift 앱 배포를 하지 않았다.

하지만 OpenShift Local 또는 Developer Sandbox에서도 같은 S3 Prefix를 사용할 수 있어야 한다.

OpenShift에서는 다음 값을 환경 변수 또는 ConfigMap으로 주입할 수 있다.

```text
S3_BUCKET={BUCKET}
S3_CLEAN_PREFIX={clean_prefix}
S3_LOG_PREFIX={log_prefix}
S3_ARTIFACT_PREFIX={artifact_prefix}
```

AWS 인증 정보는 Secret 또는 더 안전한 인증 방식으로 관리한다.

OpenShift에서 실행되는 애플리케이션도 raw, clean, feature, log, artifact Prefix를 구분해서 사용해야 한다.

## 13. g4dn.xlarge 연결

Day 4에서는 g4dn.xlarge를 사용하지 않았다.

S3 데이터 운영 실습에는 GPU가 필요하지 않기 때문이다.

이후 GPU 실습 주차에서는 g4dn에서 생성한 GPU 결과, 모델 파일, 실행 로그를 같은 artifact/log Prefix 체계로 저장한다.

예시 저장 위치는 다음과 같다.

```text
users/{AUTHOR}/artifact/week7/
users/{AUTHOR}/log/week7/
```

g4dn 실습 결과도 파일명에 데이터셋, stage, 날짜, 버전을 포함하는 것이 좋다.

## 14. Day 5 준비

Day 5에서는 아래 clean 데이터를 다시 읽어 baseline 준비를 시작한다.

```text
{clean_s3_uri}
```

Day 5에서 할 일:

- S3 clean 데이터 읽기
- 데이터 shape 확인
- 컬럼과 타입 확인
- target 컬럼 확인
- feature 후보 컬럼 확인
- train/test split 준비
- baseline 모델 준비 기록 작성

## 15. 오늘 이해한 점

S3는 단순 파일 저장소가 아니다.

AI 실험에서 S3는 raw, clean, feature, notebook, artifact, log, archive를 체계적으로 관리하는 데이터 자산 저장소다.

좋은 데이터 운영은 업로드 명령어가 아니라 Prefix, 파일명, 버전, 보관 정책, 권한 규칙에서 시작한다.

## 16. Day 4 생성 산출물 요약

| 산출물 | 경로 |
|---|---|
| S3 업로드 기록 Markdown | outputs/day4_s3_upload_record.md |
| 파일명 규칙 Markdown | outputs/day4_s3_file_naming_rules.md |
| 데이터 적재 규칙 Markdown | outputs/day4_s3_data_loading_rules.md |
| 데이터 적재 규칙 JSON | outputs/day4_s3_data_loading_rules.json |
| Versioning 기록 Markdown | outputs/day4_s3_versioning_record.md |
| Versioning 기록 JSON | outputs/day4_s3_versioning_record.json |
| Lifecycle 설계 Markdown | outputs/day4_s3_lifecycle_design.md |
| Lifecycle 설계 JSON | outputs/day4_s3_lifecycle_design.json |
| Lifecycle tmp 정책 예시 JSON | outputs/day4_s3_lifecycle_tmp_policy_example.json |
| IAM 운영 규칙 Markdown | outputs/day4_s3_iam_operation_rules.md |
| IAM 운영 규칙 JSON | outputs/day4_s3_iam_operation_rules.json |
| 개인 권한 매트릭스 | outputs/day4_s3_personal_permission_matrix.md |
| Day 4 최종 요약 Markdown | outputs/day4_final_summary.md |
"""

# 불필요한 앞뒤 공백 정리 후 저장
day4_final_summary_md = textwrap.dedent(day4_final_summary_md).strip() + "\n"

day4_final_summary_md_file.write_text(
    day4_final_summary_md,
    encoding="utf-8"
)

print("Day 4 최종 요약 Markdown 저장:", day4_final_summary_md_file)
print("존재 여부:", day4_final_summary_md_file.exists())
print("상대 경로:", day4_final_summary_md_file.relative_to(BASE_DIR))

Day 4 최종 요약 Markdown 저장: /home/soldesk/week2-reproducibility/outputs/day4_final_summary.md
존재 여부: True
상대 경로: outputs/day4_final_summary.md

In [153]:
from pathlib import Path
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
AUTHOR = "student"
BUCKET = "edu-ai-lake"
submission_record_file = OUTPUT_DIR / "day4_submission_record.md"
submission_record_text = f"""# 2주차 Day 4 제출 확인 기록
## 1. 작성자
- author: {AUTHOR}
## 2. 버킷
- bucket: {BUCKET}
## 3. 개인 Prefix
| 구분 | Prefix |
|---|---|
| raw | users/{AUTHOR}/raw/customers/ |
| clean | users/{AUTHOR}/clean/customers/ |
| feature | users/{AUTHOR}/feature/customers/ |
| notebook | users/{AUTHOR}/notebook/week2/ |
| artifact | users/{AUTHOR}/artifact/week2/ |
| log | users/{AUTHOR}/log/week2/ |
| archive | users/{AUTHOR}/archive/ |
## 4. 업로드한 파일 기록
| 구분 | 로컬 파일 | S3 위치 |
|---|---|---|
| raw | data/raw/customers_raw.csv | s3://{BUCKET}/users/{AUTHOR}/raw/customers/ |
| clean | data/clean/customers_clean_20260606_v2.csv | s3://{BUCKET}/users/{AUTHOR}/clean/customers/ |
| run_info | outputs/run_info.json | s3://{BUCKET}/users/{AUTHOR}/log/week2/ |
| upload record | outputs/day4_s3_upload_record.json | s3://{BUCKET}/users/{AUTHOR}/log/week2/ |
| lifecycle design | outputs/day4_s3_lifecycle_design.md | s3://{BUCKET}/users/{AUTHOR}/artifact/week2/ |
| iam rules | outputs/day4_s3_iam_operation_rules.md | s3://{BUCKET}/users/{AUTHOR}/artifact/week2/ |
## 5. 작성한 주요 문서
| 문서 | 로컬 경로 |
|---|---|
| S3 데이터 레이크 구조 초안 | outputs/day4_s3_data_lake_draft.md |
| S3 Prefix 설계안 | outputs/day4_s3_prefix_design.md |
| S3 Prefix 설계 JSON | outputs/day4_s3_prefix_design.json |
| S3 업로드 기록 | outputs/day4_s3_upload_record.md |
| S3 파일명 규칙 | outputs/day4_s3_file_naming_rules.md |
| S3 데이터 적재 규칙 | outputs/day4_s3_data_loading_rules.md |
| S3 Versioning 기록 | outputs/day4_s3_versioning_record.md |
| S3 Lifecycle 설계 | outputs/day4_s3_lifecycle_design.md |
| S3 IAM 운영 규칙 | outputs/day4_s3_iam_operation_rules.md |
| 개인 권한 매트릭스 | outputs/day4_s3_personal_permission_matrix.md |
| Day 4 최종 요약 | outputs/day4_final_summary.md |
## 6. Versioning 확인 기록
| 항목 | 기록 |
|---|---|
| Versioning 실습 대상 | users/{AUTHOR}/clean/customers/versioning-test/ |
| 최신 VersionId 기록 | outputs/day4_s3_versioning_version_ids.json |
| 버전 목록 원본 | outputs/day4_s3_versioning_versions_raw.json |
| 이전 버전 다운로드 확인 | tmp/versioning-test/download_previous.csv |
## 7. Lifecycle 설계 요약
| Prefix | 보관 기준 |
|---|---|
| raw | 장기 보관, 자동 삭제 금지 |
| clean | 중기/장기 보관 |
| feature | 재생성 가능성 확인 후 정리 후보 |
| log | 추적 기간 보관 |
| artifact | 평가/제출 기간 보관 |
| tmp | 짧은 기간 후 정리 후보 |
## 8. IAM 최소 권한 요약
| 항목 | 기준 |
|---|---|
| 학생 개인 범위 | users/{AUTHOR}/ |
| raw 삭제 | 제한 |
| log 삭제 | 제한 |
| artifact 최종 산출물 삭제 | 제한 |
| tmp 삭제 | 본인 tmp Prefix 안에서 허용 가능 |
| Versioning 설정 변경 | 학생 개인에게 불필요 |
| Lifecycle 설정 변경 | 학생 개인에게 불필요 |
| 다른 개인 Prefix 쓰기 | 허용하지 않음 |
## 9. Day 5 준비 상태
| 항목 | 값 |
|---|---|
| Day 5 입력 데이터 | s3://{BUCKET}/users/{AUTHOR}/clean/customers/customers_clean_20260606_v2.csv |
| 입력 데이터 상태 | clean |
| 다음 실습 | S3 clean 데이터 읽기 + baseline 준비 |
| 중심 환경 | 개인 로컬 PC WSL2 |
| OpenShift | 같은 S3 URI 사용 구조로 연결 |
| g4dn | Day 4에서는 미사용, GPU 주차에서 연결 |
## 10. 오늘 배운 핵심
S3는 단순 파일 저장소가 아니라 AI 실험 데이터 자산의 기준 저장소다.
raw, clean, feature, log, artifact는 역할이 다르며 Prefix도 분리해야 한다.
파일명에는 dataset, stage, 날짜, 버전, 확장자가 드러나야 한다.
Versioning은 안전망이고, Lifecycle은 보관 정책이며, IAM 최소 권한은 사고 예방 장치다.
Day 5에서는 S3 clean 데이터를 다시 읽어 baseline 준비로 연결한다.
"""
submission_record_file.write_text(submission_record_text, encoding="utf-8")
print("Day 4 제출 확인 기록 저장:", submission_record_file)
print("존재 여부:", submission_record_file.exists())

Day 4 제출 확인 기록 저장: /home/soldesk/week2-reproducibility/outputs/day4_submission_record.md
존재 여부: True

In [155]:
import pandas as pd
from pathlib import Path
BASE_DIR = Path.cwd().parent if Path.cwd().name in ["notebook", "notebooks"] else Path.cwd()
clean_from_s3_file = BASE_DIR / "data" / "from_s3" / "customers_clean_20260606_v2.csv"
df_clean_s3 = pd.read_csv(clean_from_s3_file)
print("shape:", df_clean_s3.shape)
print("columns:", list(df_clean_s3.columns))
df_clean_s3.head()

shape: (9, 29)
columns: ['customer_id', 'age', 'monthly_fee', 'usage_days', 'support_calls', 'gender_standard', 'contract_type_standard', 'signup_date', 'last_login_date', 'signup_year', 'signup_month', 'last_login_dayofweek', 'last_login_day_name', 'days_since_signup', 'days_since_last_login', 'age_was_missing', 'monthly_fee_was_missing', 'gender_was_missing', 'contract_type_was_missing', 'monthly_fee_outlier', 'support_calls_outlier', 'is_high_fee', 'is_short_user', 'has_many_support_calls', 'usage_group', 'is_long_contract', 'churn', 'gender', 'contract_type']

,customer_id,age,monthly_fee,usage_days,support_calls,gender_standard,contract_type_standard,signup_date,last_login_date,signup_year,...,monthly_fee_outlier,support_calls_outlier,is_high_fee,is_short_user,has_many_support_calls,usage_group,is_long_contract,churn,gender,contract_type
0,C001,34,59000,120,1,female,monthly,2025-01-10,2026-06-01,2025,...,0,0,1,0,0,middle,0,0,female,month-to-month
1,C002,45,79000,380,3,male,one_year,2024-12-01,2026-05-10,2024,...,0,0,1,0,1,long,1,1,male,1-year
2,C003,41,72000,45,0,female,monthly,2026-04-20,2026-06-03,2026,...,0,0,1,0,0,middle,0,0,female,month-to-month
3,C004,52,99000,800,5,male,one_year,2023-05-15,2026-03-01,2023,...,0,0,1,0,1,long,1,1,male,1-year
4,C005,41,69000,220,2,female,unknown,2025-08-03,2026-05-30,2025,...,0,0,1,0,0,middle,0,0,female,unknown

In [156]:
import pandas as pd
AUTHOR = "kim-juil"
BUCKET = "edu-ai-lake"
s3_clean_uri = f"s3://{BUCKET}/users/{AUTHOR}/clean/customers/customers_clean_20260606_v2.csv"
df_clean_s3 = pd.read_csv(s3_clean_uri)
print("shape:", df_clean_s3.shape)
print("columns:", list(df_clean_s3.columns))
df_clean_s3.head()

shape: (9, 29)
columns: ['customer_id', 'age', 'monthly_fee', 'usage_days', 'support_calls', 'gender_standard', 'contract_type_standard', 'signup_date', 'last_login_date', 'signup_year', 'signup_month', 'last_login_dayofweek', 'last_login_day_name', 'days_since_signup', 'days_since_last_login', 'age_was_missing', 'monthly_fee_was_missing', 'gender_was_missing', 'contract_type_was_missing', 'monthly_fee_outlier', 'support_calls_outlier', 'is_high_fee', 'is_short_user', 'has_many_support_calls', 'usage_group', 'is_long_contract', 'churn', 'gender', 'contract_type']

,customer_id,age,monthly_fee,usage_days,support_calls,gender_standard,contract_type_standard,signup_date,last_login_date,signup_year,...,monthly_fee_outlier,support_calls_outlier,is_high_fee,is_short_user,has_many_support_calls,usage_group,is_long_contract,churn,gender,contract_type
0,C001,34,59000,120,1,female,monthly,2025-01-10,2026-06-01,2025,...,0,0,1,0,0,middle,0,0,female,month-to-month
1,C002,45,79000,380,3,male,one_year,2024-12-01,2026-05-10,2024,...,0,0,1,0,1,long,1,1,male,1-year
2,C003,41,72000,45,0,female,monthly,2026-04-20,2026-06-03,2026,...,0,0,1,0,0,middle,0,0,female,month-to-month
3,C004,52,99000,800,5,male,one_year,2023-05-15,2026-03-01,2023,...,0,0,1,0,1,long,1,1,male,1-year
4,C005,41,69000,220,2,female,unknown,2025-08-03,2026-05-30,2025,...,0,0,1,0,0,middle,0,0,female,unknown

In [157]:
from pathlib import Path
import os
import json
import textwrap

# 현재 실행 위치가 notebook 또는 notebooks 폴더이면 부모 폴더를 프로젝트 루트로 사용
BASE_DIR = Path.cwd().parent if Path.cwd().name in ["notebook", "notebooks"] else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# reports/week2 폴더 준비
REPORT_DIR = BASE_DIR / "reports" / "week2"
OUTPUT_DIR = BASE_DIR / "outputs"

REPORT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# 기존 셀에서 AUTHOR 또는 author 변수가 있으면 사용하고,
# 없으면 환경 변수 또는 기본값 사용
AUTHOR = globals().get(
    "AUTHOR",
    globals().get("author", os.environ.get("AUTHOR", "student"))
)

# 기존 셀에서 BUCKET 또는 bucket_name 변수가 있으면 사용하고,
# 없으면 환경 변수 또는 기본값 사용
BUCKET = globals().get(
    "BUCKET",
    globals().get("bucket_name", os.environ.get("S3_BUCKET", "edu-ai-lake"))
)

# Prefix 정의
user_prefix = f"users/{AUTHOR}/"
raw_prefix = f"{user_prefix}raw/customers/"
clean_prefix = f"{user_prefix}clean/customers/"
feature_prefix = f"{user_prefix}feature/customers/"
notebook_prefix = f"{user_prefix}notebook/week2/"
artifact_prefix = f"{user_prefix}artifact/week2/"
log_prefix = f"{user_prefix}log/week2/"
archive_prefix = f"{user_prefix}archive/"
tmp_prefix = f"{user_prefix}tmp/"

# 핵심 로컬 파일
raw_local_file = "data/raw/customers_raw.csv"
clean_local_file = "data/clean/customers_clean_20260606_v2.csv"
run_info_local_file = "outputs/run_info.json"
upload_record_local_file = "outputs/day4_s3_upload_record.md"
final_summary_local_file = "outputs/day4_final_summary.md"

# 핵심 S3 URI
raw_s3_uri = f"s3://{BUCKET}/{raw_prefix}customers_raw_20260605_v1.csv"
clean_s3_uri = f"s3://{BUCKET}/{clean_prefix}customers_clean_20260606_v2.csv"
run_info_s3_uri = f"s3://{BUCKET}/{log_prefix}run_info_20260606_{AUTHOR}.json"
upload_record_s3_uri = f"s3://{BUCKET}/{log_prefix}day4_s3_upload_record_{AUTHOR}.md"
final_summary_s3_uri = f"s3://{BUCKET}/{artifact_prefix}day4_final_summary_{AUTHOR}.md"

# Versioning 실습 대상
versioning_test_prefix = f"{clean_prefix}versioning-test/"
versioning_test_key = f"{versioning_test_prefix}customers_clean_versioning_test_same_key.csv"

# VersionId 요약 JSON이 있으면 읽어서 자동 반영
version_ids_json_file = OUTPUT_DIR / "day4_s3_versioning_version_ids.json"

latest_version_id = ""
previous_version_id = ""
previous_version_download_checked = "확인 필요"

if version_ids_json_file.exists():
    try:
        version_ids_data = json.loads(
            version_ids_json_file.read_text(encoding="utf-8")
        )

        latest_version_id = (
            version_ids_data.get("latest_version_id")
            or version_ids_data.get("v2_version_id")
            or ""
        )

        previous_version_id = (
            version_ids_data.get("previous_version_id")
            or version_ids_data.get("v1_version_id")
            or ""
        )

        if previous_version_id:
            previous_version_download_checked = "확인 필요"

    except json.JSONDecodeError:
        latest_version_id = ""
        previous_version_id = ""
        previous_version_download_checked = "VersionId JSON 형식 확인 필요"

# Day 5 clean 데이터 준비 상태 확인
day5_clean_local_candidates = [
    BASE_DIR / "data" / "from_s3" / "customers_clean_20260606_v2.csv",
    BASE_DIR / "data" / "clean" / "customers_clean_20260606_v2.csv",
]

day5_clean_local_file = next(
    (path for path in day5_clean_local_candidates if path.exists()),
    None
)

if day5_clean_local_file is not None:
    clean_data_status = f"로컬 파일 확인됨: {day5_clean_local_file.relative_to(BASE_DIR)}"
    baseline_ready = "가능"
else:
    clean_data_status = "로컬 파일 확인 필요"
    baseline_ready = "확인 필요"

# 작성한 문서 목록
documents = [
    {
        "name": "S3 Prefix 설계안",
        "local": "reports/week2/day4_period2_s3_prefix_design_record.md",
        "s3": f"s3://{BUCKET}/{artifact_prefix}day4_period2_s3_prefix_design_record_{AUTHOR}.md",
    },
    {
        "name": "S3 업로드 기록",
        "local": "outputs/day4_s3_upload_record.md",
        "s3": f"s3://{BUCKET}/{log_prefix}day4_s3_upload_record_{AUTHOR}.md",
    },
    {
        "name": "파일명 규칙",
        "local": "outputs/day4_s3_file_naming_rules.md",
        "s3": f"s3://{BUCKET}/{artifact_prefix}day4_s3_file_naming_rules_{AUTHOR}.md",
    },
    {
        "name": "데이터 적재 규칙",
        "local": "outputs/day4_s3_data_loading_rules.md",
        "s3": f"s3://{BUCKET}/{artifact_prefix}day4_s3_data_loading_rules_{AUTHOR}.md",
    },
    {
        "name": "Versioning 기록",
        "local": "outputs/day4_s3_versioning_record.md",
        "s3": f"s3://{BUCKET}/{log_prefix}day4_s3_versioning_record_{AUTHOR}.md",
    },
    {
        "name": "Lifecycle 설계",
        "local": "outputs/day4_s3_lifecycle_design.md",
        "s3": f"s3://{BUCKET}/{artifact_prefix}day4_s3_lifecycle_design_{AUTHOR}.md",
    },
    {
        "name": "IAM 운영 규칙",
        "local": "outputs/day4_s3_iam_operation_rules.md",
        "s3": f"s3://{BUCKET}/{artifact_prefix}day4_s3_iam_operation_rules_{AUTHOR}.md",
    },
    {
        "name": "Day 4 최종 요약",
        "local": "outputs/day4_final_summary.md",
        "s3": final_summary_s3_uri,
    },
]

document_rows = "\n".join(
    f"| {doc['name']} | {doc['local']} | {doc['s3']} |"
    for doc in documents
)

# 저장 파일 경로
final_record_file = REPORT_DIR / "day4_period8_final_record.md"

# Markdown 실습 기록지 내용
final_record_text = f"""
# 2주차 Day 4 8교시 최종 실습 기록지

## 작성자

- author: {AUTHOR}

## 1. 오늘 주제

Day 4 산출물 정리 + Day 5 예고

## 2. 사용한 S3 버킷

- bucket: {BUCKET}

## 3. 개인 author

- author: {AUTHOR}

## 4. 사용한 Prefix

| 구분 | Prefix |
|---|---|
| raw | {raw_prefix} |
| clean | {clean_prefix} |
| feature | {feature_prefix} |
| notebook | {notebook_prefix} |
| artifact | {artifact_prefix} |
| log | {log_prefix} |
| archive | {archive_prefix} |
| tmp | {tmp_prefix} |

## 5. 업로드한 핵심 파일

| 구분 | 로컬 파일 | S3 URI |
|---|---|---|
| raw | {raw_local_file} | {raw_s3_uri} |
| clean | {clean_local_file} | {clean_s3_uri} |
| run_info | {run_info_local_file} | {run_info_s3_uri} |
| upload record | {upload_record_local_file} | {upload_record_s3_uri} |
| final summary | {final_summary_local_file} | {final_summary_s3_uri} |

## 6. 작성한 문서

| 문서 | 로컬 경로 | S3 업로드 위치 |
|---|---|---|
{document_rows}

## 7. Versioning 확인

| 항목 | 값 |
|---|---|
| 실습 대상 Key | {versioning_test_key} |
| 최신 VersionId | {latest_version_id} |
| 이전 VersionId | {previous_version_id} |
| 이전 버전 다운로드 확인 여부 | {previous_version_download_checked} |

## 8. Lifecycle 설계 요약

| Prefix | 보관 정책 |
|---|---|
| raw | 원본 데이터이므로 장기 보관하고 자동 삭제를 제한한다. |
| clean | 전처리 완료 데이터이므로 버전과 처리 기준을 함께 보관한다. |
| feature | 모델 학습 재현에 필요하므로 모델 버전과 연결해 보관한다. |
| log | 실행 조건 추적용이므로 삭제를 제한하고 장기 보관을 검토한다. |
| artifact | 리포트, 모델 파일, 최종 산출물이므로 삭제 전 승인 기준이 필요하다. |
| tmp | 실습용 임시 파일만 저장하고 짧은 기간 후 정리 후보로 둔다. |

## 9. IAM 최소 권한 요약

| 항목 | 기준 |
|---|---|
| 학생 개인 권한 범위 | 본인 {user_prefix} Prefix 중심으로 제한한다. |
| raw 삭제 권한 | 기본적으로 허용하지 않는다. |
| log 삭제 권한 | 기본적으로 제한한다. |
| artifact 삭제 권한 | 최종 산출물 삭제는 제한한다. |
| tmp 삭제 권한 | 실습용 tmp Prefix에 한해 제한적으로 허용할 수 있다. |
| Lifecycle 설정 변경 | 학생 개인에게 허용하지 않는다. |
| Versioning 설정 변경 | 학생 개인에게 허용하지 않는다. |

## 10. Day 5 준비 상태

| 항목 | 값 |
|---|---|
| Day 5 입력 clean S3 URI | {clean_s3_uri} |
| clean 데이터 상태 | {clean_data_status} |
| baseline 준비 가능 여부 | {baseline_ready} |
| 추가로 확인할 점 | S3에서 받은 clean 데이터의 shape, columns, target 컬럼, feature 후보 컬럼을 확인한다. |

## 11. OpenShift 연결

- OpenShift Local 또는 Developer Sandbox에서 같은 S3 Prefix를 어떻게 사용할 것인가?
- OpenShift에서 실행되는 애플리케이션은 S3_BUCKET, S3_CLEAN_PREFIX, S3_LOG_PREFIX, S3_ARTIFACT_PREFIX 같은 값을 환경 변수 또는 ConfigMap으로 주입받을 수 있다.
- AWS 인증 정보는 Secret 또는 더 안전한 인증 방식으로 관리한다.
- Pod가 모든 S3 경로에 접근하지 않도록 본인 Prefix 중심의 최소 권한을 적용한다.

## 12. g4dn 연결

- g4dn GPU 실습 결과는 어느 Prefix에 저장할 것인가?
- GPU 실습 결과, 모델 파일, 추론 결과, 실행 로그는 artifact와 log Prefix로 분리해서 저장한다.
- 예시 저장 위치는 다음과 같다.
  - users/{AUTHOR}/artifact/week7/
  - users/{AUTHOR}/log/week7/
- raw 원본 데이터는 GPU 실습 중에도 덮어쓰지 않는다.

## 13. 오늘 이해한 점

- S3는 단순 파일 저장소가 아니라 AI 실험 데이터 자산 저장소이다.
- Prefix는 데이터의 위치를 나누는 운영 기준이다.
- 파일명 규칙은 데이터 상태와 버전을 사람이 이해할 수 있게 해준다.
- Versioning은 실수 복구를 돕지만 파일명 규칙을 대체하지 않는다.
- Lifecycle은 비용과 보관 기간을 관리하지만 raw, log, artifact에는 조심해서 적용해야 한다.
- IAM 최소 권한은 사고를 예방하는 기본 원칙이다.

## 14. 다음 Day 5에서 할 일

S3 clean 데이터 읽기 + baseline 준비
"""

# 불필요한 앞뒤 공백 정리 후 저장
final_record_text = textwrap.dedent(final_record_text).strip() + "\n"

final_record_file.write_text(final_record_text, encoding="utf-8")

print("Day 4 8교시 최종 실습 기록지 저장:", final_record_file)
print("존재 여부:", final_record_file.exists())
print("상대 경로:", final_record_file.relative_to(BASE_DIR))

Day 4 8교시 최종 실습 기록지 저장: /home/soldesk/week2-reproducibility/reports/week2/day4_period8_final_record.md
존재 여부: True
상대 경로: reports/week2/day4_period8_final_record.md