In [1]:
from pathlib import Path
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
print("BASE_DIR:", BASE_DIR)
print("현재 작업 위치:", Path.cwd())

BASE_DIR: /home/soldesk/week2-reproducibility
현재 작업 위치: /home/soldesk/week2-reproducibility/notebooks

In [2]:
DATA_DIR = BASE_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
CLEAN_DIR = DATA_DIR / "clean"
FEATURE_DIR = DATA_DIR / "feature"
OUTPUT_DIR = BASE_DIR / "outputs"
NOTEBOOK_DIR = BASE_DIR / "notebooks"
for directory in [RAW_DIR, CLEAN_DIR, FEATURE_DIR, OUTPUT_DIR, NOTEBOOK_DIR]:
    directory.mkdir(parents=True, exist_ok=True)
    print(directory.relative_to(BASE_DIR), ":", directory.exists())

data/raw : True
data/clean : True
data/feature : True
outputs : True
notebooks : True

In [3]:
import sys
if str(BASE_DIR) not in sys.path:
    sys.path.append(str(BASE_DIR))
print("BASE_DIR in sys.path:", str(BASE_DIR) in sys.path)

BASE_DIR in sys.path: True

In [4]:
from src.seed import set_seed
SEED = set_seed(42)
print("SEED:", SEED)

SEED: 42

In [5]:
from src.paths import get_project_dirs
dirs = get_project_dirs()
print("dirs:", dirs)

dirs: {'base': PosixPath('/home/soldesk/week2-reproducibility'), 'raw': PosixPath('/home/soldesk/week2-reproducibility/data/raw'), 'clean': PosixPath('/home/soldesk/week2-reproducibility/data/clean'), 'feature': PosixPath('/home/soldesk/week2-reproducibility/data/feature'), 'outputs': PosixPath('/home/soldesk/week2-reproducibility/outputs'), 'reports': PosixPath('/home/soldesk/week2-reproducibility/reports/week2'), 'notebooks': PosixPath('/home/soldesk/week2-reproducibility/notebooks'), 'src': PosixPath('/home/soldesk/week2-reproducibility/src')}

In [6]:
import os
from dotenv import load_dotenv
env_path = BASE_DIR / ".env"
load_dotenv(env_path)
AUTHOR = os.getenv("AUTHOR", "student")
SEED = int(os.getenv("SEED", "42"))
AWS_REGION = os.getenv("AWS_REGION", "ap-northeast-2")
S3_BUCKET = os.getenv("S3_BUCKET", "edu-ai-lake")
S3_CLEAN_KEY = os.getenv(
    "S3_CLEAN_KEY",
    f"users/{AUTHOR}/clean/customers/customers_clean_20260606_v2.csv"
)
S3_FEATURE_PREFIX = os.getenv("S3_FEATURE_PREFIX", f"users/{AUTHOR}/feature/customers/")
S3_LOG_PREFIX = os.getenv("S3_LOG_PREFIX", f"users/{AUTHOR}/log/week2/")
S3_ARTIFACT_PREFIX = os.getenv("S3_ARTIFACT_PREFIX", f"users/{AUTHOR}/artifact/week2/")
print("AUTHOR:", AUTHOR)
print("SEED:", SEED)
print("AWS_REGION:", AWS_REGION)
print("S3_BUCKET:", S3_BUCKET)
print("S3_CLEAN_KEY:", S3_CLEAN_KEY)

AUTHOR: kim-juil
SEED: 42
AWS_REGION: ap-northeast-2
S3_BUCKET: edu-ai-lake
S3_CLEAN_KEY: users/kim-juil/clean/customers/customers_clean_20260606_v2.csv

In [7]:
from datetime import datetime
import json
import platform
import sys
orientation_record = {
    "day": "week2_day5",
    "lesson": "period1_orientation_and_pipeline_overview",
    "author": AUTHOR,
    "created_at": datetime.now().isoformat(),
    "python_version": sys.version,
    "platform": platform.platform(),
    "execution_environment": "local_pc_wsl2",
    "openshift_local_connection": {
        "used_in_period1": False,
        "purpose": "same project structure and environment reproducibility"
    },
    "g4dn_connection": {
        "used_in_day5": False,
        "reason": "Day 5 uses pandas and scikit-learn baseline preparation; GPU is not required"
    },
    "main_goal": "S3 clean data to baseline preparation pipeline",
    "pipeline_steps": [
        "S3 clean data download",
        "local or OpenShift Local path setup",
        "data validation",
        "feature generation",
        "train validation test split",
        "baseline model preparation",
        "metrics and report save",
        "S3 feature log artifact upload",
        "baseline preparation report"
    ],
    "warning": {
        "goal_is_not_best_model": True,
        "leakage_check_required": True,
        "test_data_should_be_reserved": True,
        "baseline_is_reference_not_final_model": True
    },
    "s3_inputs": {
        "bucket": S3_BUCKET,
        "clean_key": S3_CLEAN_KEY,
        "clean_s3_uri": f"s3://{S3_BUCKET}/{S3_CLEAN_KEY}"
    },
    "s3_outputs": {
        "feature_prefix": S3_FEATURE_PREFIX,
        "log_prefix": S3_LOG_PREFIX,
        "artifact_prefix": S3_ARTIFACT_PREFIX
    }
}
orientation_record

{'day': 'week2_day5',
 'lesson': 'period1_orientation_and_pipeline_overview',
 'author': 'kim-juil',
 'created_at': '2026-06-30T13:07:00.121596',
 'python_version': '3.12.3 (main, Mar 23 2026, 19:04:32) [GCC 13.3.0]',
 'platform': 'Linux-6.18.33.2-microsoft-standard-WSL2-x86_64-with-glibc2.39',
 'execution_environment': 'local_pc_wsl2',
 'openshift_local_connection': {'used_in_period1': False,
  'purpose': 'same project structure and environment reproducibility'},
 'g4dn_connection': {'used_in_day5': False,
  'reason': 'Day 5 uses pandas and scikit-learn baseline preparation; GPU is not required'},
 'main_goal': 'S3 clean data to baseline preparation pipeline',
 'pipeline_steps': ['S3 clean data download',
  'local or OpenShift Local path setup',
  'data validation',
  'feature generation',
  'train validation test split',
  'baseline model preparation',
  'metrics and report save',
  'S3 feature log artifact upload',
  'baseline preparation report'],
 'warning': {'goal_is_not_best_model': True,
  'leakage_check_required': True,
  'test_data_should_be_reserved': True,
  'baseline_is_reference_not_final_model': True},
 's3_inputs': {'bucket': 'edu-ai-lake',
  'clean_key': 'users/kim-juil/clean/customers/customers_clean_20260606_v2.csv',
  'clean_s3_uri': 's3://edu-ai-lake/users/kim-juil/clean/customers/customers_clean_20260606_v2.csv'},
 's3_outputs': {'feature_prefix': 'users/kim-juil/feature/customers/',
  'log_prefix': 'users/kim-juil/log/week2/',
  'artifact_prefix': 'users/kim-juil/artifact/week2/'}}

In [8]:
orientation_record_file = OUTPUT_DIR / "day5_orientation_record.json"
with open(orientation_record_file, "w", encoding="utf-8") as f:
    json.dump(orientation_record, f, ensure_ascii=False, indent=2)
print("Day 5 오리엔테이션 기록 저장:", orientation_record_file)
print("존재 여부:", orientation_record_file.exists())

Day 5 오리엔테이션 기록 저장: /home/soldesk/week2-reproducibility/outputs/day5_orientation_record.json
존재 여부: True

In [9]:
print("author:", orientation_record["author"])
print("clean_s3_uri:", orientation_record["s3_inputs"]["clean_s3_uri"])
print("g4dn used:", orientation_record["g4dn_connection"]["used_in_day5"])

author: kim-juil
clean_s3_uri: s3://edu-ai-lake/users/kim-juil/clean/customers/customers_clean_20260606_v2.csv
g4dn used: False

In [10]:
from pathlib import Path
import os
import textwrap

# 현재 실행 위치가 notebook 또는 notebooks 폴더이면 부모 폴더를 프로젝트 루트로 사용
BASE_DIR = Path.cwd().parent if Path.cwd().name in ["notebook", "notebooks"] else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# outputs 폴더 준비
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# 기존 셀에 변수가 있으면 사용하고, 없으면 환경 변수 또는 기본값 사용
AUTHOR = globals().get(
    "AUTHOR",
    globals().get("author", os.environ.get("AUTHOR", "student"))
)

S3_BUCKET = globals().get(
    "S3_BUCKET",
    globals().get("BUCKET", globals().get("bucket_name", os.environ.get("S3_BUCKET", "edu-ai-lake")))
)

# S3 Prefix / Key 기본값
S3_CLEAN_PREFIX = globals().get(
    "S3_CLEAN_PREFIX",
    os.environ.get("S3_CLEAN_PREFIX", f"users/{AUTHOR}/clean/customers/")
)

S3_FEATURE_PREFIX = globals().get(
    "S3_FEATURE_PREFIX",
    os.environ.get("S3_FEATURE_PREFIX", f"users/{AUTHOR}/feature/customers/")
)

S3_LOG_PREFIX = globals().get(
    "S3_LOG_PREFIX",
    os.environ.get("S3_LOG_PREFIX", f"users/{AUTHOR}/log/week2/")
)

S3_ARTIFACT_PREFIX = globals().get(
    "S3_ARTIFACT_PREFIX",
    os.environ.get("S3_ARTIFACT_PREFIX", f"users/{AUTHOR}/artifact/week2/")
)

S3_CLEAN_KEY = globals().get(
    "S3_CLEAN_KEY",
    os.environ.get("S3_CLEAN_KEY", f"{S3_CLEAN_PREFIX}customers_clean_20260606_v2.csv")
)

# 저장 파일
orientation_md_file = OUTPUT_DIR / "day5_orientation_record.md"

# Markdown 내용
orientation_md_text = f"""
# Day 5 오리엔테이션 기록

## 1. 작성자

- author: {AUTHOR}

## 2. Day 5 주제

S3 데이터 로딩 → 전처리 재사용 → feature 생성 → split → baseline 준비

## 3. Day 5 목표

- S3에서 clean 데이터를 가져온다.
- 데이터 구조를 검증한다.
- feature 데이터를 생성한다.
- train / validation / test로 분리한다.
- baseline model을 준비한다.
- metrics와 report를 저장한다.
- 결과물을 S3에 다시 업로드한다.
- 3주차 모델링 수업으로 연결한다.

## 4. 통합 파이프라인 구조

```text
S3 clean 데이터
↓
개인 로컬 PC WSL2 / Notebook
↓
데이터 검증
↓
feature 생성
↓
train / validation / test split
↓
baseline model 준비
↓
metrics / report / run_info 저장
↓
S3 feature / log / artifact 업로드
```

## 5. Day 5 입력 데이터

```text
s3://{S3_BUCKET}/{S3_CLEAN_KEY}
```

## 6. S3 출력 Prefix

| 구분 | Prefix |
|---|---|
| feature | {S3_FEATURE_PREFIX} |
| log | {S3_LOG_PREFIX} |
| artifact | {S3_ARTIFACT_PREFIX} |

## 7. 주의사항

- Day 5의 목표는 최고 성능 모델이 아니다.
- baseline은 기준 성능 확인용이다.
- test 데이터는 최종 평가용으로 아껴야 한다.
- leakage를 항상 점검해야 한다.
- 실행 기록과 산출물을 남겨야 한다.
- 개인 author와 개인 Prefix를 사용한다.
- Day 5에서는 g4dn.xlarge를 사용하지 않는다.
- OpenShift Local에서도 같은 프로젝트 구조와 S3 경로를 사용할 수 있어야 한다.

## 8. OpenShift Local 연결

Day 5 기본 실행은 개인 로컬 PC WSL2에서 진행한다.

다만 같은 프로젝트 구조, 같은 requirements.txt, 같은 .env.example, 같은 src 모듈을 유지해서  
OpenShift Local 환경에서도 동일한 파이프라인을 실행할 수 있도록 준비한다.

OpenShift에서는 S3 경로 정보를 ConfigMap 또는 환경 변수로 주입할 수 있다.

예시:

```text
S3_BUCKET={S3_BUCKET}
S3_CLEAN_KEY={S3_CLEAN_KEY}
S3_FEATURE_PREFIX={S3_FEATURE_PREFIX}
S3_LOG_PREFIX={S3_LOG_PREFIX}
S3_ARTIFACT_PREFIX={S3_ARTIFACT_PREFIX}
```

AWS 인증 정보는 Secret 또는 더 안전한 인증 방식으로 관리한다.

## 9. g4dn.xlarge 연결

Day 5에서는 GPU가 필요하지 않으므로 g4dn.xlarge를 사용하지 않는다.

이후 GPU 실습 주차에서는 Day 5에서 만든 feature, log, artifact 저장 규칙을 그대로 사용한다.

예를 들어 g4dn에서 생성한 모델 파일, 추론 결과, 실행 로그는 다음 Prefix 체계로 저장할 수 있다.

```text
users/{AUTHOR}/artifact/week7/
users/{AUTHOR}/log/week7/
```

## 10. 핵심 메시지

최고 성능 모델을 만드는 것이 아니라,  
모델링으로 넘어갈 수 있는 재현 가능한 데이터 파이프라인을 만드는 것이 목표다.
"""

# 앞뒤 공백 정리 후 저장
orientation_md_text = textwrap.dedent(orientation_md_text).strip() + "\n"

orientation_md_file.write_text(
    orientation_md_text,
    encoding="utf-8"
)

print("Day 5 오리엔테이션 Markdown 저장:", orientation_md_file)
print("존재 여부:", orientation_md_file.exists())
print("상대 경로:", orientation_md_file.relative_to(BASE_DIR))

Day 5 오리엔테이션 Markdown 저장: /home/soldesk/week2-reproducibility/outputs/day5_orientation_record.md
존재 여부: True
상대 경로: outputs/day5_orientation_record.md

In [11]:
from pathlib import Path
import os
import textwrap

# 현재 실행 위치가 notebook 또는 notebooks 폴더이면 부모 폴더를 프로젝트 루트로 사용
BASE_DIR = Path.cwd().parent if Path.cwd().name in ["notebook", "notebooks"] else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# 폴더 준비
REPORT_DIR = BASE_DIR / "reports" / "week2"
OUTPUT_DIR = BASE_DIR / "outputs"

REPORT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# 기존 셀에 변수가 있으면 사용하고, 없으면 환경 변수 또는 기본값 사용
AUTHOR = globals().get(
    "AUTHOR",
    globals().get("author", os.environ.get("AUTHOR", "student"))
)

S3_BUCKET = globals().get(
    "S3_BUCKET",
    globals().get("BUCKET", globals().get("bucket_name", os.environ.get("S3_BUCKET", "edu-ai-lake")))
)

S3_CLEAN_PREFIX = globals().get(
    "S3_CLEAN_PREFIX",
    os.environ.get("S3_CLEAN_PREFIX", f"users/{AUTHOR}/clean/customers/")
)

S3_FEATURE_PREFIX = globals().get(
    "S3_FEATURE_PREFIX",
    os.environ.get("S3_FEATURE_PREFIX", f"users/{AUTHOR}/feature/customers/")
)

S3_LOG_PREFIX = globals().get(
    "S3_LOG_PREFIX",
    os.environ.get("S3_LOG_PREFIX", f"users/{AUTHOR}/log/week2/")
)

S3_ARTIFACT_PREFIX = globals().get(
    "S3_ARTIFACT_PREFIX",
    os.environ.get("S3_ARTIFACT_PREFIX", f"users/{AUTHOR}/artifact/week2/")
)

S3_CLEAN_KEY = globals().get(
    "S3_CLEAN_KEY",
    os.environ.get("S3_CLEAN_KEY", f"{S3_CLEAN_PREFIX}customers_clean_20260606_v2.csv")
)

S3_CLEAN_URI = f"s3://{S3_BUCKET}/{S3_CLEAN_KEY}"

# 저장 파일 경로
period1_record_file = REPORT_DIR / "day5_period1_orientation_record.md"

# Markdown 기록지 내용
period1_record_text = f"""
# 2주차 Day 5 1교시 실습 기록지

## 작성자

- author: {AUTHOR}

## 1. 오늘 주제

S3 데이터 로딩 → 전처리 재사용 → 베이스라인 준비

## 2. Day 1~4 연결

| Day | 내가 만든 것 | Day 5에서 어떻게 쓰는가 |
|---|---|---|
| Day 1 | 데이터 관찰 결과 | 데이터 검증 기준 |
| Day 2 | clean 데이터 | S3에서 다시 읽을 입력 데이터 |
| Day 3 | 재현성 구조 | seed, requirements, .env, src 재사용 |
| Day 4 | S3 운영 구조 | clean 입력, feature/log/artifact 출력 Prefix |

## 3. Day 5 통합 파이프라인

```text
S3 clean 데이터
↓
Notebook
↓
데이터 검증
↓
feature 생성
↓
train / validation / test split
↓
baseline model 준비
↓
metrics / report / run_info 저장
↓
S3 업로드
```

## 4. baseline 의미

- baseline model이란?
  - 복잡한 모델을 만들기 전에 기준점으로 사용하는 가장 기본적인 모델이다.
  - 이후 모델 성능이 좋아졌는지 비교하기 위한 기준 성능을 만든다.

- Day 5에서 최고 성능을 목표로 하지 않는 이유는?
  - Day 5의 핵심은 모델 성능 경쟁이 아니라 재현 가능한 데이터 파이프라인을 만드는 것이다.
  - S3에서 clean 데이터를 읽고, feature를 만들고, split하고, 기록을 남기는 구조가 먼저 필요하다.

## 5. leakage 주의

| 위험 상황 | 왜 위험한가 |
|---|---|
| 전체 데이터로 평균 계산 후 split | test 데이터 정보가 train 과정에 섞일 수 있다. |
| test 데이터 보고 전처리 기준 결정 | 최종 평가용 데이터를 미리 본 것이 되어 성능이 과대평가될 수 있다. |
| churn과 같은 의미의 컬럼 사용 | target 정답을 간접적으로 알려주는 컬럼이 들어갈 수 있다. |
| test 성능 보고 feature 반복 수정 | test 데이터가 검증용처럼 사용되어 최종 평가 의미가 약해진다. |

## 6. 개인 S3 설정

| 항목 | 값 |
|---|---|
| author | {AUTHOR} |
| bucket | {S3_BUCKET} |
| clean S3 URI | {S3_CLEAN_URI} |
| feature Prefix | {S3_FEATURE_PREFIX} |
| log Prefix | {S3_LOG_PREFIX} |
| artifact Prefix | {S3_ARTIFACT_PREFIX} |

## 7. OpenShift Local 연결

- 같은 프로젝트 구조를 OpenShift Local에서도 실행하려면 무엇이 같아야 하는가?
- 같은 `requirements.txt`를 사용해야 한다.
- 같은 `.env.example` 구조를 유지해야 한다.
- 같은 `src` 모듈 구조를 사용해야 한다.
- 같은 S3 Bucket과 Prefix 설정을 환경 변수 또는 ConfigMap으로 주입할 수 있어야 한다.
- AWS 인증 정보는 Secret 또는 더 안전한 인증 방식으로 관리해야 한다.

## 8. g4dn 연결

- Day 5에서 g4dn을 사용하지 않는 이유는?
  - Day 5는 데이터 로딩, feature 생성, split, baseline 준비가 중심이므로 GPU가 필요하지 않다.

- 이후 GPU 실습에서 Day 5 구조가 어떻게 쓰이는가?
  - Day 5에서 만든 feature, log, artifact 저장 규칙을 그대로 사용할 수 있다.
  - 이후 g4dn에서 생성한 모델 파일, 추론 결과, 실행 로그를 S3 artifact/log Prefix에 저장할 수 있다.

## 9. 오늘 생성한 산출물

| 산출물 | 경로 |
|---|---|
| Day 5 Notebook | notebooks/05_s3_to_baseline_pipeline.ipynb |
| 오리엔테이션 JSON | outputs/day5_orientation_record.json |
| 오리엔테이션 Markdown | outputs/day5_orientation_record.md |
| 1교시 개인 실습 기록지 | reports/week2/day5_period1_orientation_record.md |

## 10. 오늘 이해한 점

-

## 11. 다음 교시에서 할 일

S3에서 clean 데이터를 가져오기 + 로컬/OpenShift Local 경로 정리
"""

# 앞뒤 공백 정리 후 저장
period1_record_text = textwrap.dedent(period1_record_text).strip() + "\n"

period1_record_file.write_text(
    period1_record_text,
    encoding="utf-8"
)

print("Day 5 1교시 실습 기록지 저장:", period1_record_file)
print("존재 여부:", period1_record_file.exists())
print("상대 경로:", period1_record_file.relative_to(BASE_DIR))

Day 5 1교시 실습 기록지 저장: /home/soldesk/week2-reproducibility/reports/week2/day5_period1_orientation_record.md
존재 여부: True
상대 경로: reports/week2/day5_period1_orientation_record.md

In [12]:
from pathlib import Path
import os
from dotenv import load_dotenv
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
env_path = BASE_DIR / ".env"
load_dotenv(env_path)
AUTHOR = os.getenv("AUTHOR", "student")
SEED = int(os.getenv("SEED", "42"))
AWS_REGION = os.getenv("AWS_REGION", "ap-northeast-2")
S3_BUCKET = os.getenv("S3_BUCKET", "edu-ai-lake")
S3_CLEAN_KEY = os.getenv(
    "S3_CLEAN_KEY",
    f"users/{AUTHOR}/clean/customers/customers_clean_20260606_v2.csv"
)
S3_FEATURE_PREFIX = os.getenv("S3_FEATURE_PREFIX", f"users/{AUTHOR}/feature/customers/")
S3_LOG_PREFIX = os.getenv("S3_LOG_PREFIX", f"users/{AUTHOR}/log/week2/")
S3_ARTIFACT_PREFIX = os.getenv("S3_ARTIFACT_PREFIX", f"users/{AUTHOR}/artifact/week2/")
LOCAL_CLEAN_FILE_RAW = os.getenv(
    "LOCAL_CLEAN_FILE",
    "data/clean/customers_clean_20260606_v2.csv"
)
LOCAL_CLEAN_FILE = BASE_DIR / LOCAL_CLEAN_FILE_RAW
print("BASE_DIR:", BASE_DIR)
print("AUTHOR:", AUTHOR)
print("SEED:", SEED)
print("AWS_REGION:", AWS_REGION)
print("S3_BUCKET:", S3_BUCKET)
print("S3_CLEAN_KEY:", S3_CLEAN_KEY)
print("LOCAL_CLEAN_FILE:", LOCAL_CLEAN_FILE)

BASE_DIR: /home/soldesk/week2-reproducibility
AUTHOR: kim-juil
SEED: 42
AWS_REGION: ap-northeast-2
S3_BUCKET: edu-ai-lake
S3_CLEAN_KEY: users/kim-juil/clean/customers/customers_clean_20260606_v2.csv
LOCAL_CLEAN_FILE: /home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv

In [13]:
DATA_DIR = BASE_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
CLEAN_DIR = DATA_DIR / "clean"
FEATURE_DIR = DATA_DIR / "feature"
OUTPUT_DIR = BASE_DIR / "outputs"
SRC_DIR = BASE_DIR / "src"
REPORT_DIR = BASE_DIR / "reports" / "week2"
for directory in [RAW_DIR, CLEAN_DIR, FEATURE_DIR, OUTPUT_DIR, SRC_DIR, REPORT_DIR]:
    directory.mkdir(parents=True, exist_ok=True)
    print(directory.relative_to(BASE_DIR), ":", directory.exists())

data/raw : True
data/clean : True
data/feature : True
outputs : True
src : True
reports/week2 : True

In [14]:
import pandas as pd
df_clean = pd.read_csv(LOCAL_CLEAN_FILE)
print("파일 경로:", LOCAL_CLEAN_FILE)
print("shape:", df_clean.shape)
print("columns:", list(df_clean.columns))
df_clean.head()

파일 경로: /home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv
shape: (9, 29)
columns: ['customer_id', 'age', 'monthly_fee', 'usage_days', 'support_calls', 'gender_standard', 'contract_type_standard', 'signup_date', 'last_login_date', 'signup_year', 'signup_month', 'last_login_dayofweek', 'last_login_day_name', 'days_since_signup', 'days_since_last_login', 'age_was_missing', 'monthly_fee_was_missing', 'gender_was_missing', 'contract_type_was_missing', 'monthly_fee_outlier', 'support_calls_outlier', 'is_high_fee', 'is_short_user', 'has_many_support_calls', 'usage_group', 'is_long_contract', 'churn', 'gender', 'contract_type']

,customer_id,age,monthly_fee,usage_days,support_calls,gender_standard,contract_type_standard,signup_date,last_login_date,signup_year,...,monthly_fee_outlier,support_calls_outlier,is_high_fee,is_short_user,has_many_support_calls,usage_group,is_long_contract,churn,gender,contract_type
0,C001,34,59000,120,1,female,monthly,2025-01-10,2026-06-01,2025,...,0,0,1,0,0,middle,0,0,female,month-to-month
1,C002,45,79000,380,3,male,one_year,2024-12-01,2026-05-10,2024,...,0,0,1,0,1,long,1,1,male,1-year
2,C003,41,72000,45,0,female,monthly,2026-04-20,2026-06-03,2026,...,0,0,1,0,0,middle,0,0,female,month-to-month
3,C004,52,99000,800,5,male,one_year,2023-05-15,2026-03-01,2023,...,0,0,1,0,1,long,1,1,male,1-year
4,C005,41,69000,220,2,female,unknown,2025-08-03,2026-05-30,2025,...,0,0,1,0,0,middle,0,0,female,unknown

In [15]:
print("row count:", len(df_clean))
print("column count:", len(df_clean.columns))
print("dtypes:")
print(df_clean.dtypes)

row count: 9
column count: 29
dtypes:
customer_id                    str
age                          int64
monthly_fee                  int64
usage_days                   int64
support_calls                int64
gender_standard                str
contract_type_standard         str
signup_date                    str
last_login_date                str
signup_year                  int64
signup_month                 int64
last_login_dayofweek         int64
last_login_day_name            str
days_since_signup            int64
days_since_last_login        int64
age_was_missing              int64
monthly_fee_was_missing      int64
gender_was_missing           int64
contract_type_was_missing    int64
monthly_fee_outlier          int64
support_calls_outlier        int64
is_high_fee                  int64
is_short_user                int64
has_many_support_calls       int64
usage_group                    str
is_long_contract             int64
churn                        int64
gender                         str
contract_type                  str
dtype: object

In [16]:
import sys
if str(BASE_DIR) not in sys.path:
    sys.path.append(str(BASE_DIR))
from src.s3_utils import build_s3_uri, head_s3_object, download_s3_object
s3_clean_uri = build_s3_uri(S3_BUCKET, S3_CLEAN_KEY)
print("s3_clean_uri:", s3_clean_uri)

s3_clean_uri: s3://edu-ai-lake/users/kim-juil/clean/customers/customers_clean_20260606_v2.csv

In [17]:
s3_head = head_s3_object(S3_BUCKET, S3_CLEAN_KEY)
s3_head

{'success': True,
 'bucket': 'edu-ai-lake',
 'key': 'users/kim-juil/clean/customers/customers_clean_20260606_v2.csv',
 's3_uri': 's3://edu-ai-lake/users/kim-juil/clean/customers/customers_clean_20260606_v2.csv',
 'content_length': 1595,
 'content_type': 'text/csv',
 'last_modified': '2026-06-29T04:19:57+00:00',
 'etag': '"0d29a76d0603693b2515387e7a4a7f15"',
 'method': 'boto3.head_object',
 'checked_at': '2026-06-30T13:07:01+09:00'}

In [18]:
boto3_download_path = CLEAN_DIR / "customers_clean_20260606_v2_boto3.csv"
download_result = download_s3_object(
    bucket=S3_BUCKET,
    key=S3_CLEAN_KEY,
    local_path=boto3_download_path
)
download_result

{'success': True,
 'bucket': 'edu-ai-lake',
 'key': 'users/kim-juil/clean/customers/customers_clean_20260606_v2.csv',
 's3_uri': 's3://edu-ai-lake/users/kim-juil/clean/customers/customers_clean_20260606_v2.csv',
 'local_path': '/home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2_boto3.csv',
 'local_exists': True,
 'local_size_bytes': 1595,
 'started_at': '2026-06-30T13:07:02+09:00',
 'finished_at': '2026-06-30T13:07:02+09:00',
 'method': 'boto3.download_file'}

In [19]:
df_clean_boto3 = pd.read_csv(boto3_download_path)
print("shape:", df_clean_boto3.shape)
print("columns:", list(df_clean_boto3.columns))
df_clean_boto3.head()

shape: (9, 29)
columns: ['customer_id', 'age', 'monthly_fee', 'usage_days', 'support_calls', 'gender_standard', 'contract_type_standard', 'signup_date', 'last_login_date', 'signup_year', 'signup_month', 'last_login_dayofweek', 'last_login_day_name', 'days_since_signup', 'days_since_last_login', 'age_was_missing', 'monthly_fee_was_missing', 'gender_was_missing', 'contract_type_was_missing', 'monthly_fee_outlier', 'support_calls_outlier', 'is_high_fee', 'is_short_user', 'has_many_support_calls', 'usage_group', 'is_long_contract', 'churn', 'gender', 'contract_type']

,customer_id,age,monthly_fee,usage_days,support_calls,gender_standard,contract_type_standard,signup_date,last_login_date,signup_year,...,monthly_fee_outlier,support_calls_outlier,is_high_fee,is_short_user,has_many_support_calls,usage_group,is_long_contract,churn,gender,contract_type
0,C001,34,59000,120,1,female,monthly,2025-01-10,2026-06-01,2025,...,0,0,1,0,0,middle,0,0,female,month-to-month
1,C002,45,79000,380,3,male,one_year,2024-12-01,2026-05-10,2024,...,0,0,1,0,1,long,1,1,male,1-year
2,C003,41,72000,45,0,female,monthly,2026-04-20,2026-06-03,2026,...,0,0,1,0,0,middle,0,0,female,month-to-month
3,C004,52,99000,800,5,male,one_year,2023-05-15,2026-03-01,2023,...,0,0,1,0,1,long,1,1,male,1-year
4,C005,41,69000,220,2,female,unknown,2025-08-03,2026-05-30,2025,...,0,0,1,0,0,middle,0,0,female,unknown

In [20]:
df_clean_cli = pd.read_csv(LOCAL_CLEAN_FILE)
print("CLI shape:", df_clean_cli.shape)
print("boto3 shape:", df_clean_boto3.shape)
print("same columns:", list(df_clean_cli.columns) == list(df_clean_boto3.columns))

CLI shape: (9, 29)
boto3 shape: (9, 29)
same columns: True

In [21]:
from datetime import datetime
import json
import platform
import sys
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
download_record = {
    "day": "week2_day5",
    "lesson": "period2_s3_download_and_path_setup",
    "author": AUTHOR,
    "created_at": datetime.now().isoformat(),
    "execution_environment": {
        "main": "local_pc_wsl2",
        "python_version": sys.version,
        "platform": platform.platform(),
        "openshift_local_used": False,
        "openshift_local_connection": "same project structure, same .env.example, same src modules",
        "g4dn_used": False,
        "g4dn_not_used_reason": "S3 download and pandas data loading do not require GPU"
    },
    "s3_source": {
        "bucket": S3_BUCKET,
        "key": S3_CLEAN_KEY,
        "s3_uri": build_s3_uri(S3_BUCKET, S3_CLEAN_KEY),
        "stage": "clean",
        "data_name": "customers",
        "version": "20260606_v2"
    },
    "local_destination": {
        "local_path": str(LOCAL_CLEAN_FILE.relative_to(BASE_DIR)),
        "absolute_path": str(LOCAL_CLEAN_FILE),
        "exists": LOCAL_CLEAN_FILE.exists(),
        "size_bytes": LOCAL_CLEAN_FILE.stat().st_size if LOCAL_CLEAN_FILE.exists() else None
    },
    "s3_metadata": s3_head,
    "read_test": {
        "pandas_read_csv_success": True,
        "shape": list(df_clean.shape),
        "columns": list(df_clean.columns)
    },
    "download_methods": {
        "aws_cli": "aws s3 cp",
        "boto3": "boto3.client('s3').download_file"
    },
    "next_lesson": "data validation and preprocessing logic reuse"
}
s3_download_record_file = OUTPUT_DIR / "s3_download_record.json"
with open(s3_download_record_file, "w", encoding="utf-8") as f:
    json.dump(download_record, f, ensure_ascii=False, indent=2)
print("S3 다운로드 기록 JSON 저장:", s3_download_record_file)
print("존재 여부:", s3_download_record_file.exists())

S3 다운로드 기록 JSON 저장: /home/soldesk/week2-reproducibility/outputs/s3_download_record.json
존재 여부: True

In [22]:
print("author:", download_record["author"])
print("s3_uri:", download_record["s3_source"]["s3_uri"])
print("local_path:", download_record["local_destination"]["local_path"])
print("shape:", download_record["read_test"]["shape"])

author: kim-juil
s3_uri: s3://edu-ai-lake/users/kim-juil/clean/customers/customers_clean_20260606_v2.csv
local_path: data/clean/customers_clean_20260606_v2.csv
shape: [9, 29]

In [23]:
s3_download_record_md_file = OUTPUT_DIR / "s3_download_record.md"
s3_download_record_md = f"""# Day 5 2교시 S3 다운로드 기록
## 1. 작성자
- author: {AUTHOR}
## 2. 오늘 주제
S3에서 clean 데이터 가져오기 + 로컬/OpenShift Local 경로 정리
## 3. S3 입력 데이터
| 항목 | 값 |
|---|---|
| bucket | {S3_BUCKET} |
| key | {S3_CLEAN_KEY} |
| S3 URI | {build_s3_uri(S3_BUCKET, S3_CLEAN_KEY)} |
| 데이터 상태 | clean |
| 데이터셋 | customers |
| 버전 | 20260606_v2 |
## 4. 로컬 저장 경로
| 항목 | 값 |
|---|---|
| 로컬 상대 경로 | {LOCAL_CLEAN_FILE.relative_to(BASE_DIR)} |
| 로컬 절대 경로 | {LOCAL_CLEAN_FILE} |
| 파일 존재 여부 | {LOCAL_CLEAN_FILE.exists()} |
| 파일 크기 bytes | {LOCAL_CLEAN_FILE.stat().st_size if LOCAL_CLEAN_FILE.exists() else None} |
## 5. 다운로드 방식
| 방식 | 설명 |
|---|---|
| AWS CLI | `aws s3 cp` 명령으로 다운로드 |
| boto3 | `boto3.client("s3").download_file()` 함수로 다운로드 |
## 6. pandas 읽기 확인
| 항목 | 값 |
|---|---|
| read_csv 성공 | True |
| shape | {list(df_clean.shape)} |
| columns | {list(df_clean.columns)} |
## 7. OpenShift Local 연결
이번 교시에서는 OpenShift Local에 앱을 배포하지 않았다.
하지만 같은 프로젝트 구조,
같은 `.env.example`,
같은 `src/s3_utils.py`,
같은 S3 clean key를 사용하면
OpenShift Local 환경에서도 동일한 방식으로 데이터를 가져올 수 있다.
## 8. g4dn.xlarge 연결
이번 교시에서는 g4dn.xlarge를 사용하지 않았다.
S3 다운로드와 pandas 데이터 읽기에는 GPU가 필요하지 않다.
이후 GPU 실습 주차에서는 Day 5에서 만든 feature/log/artifact 구조를 그대로 사용한다.
## 9. 다음 교시 연결
3교시에서는 내려받은 clean 데이터를 바로 모델링하지 않고,
컬럼, 타입, 결측치, target, row 수를 먼저 검증한다.
"""
s3_download_record_md_file.write_text(s3_download_record_md, encoding="utf-8")
print("S3 다운로드 기록 Markdown 저장:", s3_download_record_md_file)
print("존재 여부:", s3_download_record_md_file.exists())

S3 다운로드 기록 Markdown 저장: /home/soldesk/week2-reproducibility/outputs/s3_download_record.md
존재 여부: True

In [24]:
from pathlib import Path
import os
import textwrap

# 현재 실행 위치가 notebook 또는 notebooks 폴더이면 부모 폴더를 프로젝트 루트로 사용
BASE_DIR = Path.cwd().parent if Path.cwd().name in ["notebook", "notebooks"] else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# 폴더 준비
REPORT_DIR = BASE_DIR / "reports" / "week2"
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# 기존 Notebook 변수 또는 환경 변수 사용
AUTHOR = globals().get(
    "AUTHOR",
    globals().get("author", os.environ.get("AUTHOR", "student"))
)

AWS_REGION = globals().get(
    "AWS_REGION",
    os.environ.get("AWS_REGION", "ap-northeast-2")
)

S3_BUCKET = globals().get(
    "S3_BUCKET",
    globals().get("BUCKET", globals().get("bucket_name", os.environ.get("S3_BUCKET", "edu-ai-lake")))
)

S3_CLEAN_PREFIX = globals().get(
    "S3_CLEAN_PREFIX",
    os.environ.get("S3_CLEAN_PREFIX", f"users/{AUTHOR}/clean/customers/")
)

S3_CLEAN_KEY = globals().get(
    "S3_CLEAN_KEY",
    os.environ.get("S3_CLEAN_KEY", f"{S3_CLEAN_PREFIX}customers_clean_20260606_v2.csv")
)

LOCAL_CLEAN_FILE = globals().get(
    "LOCAL_CLEAN_FILE",
    os.environ.get("LOCAL_CLEAN_FILE", "data/clean/customers_clean_20260606_v2.csv")
)

S3_CLEAN_URI = f"s3://{S3_BUCKET}/{S3_CLEAN_KEY}"

# 저장 파일
period2_record_file = REPORT_DIR / "day5_period2_s3_download_record.md"

# Markdown 기록 양식
period2_record_text = f"""
# 2주차 Day 5 2교시 실습 기록지

## 작성자

- author: {AUTHOR}

## 1. 오늘 주제

S3에서 데이터 가져오기 + 로컬/OpenShift Local 경로 정리

## 2. S3 URI 구조

- bucket: {S3_BUCKET}
- key: {S3_CLEAN_KEY}
- S3 URI: {S3_CLEAN_URI}

## 3. 개인 설정

| 항목 | 값 |
|---|---|
| AUTHOR | {AUTHOR} |
| AWS_REGION | {AWS_REGION} |
| S3_BUCKET | {S3_BUCKET} |
| S3_CLEAN_KEY | {S3_CLEAN_KEY} |
| LOCAL_CLEAN_FILE | {LOCAL_CLEAN_FILE} |

## 4. 다운로드 전 확인

| 항목 | 결과 |
|---|---|
| AWS CLI 설치 확인 | 확인 필요 |
| AWS 인증 확인 | 확인 필요 |
| S3 객체 존재 확인 | 확인 필요 |
| 로컬 data/clean 폴더 확인 | 확인 필요 |

## 5. 다운로드 방식

| 방식 | 실행 여부 | 결과 |
|---|---|---|
| AWS CLI `aws s3 cp` | 확인 필요 | 확인 필요 |
| boto3 download_file | 확인 필요 | 확인 필요 |

## 6. pandas 읽기 확인

| 항목 | 값 |
|---|---|
| read_csv 성공 여부 | 확인 필요 |
| row 수 | 확인 필요 |
| column 수 | 확인 필요 |
| 주요 columns | 확인 필요 |

## 7. 생성한 산출물

| 산출물 | 경로 |
|---|---|
| clean 데이터 | data/clean/customers_clean_20260606_v2.csv |
| S3 다운로드 기록 JSON | outputs/s3_download_record.json |
| S3 다운로드 기록 Markdown | outputs/s3_download_record.md |
| S3 유틸 모듈 | src/s3_utils.py |

## 8. OpenShift Local 연결

- OpenShift Local에서 같은 코드를 실행하려면 어떤 설정이 같아야 하는가?
- 같은 프로젝트 폴더 구조를 사용해야 한다.
- 같은 `requirements.txt`를 사용해야 한다.
- 같은 `.env.example` 구조를 유지해야 한다.
- `S3_BUCKET`, `S3_CLEAN_KEY`, `LOCAL_CLEAN_FILE` 같은 설정값을 환경 변수 또는 ConfigMap으로 주입할 수 있어야 한다.
- AWS 인증 정보는 코드에 직접 작성하지 않고 Secret 또는 환경 변수로 관리해야 한다.
- 로컬 절대경로를 하드코딩하지 않고 `Path` 기반 상대경로를 사용해야 한다.

## 9. g4dn 연결

- 이번 교시에서 g4dn을 사용하지 않는 이유는?
  - 이번 교시는 S3 clean 데이터 다운로드와 로컬 경로 정리가 중심이므로 GPU가 필요하지 않다.
  - pandas 기반 CSV 읽기와 데이터 확인은 CPU 환경에서 충분히 수행할 수 있다.

- 이후 GPU 실습에서 S3 다운로드 구조가 어떻게 사용될 수 있는가?
  - g4dn GPU 서버에서도 같은 S3 Bucket과 Key를 사용해 학습 데이터를 다운로드할 수 있다.
  - g4dn에서 생성한 모델 파일은 artifact Prefix에 저장할 수 있다.
  - g4dn에서 생성한 실행 로그는 log Prefix에 저장할 수 있다.
  - Day 5에서 만든 S3 다운로드 구조는 이후 GPU 모델 학습 서버에서도 재사용할 수 있다.

## 10. 오늘 이해한 점

-

## 11. 다음 교시에서 할 일

데이터 검증 + 전처리 로직 재사용
"""

# 앞뒤 공백 정리 후 저장
period2_record_text = textwrap.dedent(period2_record_text).strip() + "\n"

period2_record_file.write_text(
    period2_record_text,
    encoding="utf-8"
)

print("Day 5 2교시 실습 기록지 저장:", period2_record_file)
print("존재 여부:", period2_record_file.exists())
print("상대 경로:", period2_record_file.relative_to(BASE_DIR))

Day 5 2교시 실습 기록지 저장: /home/soldesk/week2-reproducibility/reports/week2/day5_period2_s3_download_record.md
존재 여부: True
상대 경로: reports/week2/day5_period2_s3_download_record.md

In [25]:
from pathlib import Path
import os
import sys
import json
from datetime import datetime
import pandas as pd
import numpy as np
from dotenv import load_dotenv
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
if str(BASE_DIR) not in sys.path:
    sys.path.append(str(BASE_DIR))
env_path = BASE_DIR / ".env"
load_dotenv(env_path)
AUTHOR = os.getenv("AUTHOR", "student")
SEED = int(os.getenv("SEED", "42"))
LOCAL_CLEAN_FILE_RAW = os.getenv(
    "LOCAL_CLEAN_FILE",
    "data/clean/customers_clean_20260606_v2.csv"
)
LOCAL_CLEAN_FILE = BASE_DIR / LOCAL_CLEAN_FILE_RAW
print("BASE_DIR:", BASE_DIR)
print("AUTHOR:", AUTHOR)
print("LOCAL_CLEAN_FILE:", LOCAL_CLEAN_FILE)
print("exists:", LOCAL_CLEAN_FILE.exists())

BASE_DIR: /home/soldesk/week2-reproducibility
AUTHOR: kim-juil
LOCAL_CLEAN_FILE: /home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv
exists: True

In [26]:
if not LOCAL_CLEAN_FILE.exists():
    raise FileNotFoundError(f"clean 데이터 파일이 없습니다: {LOCAL_CLEAN_FILE}")
df_clean = pd.read_csv(LOCAL_CLEAN_FILE)
print("shape:", df_clean.shape)
print("columns:", list(df_clean.columns))
df_clean.head()

shape: (9, 29)
columns: ['customer_id', 'age', 'monthly_fee', 'usage_days', 'support_calls', 'gender_standard', 'contract_type_standard', 'signup_date', 'last_login_date', 'signup_year', 'signup_month', 'last_login_dayofweek', 'last_login_day_name', 'days_since_signup', 'days_since_last_login', 'age_was_missing', 'monthly_fee_was_missing', 'gender_was_missing', 'contract_type_was_missing', 'monthly_fee_outlier', 'support_calls_outlier', 'is_high_fee', 'is_short_user', 'has_many_support_calls', 'usage_group', 'is_long_contract', 'churn', 'gender', 'contract_type']

,customer_id,age,monthly_fee,usage_days,support_calls,gender_standard,contract_type_standard,signup_date,last_login_date,signup_year,...,monthly_fee_outlier,support_calls_outlier,is_high_fee,is_short_user,has_many_support_calls,usage_group,is_long_contract,churn,gender,contract_type
0,C001,34,59000,120,1,female,monthly,2025-01-10,2026-06-01,2025,...,0,0,1,0,0,middle,0,0,female,month-to-month
1,C002,45,79000,380,3,male,one_year,2024-12-01,2026-05-10,2024,...,0,0,1,0,1,long,1,1,male,1-year
2,C003,41,72000,45,0,female,monthly,2026-04-20,2026-06-03,2026,...,0,0,1,0,0,middle,0,0,female,month-to-month
3,C004,52,99000,800,5,male,one_year,2023-05-15,2026-03-01,2023,...,0,0,1,0,1,long,1,1,male,1-year
4,C005,41,69000,220,2,female,unknown,2025-08-03,2026-05-30,2025,...,0,0,1,0,0,middle,0,0,female,unknown

In [27]:
row_count = len(df_clean)
column_count = len(df_clean.columns)
print("row_count:", row_count)
print("column_count:", column_count)

row_count: 9
column_count: 29

In [28]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_id                9 non-null      str
 1   age                        9 non-null      int64
 2   monthly_fee                9 non-null      int64
 3   usage_days                 9 non-null      int64
 4   support_calls              9 non-null      int64
 5   gender_standard            9 non-null      str
 6   contract_type_standard     9 non-null      str
 7   signup_date                9 non-null      str
 8   last_login_date            9 non-null      str
 9   signup_year                9 non-null      int64
 10  signup_month               9 non-null      int64
 11  last_login_dayofweek       9 non-null      int64
 12  last_login_day_name        9 non-null      str
 13  days_since_signup          9 non-null      int64
 14  days_since_last_login      9 non-null      int64
 15  age_was_missing            9 non-null      int64
 16  monthly_fee_was_missing    9 non-null      int64
 17  gender_was_missing         9 non-null      int64
 18  contract_type_was_missing  9 non-null      int64
 19  monthly_fee_outlier        9 non-null      int64
 20  support_calls_outlier      9 non-null      int64
 21  is_high_fee                9 non-null      int64
 22  is_short_user              9 non-null      int64
 23  has_many_support_calls     9 non-null      int64
 24  usage_group                9 non-null      str
 25  is_long_contract           9 non-null      int64
 26  churn                      9 non-null      int64
 27  gender                     9 non-null      str
 28  contract_type              9 non-null      str
dtypes: int64(20), str(9)
memory usage: 2.7 KB

In [29]:
expected_columns = [
    "customer_id",
    "age",
    "gender_standard",
    "contract_type_standard",
    "monthly_fee",
    "total_usage_minutes",
    "support_calls",
    "usage_days",
    "signup_date",
    "last_login_date",
    "is_high_fee",
    "is_short_user",
    "has_many_support_calls",
    "usage_group",
    "is_long_contract",
    "churn"
]
actual_columns = list(df_clean.columns)
print("expected_columns:")
print(expected_columns)
print("actual_columns:")
print(actual_columns)

expected_columns:
['customer_id', 'age', 'gender_standard', 'contract_type_standard', 'monthly_fee', 'total_usage_minutes', 'support_calls', 'usage_days', 'signup_date', 'last_login_date', 'is_high_fee', 'is_short_user', 'has_many_support_calls', 'usage_group', 'is_long_contract', 'churn']
actual_columns:
['customer_id', 'age', 'monthly_fee', 'usage_days', 'support_calls', 'gender_standard', 'contract_type_standard', 'signup_date', 'last_login_date', 'signup_year', 'signup_month', 'last_login_dayofweek', 'last_login_day_name', 'days_since_signup', 'days_since_last_login', 'age_was_missing', 'monthly_fee_was_missing', 'gender_was_missing', 'contract_type_was_missing', 'monthly_fee_outlier', 'support_calls_outlier', 'is_high_fee', 'is_short_user', 'has_many_support_calls', 'usage_group', 'is_long_contract', 'churn', 'gender', 'contract_type']

In [30]:
expected_set = set(expected_columns)
actual_set = set(actual_columns)
missing_columns = sorted(list(expected_set - actual_set))
extra_columns = sorted(list(actual_set - expected_set))
print("missing_columns:", missing_columns)
print("extra_columns:", extra_columns)

missing_columns: ['total_usage_minutes']
extra_columns: ['age_was_missing', 'contract_type', 'contract_type_was_missing', 'days_since_last_login', 'days_since_signup', 'gender', 'gender_was_missing', 'last_login_day_name', 'last_login_dayofweek', 'monthly_fee_outlier', 'monthly_fee_was_missing', 'signup_month', 'signup_year', 'support_calls_outlier']

In [31]:
has_required_columns = len(missing_columns) == 0
print("has_required_columns:", has_required_columns)

has_required_columns: False

In [32]:
expected_columns = [
    "customer_id",
    "age",
    "gender",
    "contract_type",
    "monthly_fee",
    "usage_days",
    "support_calls",
    "usage_days",
    "churn"
]

In [33]:
expected_set = set(expected_columns)
actual_set = set(actual_columns)
missing_columns = sorted(list(expected_set - actual_set))
extra_columns = sorted(list(actual_set - expected_set))
print("missing_columns:", missing_columns)
print("extra_columns:", extra_columns)

missing_columns: []
extra_columns: ['age_was_missing', 'contract_type_standard', 'contract_type_was_missing', 'days_since_last_login', 'days_since_signup', 'gender_standard', 'gender_was_missing', 'has_many_support_calls', 'is_high_fee', 'is_long_contract', 'is_short_user', 'last_login_date', 'last_login_day_name', 'last_login_dayofweek', 'monthly_fee_outlier', 'monthly_fee_was_missing', 'signup_date', 'signup_month', 'signup_year', 'support_calls_outlier', 'usage_group']

In [34]:
expected_columns = [
    "customer_id",
    "age",
    "gender",
    "contract_type",
    "monthly_fee",
    "support_calls",
    "usage_days",
    "churn"
]

In [35]:
expected_set = set(expected_columns)
actual_set = set(actual_columns)
missing_columns = sorted(list(expected_set - actual_set))
extra_columns = sorted(list(actual_set - expected_set))
print("missing_columns:", missing_columns)
print("extra_columns:", extra_columns)

missing_columns: []
extra_columns: ['age_was_missing', 'contract_type_standard', 'contract_type_was_missing', 'days_since_last_login', 'days_since_signup', 'gender_standard', 'gender_was_missing', 'has_many_support_calls', 'is_high_fee', 'is_long_contract', 'is_short_user', 'last_login_date', 'last_login_day_name', 'last_login_dayofweek', 'monthly_fee_outlier', 'monthly_fee_was_missing', 'signup_date', 'signup_month', 'signup_year', 'support_calls_outlier', 'usage_group']

In [36]:
has_required_columns = len(missing_columns) == 0
print("has_required_columns:", has_required_columns)

has_required_columns: True

In [37]:
missing_count = df_clean.isna().sum().sort_values(ascending=False)
missing_count

customer_id                  0
age                          0
monthly_fee                  0
usage_days                   0
support_calls                0
gender_standard              0
contract_type_standard       0
signup_date                  0
last_login_date              0
signup_year                  0
signup_month                 0
last_login_dayofweek         0
last_login_day_name          0
days_since_signup            0
days_since_last_login        0
age_was_missing              0
monthly_fee_was_missing      0
gender_was_missing           0
contract_type_was_missing    0
monthly_fee_outlier          0
support_calls_outlier        0
is_high_fee                  0
is_short_user                0
has_many_support_calls       0
usage_group                  0
is_long_contract             0
churn                        0
gender                       0
contract_type                0
dtype: int64

In [38]:
missing_count_nonzero = missing_count[missing_count > 0]
missing_count_nonzero

Series([], dtype: int64)

In [39]:
missing_ratio = (df_clean.isna().mean() * 100).sort_values(ascending=False)
missing_ratio_nonzero = missing_ratio[missing_ratio > 0]
missing_ratio_nonzero

Series([], dtype: float64)

In [40]:
missing_summary = pd.DataFrame({
    "missing_count": missing_count,
    "missing_ratio_percent": missing_ratio.round(2)
})
missing_summary = missing_summary[missing_summary["missing_count"] > 0]
missing_summary

Empty DataFrame
Columns: [missing_count, missing_ratio_percent]
Index: []

In [41]:
if missing_summary.empty:
    print("결측치가 남아 있는 컬럼이 없습니다.")
else:
    print("결측치가 남아 있는 컬럼이 있습니다.")
    display(missing_summary)

결측치가 남아 있는 컬럼이 없습니다.

In [42]:
dtype_summary = df_clean.dtypes.astype(str).sort_index()
dtype_summary

age                          int64
age_was_missing              int64
churn                        int64
contract_type                  str
contract_type_standard         str
contract_type_was_missing    int64
customer_id                    str
days_since_last_login        int64
days_since_signup            int64
gender                         str
gender_standard                str
gender_was_missing           int64
has_many_support_calls       int64
is_high_fee                  int64
is_long_contract             int64
is_short_user                int64
last_login_date                str
last_login_day_name            str
last_login_dayofweek         int64
monthly_fee                  int64
monthly_fee_outlier          int64
monthly_fee_was_missing      int64
signup_date                    str
signup_month                 int64
signup_year                  int64
support_calls                int64
support_calls_outlier        int64
usage_days                   int64
usage_group                    str
dtype: str

In [43]:
numeric_columns = df_clean.select_dtypes(include=["number"]).columns.tolist()
object_columns = df_clean.select_dtypes(include=["object"]).columns.tolist()
bool_columns = df_clean.select_dtypes(include=["bool"]).columns.tolist()
print("numeric_columns:", numeric_columns)
print("object_columns:", object_columns)
print("bool_columns:", bool_columns)

numeric_columns: ['age', 'monthly_fee', 'usage_days', 'support_calls', 'signup_year', 'signup_month', 'last_login_dayofweek', 'days_since_signup', 'days_since_last_login', 'age_was_missing', 'monthly_fee_was_missing', 'gender_was_missing', 'contract_type_was_missing', 'monthly_fee_outlier', 'support_calls_outlier', 'is_high_fee', 'is_short_user', 'has_many_support_calls', 'is_long_contract', 'churn']
object_columns: ['customer_id', 'gender_standard', 'contract_type_standard', 'signup_date', 'last_login_date', 'last_login_day_name', 'usage_group', 'gender', 'contract_type']
bool_columns: []

/tmp/ipykernel_1480/3410859693.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_columns = df_clean.select_dtypes(include=["object"]).columns.tolist()

In [44]:
date_candidate_columns = [
    col for col in df_clean.columns
    if "date" in col.lower() or "dt" in col.lower() or "time" in col.lower()
]
date_candidate_columns

['signup_date', 'last_login_date']

In [45]:
id_candidate_columns = [
    col for col in df_clean.columns
    if col.lower().endswith("_id") or col.lower() in ["id", "customer_id", "user_id"]
]
id_candidate_columns

['customer_id']

In [46]:
TARGET_COLUMN = "churn"
target_exists = TARGET_COLUMN in df_clean.columns
print("TARGET_COLUMN:", TARGET_COLUMN)
print("target_exists:", target_exists)

TARGET_COLUMN: churn
target_exists: True

In [47]:
if not target_exists:
    raise ValueError(f"target 컬럼이 없습니다: {TARGET_COLUMN}")

In [48]:
target_distribution_count = df_clean[TARGET_COLUMN].value_counts(dropna=False)
target_distribution_ratio = df_clean[TARGET_COLUMN].value_counts(normalize=True, dropna=False).round(4)
print("target count:")
print(target_distribution_count)
print("target ratio:")
print(target_distribution_ratio)

target count:
churn
0    5
1    4
Name: count, dtype: int64
target ratio:
churn
0    0.5556
1    0.4444
Name: proportion, dtype: float64

In [49]:
target_summary = pd.DataFrame({
    "count": target_distribution_count,
    "ratio": target_distribution_ratio
})
target_summary

       count   ratio
churn
0          5  0.5556
1          4  0.4444

In [50]:
target_missing_count = df_clean[TARGET_COLUMN].isna().sum()
target_missing_ratio = df_clean[TARGET_COLUMN].isna().mean() * 100
print("target_missing_count:", target_missing_count)
print("target_missing_ratio:", round(target_missing_ratio, 2))

target_missing_count: 0
target_missing_ratio: 0.0

In [51]:
leakage_keywords = [
    "churn",
    "label",
    "target",
    "result",
    "outcome",
    "after",
    "future",
    "next",
    "retention_result"
]
possible_leakage_columns = []
for col in df_clean.columns:
    col_lower = col.lower()
    if col == TARGET_COLUMN:
        continue
    if any(keyword in col_lower for keyword in leakage_keywords):
        possible_leakage_columns.append(col)
possible_leakage_columns

[]

In [52]:
candidate_exclude_columns = sorted(
    set([TARGET_COLUMN] + id_candidate_columns + possible_leakage_columns)
)
candidate_exclude_columns

['churn', 'customer_id']

In [53]:
validation_flags = {
    "file_exists": LOCAL_CLEAN_FILE.exists(),
    "pandas_read_success": True,
    "row_count_positive": row_count > 0,
    "column_count_positive": column_count > 0,
    "has_required_columns": has_required_columns,
    "target_exists": target_exists,
    "target_has_no_missing": target_missing_count == 0,
    "target_has_at_least_two_classes": df_clean[TARGET_COLUMN].nunique(dropna=True) >= 2,
    "no_missing_columns_from_expected": len(missing_columns) == 0,
    "possible_leakage_columns_count": len(possible_leakage_columns)
}
validation_flags

{'file_exists': True,
 'pandas_read_success': True,
 'row_count_positive': True,
 'column_count_positive': True,
 'has_required_columns': True,
 'target_exists': True,
 'target_has_no_missing': np.True_,
 'target_has_at_least_two_classes': True,
 'no_missing_columns_from_expected': True,
 'possible_leakage_columns_count': 0}

In [54]:
baseline_ready = (
    validation_flags["file_exists"]
    and validation_flags["pandas_read_success"]
    and validation_flags["row_count_positive"]
    and validation_flags["column_count_positive"]
    and validation_flags["target_exists"]
    and validation_flags["target_has_no_missing"]
    and validation_flags["target_has_at_least_two_classes"]
)
if len(missing_columns) > 0:
    baseline_ready = False
print("baseline_ready:", baseline_ready)

baseline_ready: True

In [55]:
if possible_leakage_columns:
    print("주의: leakage 후보 컬럼이 있습니다.")
    print(possible_leakage_columns)
else:
    print("명확한 leakage 후보 컬럼은 발견되지 않았습니다.")

명확한 leakage 후보 컬럼은 발견되지 않았습니다.

In [56]:
import importlib
import src.preprocess as preprocess
importlib.reload(preprocess)
from src.preprocess import (
    read_clean_data,
    validate_customer_schema,
    compare_columns,
    summarize_missing_values,
    summarize_dtypes,
    summarize_target,
    detect_possible_leakage_columns,
)
print("preprocess module loaded")

preprocess module loaded

In [57]:
df_clean = read_clean_data(LOCAL_CLEAN_FILE)
print("shape:", df_clean.shape)
df_clean.head()

shape: (9, 29)

,customer_id,age,monthly_fee,usage_days,support_calls,gender_standard,contract_type_standard,signup_date,last_login_date,signup_year,...,monthly_fee_outlier,support_calls_outlier,is_high_fee,is_short_user,has_many_support_calls,usage_group,is_long_contract,churn,gender,contract_type
0,C001,34,59000,120,1,female,monthly,2025-01-10,2026-06-01,2025,...,0,0,1,0,0,middle,0,0,female,month-to-month
1,C002,45,79000,380,3,male,one_year,2024-12-01,2026-05-10,2024,...,0,0,1,0,1,long,1,1,male,1-year
2,C003,41,72000,45,0,female,monthly,2026-04-20,2026-06-03,2026,...,0,0,1,0,0,middle,0,0,female,month-to-month
3,C004,52,99000,800,5,male,one_year,2023-05-15,2026-03-01,2023,...,0,0,1,0,1,long,1,1,male,1-year
4,C005,41,69000,220,2,female,unknown,2025-08-03,2026-05-30,2025,...,0,0,1,0,0,middle,0,0,female,unknown

In [58]:
validation_result = validate_customer_schema(
    df=df_clean,
    expected_columns=expected_columns,
    target_column=TARGET_COLUMN,
)
validation_result

{'row_count': 9,
 'column_count': 29,
 'columns': {'expected_columns': ['customer_id',
   'age',
   'gender',
   'contract_type',
   'monthly_fee',
   'support_calls',
   'usage_days',
   'churn'],
  'actual_columns': ['customer_id',
   'age',
   'monthly_fee',
   'usage_days',
   'support_calls',
   'gender_standard',
   'contract_type_standard',
   'signup_date',
   'last_login_date',
   'signup_year',
   'signup_month',
   'last_login_dayofweek',
   'last_login_day_name',
   'days_since_signup',
   'days_since_last_login',
   'age_was_missing',
   'monthly_fee_was_missing',
   'gender_was_missing',
   'contract_type_was_missing',
   'monthly_fee_outlier',
   'support_calls_outlier',
   'is_high_fee',
   'is_short_user',
   'has_many_support_calls',
   'usage_group',
   'is_long_contract',
   'churn',
   'gender',
   'contract_type'],
  'missing_columns': [],
  'extra_columns': ['age_was_missing',
   'contract_type_standard',
   'contract_type_was_missing',
   'days_since_last_login',
   'days_since_signup',
   'gender_standard',
   'gender_was_missing',
   'has_many_support_calls',
   'is_high_fee',
   'is_long_contract',
   'is_short_user',
   'last_login_date',
   'last_login_day_name',
   'last_login_dayofweek',
   'monthly_fee_outlier',
   'monthly_fee_was_missing',
   'signup_date',
   'signup_month',
   'signup_year',
   'support_calls_outlier',
   'usage_group'],
  'has_required_columns': True},
 'missing_values': {'total_missing_count': 0,
  'columns_with_missing': [],
  'has_missing_values': False},
 'dtypes': {'dtype_map': {'customer_id': 'str',
   'age': 'int64',
   'monthly_fee': 'int64',
   'usage_days': 'int64',
   'support_calls': 'int64',
   'gender_standard': 'str',
   'contract_type_standard': 'str',
   'signup_date': 'str',
   'last_login_date': 'str',
   'signup_year': 'int64',
   'signup_month': 'int64',
   'last_login_dayofweek': 'int64',
   'last_login_day_name': 'str',
   'days_since_signup': 'int64',
   'days_since_last_login': 'int64',
   'age_was_missing': 'int64',
   'monthly_fee_was_missing': 'int64',
   'gender_was_missing': 'int64',
   'contract_type_was_missing': 'int64',
   'monthly_fee_outlier': 'int64',
   'support_calls_outlier': 'int64',
   'is_high_fee': 'int64',
   'is_short_user': 'int64',
   'has_many_support_calls': 'int64',
   'usage_group': 'str',
   'is_long_contract': 'int64',
   'churn': 'int64',
   'gender': 'str',
   'contract_type': 'str'},
  'numeric_columns': ['age',
   'monthly_fee',
   'usage_days',
   'support_calls',
   'signup_year',
   'signup_month',
   'last_login_dayofweek',
   'days_since_signup',
   'days_since_last_login',
   'age_was_missing',
   'monthly_fee_was_missing',
   'gender_was_missing',
   'contract_type_was_missing',
   'monthly_fee_outlier',
   'support_calls_outlier',
   'is_high_fee',
   'is_short_user',
   'has_many_support_calls',
   'is_long_contract',
   'churn'],
  'object_columns': ['customer_id',
   'gender_standard',
   'contract_type_standard',
   'signup_date',
   'last_login_date',
   'last_login_day_name',
   'usage_group',
   'gender',
   'contract_type'],
  'bool_columns': [],
  'date_candidate_columns': ['signup_date', 'last_login_date'],
  'id_candidate_columns': ['customer_id']},
 'target': {'target_column': 'churn',
  'target_exists': True,
  'target_missing_count': 0,
  'target_missing_ratio_percent': 0.0,
  'target_unique_count': 2,
  'target_distribution_count': {'0': 5, '1': 4},
  'target_distribution_ratio': {'0': 0.5556, '1': 0.4444}},
 'leakage': {'target_column': 'churn',
  'leakage_keywords': ['churn',
   'label',
   'target',
   'result',
   'outcome',
   'after',
   'future',
   'next',
   'retention_result'],
  'possible_leakage_columns': [],
  'possible_leakage_columns_count': 0},
 'baseline_ready': True}

In [59]:
print("row_count:", validation_result["row_count"])
print("column_count:", validation_result["column_count"])
print("missing_columns:", validation_result["columns"]["missing_columns"])
print("extra_columns:", validation_result["columns"]["extra_columns"])
print("target_exists:", validation_result["target"]["target_exists"])
print("target_unique_count:", validation_result["target"]["target_unique_count"])
print("possible_leakage_columns:", validation_result["leakage"]["possible_leakage_columns"])
print("baseline_ready:", validation_result["baseline_ready"])

row_count: 9
column_count: 29
missing_columns: []
extra_columns: ['age_was_missing', 'contract_type_standard', 'contract_type_was_missing', 'days_since_last_login', 'days_since_signup', 'gender_standard', 'gender_was_missing', 'has_many_support_calls', 'is_high_fee', 'is_long_contract', 'is_short_user', 'last_login_date', 'last_login_day_name', 'last_login_dayofweek', 'monthly_fee_outlier', 'monthly_fee_was_missing', 'signup_date', 'signup_month', 'signup_year', 'support_calls_outlier', 'usage_group']
target_exists: True
target_unique_count: 2
possible_leakage_columns: []
baseline_ready: True

In [60]:
column_check_df = pd.DataFrame([
    {
        "check": "missing_columns",
        "value": validation_result["columns"]["missing_columns"],
        "count": len(validation_result["columns"]["missing_columns"]),
    },
    {
        "check": "extra_columns",
        "value": validation_result["columns"]["extra_columns"],
        "count": len(validation_result["columns"]["extra_columns"]),
    }
])
column_check_df

             check                                              value  count
0  missing_columns                                                 []      0
1    extra_columns  [age_was_missing, contract_type_standard, cont...     21

In [61]:
missing_columns_list = validation_result["missing_values"]["columns_with_missing"]
missing_report_df = pd.DataFrame(missing_columns_list)
if missing_report_df.empty:
    print("결측치가 남아 있는 컬럼이 없습니다.")
else:
    display(missing_report_df)

결측치가 남아 있는 컬럼이 없습니다.

In [62]:
dtype_report_df = pd.DataFrame([
    {"column": col, "dtype": dtype}
    for col, dtype in validation_result["dtypes"]["dtype_map"].items()
])
dtype_report_df

                       column  dtype
0                 customer_id    str
1                         age  int64
2                 monthly_fee  int64
3                  usage_days  int64
4               support_calls  int64
5             gender_standard    str
6      contract_type_standard    str
7                 signup_date    str
8             last_login_date    str
9                 signup_year  int64
10               signup_month  int64
11       last_login_dayofweek  int64
12        last_login_day_name    str
13          days_since_signup  int64
14      days_since_last_login  int64
15            age_was_missing  int64
16    monthly_fee_was_missing  int64
17         gender_was_missing  int64
18  contract_type_was_missing  int64
19        monthly_fee_outlier  int64
20      support_calls_outlier  int64
21                is_high_fee  int64
22              is_short_user  int64
23     has_many_support_calls  int64
24                usage_group    str
25           is_long_contract  int64
26                      churn  int64
27                     gender    str
28              contract_type    str

In [63]:
target_distribution_df = pd.DataFrame({
    "count": validation_result["target"]["target_distribution_count"],
    "ratio": validation_result["target"]["target_distribution_ratio"]
})
target_distribution_df

   count   ratio
0      5  0.5556
1      4  0.4444

In [64]:
data_validation_report = {
    "day": "week2_day5",
    "lesson": "period3_data_validation_and_preprocess_reuse",
    "author": AUTHOR,
    "created_at": datetime.now().isoformat(),
    "execution_environment": {
        "main": "local_pc_wsl2",
        "openshift_local_used": False,
        "openshift_local_connection": "same project structure and src/preprocess.py can be reused",
        "g4dn_used": False,
        "g4dn_not_used_reason": "data validation uses pandas and does not require GPU"
    },
    "input": {
        "local_clean_file": str(LOCAL_CLEAN_FILE.relative_to(BASE_DIR)),
        "absolute_clean_file": str(LOCAL_CLEAN_FILE),
        "s3_source_from_period2": {
            "bucket": os.getenv("S3_BUCKET", ""),
            "key": os.getenv("S3_CLEAN_KEY", ""),
            "s3_uri": f"s3://{os.getenv('S3_BUCKET', '')}/{os.getenv('S3_CLEAN_KEY', '')}"
        }
    },
    "expected_columns": expected_columns,
    "target_column": TARGET_COLUMN,
    "validation_result": validation_result,
    "decision": {
        "baseline_ready": validation_result["baseline_ready"],
        "need_schema_fix": len(validation_result["columns"]["missing_columns"]) > 0,
        "need_missing_value_review": validation_result["missing_values"]["has_missing_values"],
        "need_leakage_review": validation_result["leakage"]["possible_leakage_columns_count"] > 0
    },
    "outputs": {
        "json_report": "outputs/data_validation_report.json",
        "markdown_report": "outputs/data_validation_report.md",
        "preprocess_module": "src/preprocess.py"
    },
    "next_lesson": "feature data generation and storage structure"
}
data_validation_report_file = OUTPUT_DIR / "data_validation_report.json"
with open(data_validation_report_file, "w", encoding="utf-8") as f:
    json.dump(data_validation_report, f, ensure_ascii=False, indent=2)
print("데이터 검증 JSON 저장:", data_validation_report_file)
print("존재 여부:", data_validation_report_file.exists())

데이터 검증 JSON 저장: /home/soldesk/week2-reproducibility/outputs/data_validation_report.json
존재 여부: True

In [65]:
print("baseline_ready:", data_validation_report["decision"]["baseline_ready"])
print("need_schema_fix:", data_validation_report["decision"]["need_schema_fix"])
print("need_missing_value_review:", data_validation_report["decision"]["need_missing_value_review"])
print("need_leakage_review:", data_validation_report["decision"]["need_leakage_review"])

baseline_ready: True
need_schema_fix: False
need_missing_value_review: False
need_leakage_review: False

In [66]:
missing_columns_text = "\n".join(
    [f"- {col}" for col in validation_result["columns"]["missing_columns"]]
) or "- 없음"
extra_columns_text = "\n".join(
    [f"- {col}" for col in validation_result["columns"]["extra_columns"]]
) or "- 없음"
missing_value_text = "\n".join(
    [
        f"- {item['column']}: {item['missing_count']}개 ({item['missing_ratio_percent']}%)"
        for item in validation_result["missing_values"]["columns_with_missing"]
    ]
) or "- 결측치가 남아 있는 컬럼 없음"
possible_leakage_text = "\n".join(
    [f"- {col}" for col in validation_result["leakage"]["possible_leakage_columns"]]
) or "- 명확한 leakage 후보 컬럼 없음"
numeric_columns_text = ", ".join(validation_result["dtypes"]["numeric_columns"]) or "없음"
object_columns_text = ", ".join(validation_result["dtypes"]["object_columns"]) or "없음"
date_candidate_text = ", ".join(validation_result["dtypes"]["date_candidate_columns"]) or "없음"
id_candidate_text = ", ".join(validation_result["dtypes"]["id_candidate_columns"]) or "없음"
target_count_text = "\n".join(
    [
        f"- {label}: {count}"
        for label, count in validation_result["target"]["target_distribution_count"].items()
    ]
) or "- target 분포 없음"
data_validation_report_md = f"""# Day 5 3교시 데이터 검증 리포트
## 1. 작성자
- author: {AUTHOR}
## 2. 오늘 주제
S3에서 내려받은 clean 데이터 검증 + 전처리 로직 재사용
## 3. 입력 데이터
| 항목 | 값 |
|---|---|
| local clean file | {LOCAL_CLEAN_FILE.relative_to(BASE_DIR)} |
| absolute path | {LOCAL_CLEAN_FILE} |
| target column | {TARGET_COLUMN} |
| execution environment | local_pc_wsl2 |
| OpenShift Local 사용 | 사용하지 않음, 동일 구조 실행 가능성으로 연결 |
| g4dn.xlarge 사용 | 사용하지 않음 |
## 4. 데이터 크기
| 항목 | 값 |
|---|---:|
| row_count | {validation_result["row_count"]} |
| column_count | {validation_result["column_count"]} |
## 5. 컬럼 검증
### expected columns
{chr(10).join([f"- {col}" for col in expected_columns])}
### missing columns
{missing_columns_text}
### extra columns
{extra_columns_text}
## 6. 결측치 확인
{missing_value_text}
## 7. dtype 요약
| 구분 | 컬럼 |
|---|---|
| numeric columns | {numeric_columns_text} |
| object columns | {object_columns_text} |
| date candidate columns | {date_candidate_text} |
| id candidate columns | {id_candidate_text} |
## 8. target 확인
| 항목 | 값 |
|---|---|
| target column | {TARGET_COLUMN} |
| target exists | {validation_result["target"]["target_exists"]} |
| target missing count | {validation_result["target"]["target_missing_count"]} |
| target unique count | {validation_result["target"]["target_unique_count"]} |
### target 분포
{target_count_text}
## 9. leakage 후보 점검
{possible_leakage_text}
## 10. baseline 준비 판단
| 항목 | 값 |
|---|---|
| baseline_ready | {validation_result["baseline_ready"]} |
| schema fix 필요 | {len(validation_result["columns"]["missing_columns"]) > 0} |
| 결측치 검토 필요 | {validation_result["missing_values"]["has_missing_values"]} |
| leakage 검토 필요 | {validation_result["leakage"]["possible_leakage_columns_count"] > 0} |
## 11. 사용한 재사용 함수
| 함수 | 역할 |
|---|---|
| read_clean_data() | clean CSV 읽기 |
| compare_columns() | expected/actual 컬럼 비교 |
| summarize_missing_values() | 결측치 개수와 비율 요약 |
| summarize_dtypes() | dtype과 컬럼 유형 후보 요약 |
| summarize_target() | target 존재와 분포 확인 |
| detect_possible_leakage_columns() | leakage 후보 컬럼 탐지 |
| validate_customer_schema() | 전체 검증 실행 |
## 12. OpenShift Local 연결
이번 교시에서는 OpenShift Local에 앱을 배포하지 않았다.
하지만 `src/preprocess.py`로 검증 로직을 분리했기 때문에,
같은 프로젝트 구조와 같은 `.env` 설정을 사용하면
OpenShift Local 또는 Developer Sandbox에서도 동일한 검증 함수를 재사용할 수 있다.
## 13. g4dn.xlarge 연결
이번 교시에서는 g4dn.xlarge를 사용하지 않았다.
데이터 검증은 pandas 기반 CPU 작업이며 GPU가 필요하지 않다.
이후 GPU 실습에서도 모델 학습 전에 같은 검증 원칙을 사용해야 한다.
## 14. 다음 교시 연결
4교시에서는 검증된 clean 데이터를 기반으로 feature 데이터를 생성한다.
중요한 점은 target인 `{TARGET_COLUMN}`을 feature로 넣지 않는 것이다.
"""
data_validation_report_md_file = OUTPUT_DIR / "data_validation_report.md"
data_validation_report_md_file.write_text(data_validation_report_md, encoding="utf-8")
print("데이터 검증 Markdown 저장:", data_validation_report_md_file)
print("존재 여부:", data_validation_report_md_file.exists())

데이터 검증 Markdown 저장: /home/soldesk/week2-reproducibility/outputs/data_validation_report.md
존재 여부: True

In [67]:
from pathlib import Path
import os
import json
import textwrap
import pandas as pd


# 현재 실행 위치가 notebook 또는 notebooks 폴더이면 부모 폴더를 프로젝트 루트로 사용
BASE_DIR = Path.cwd().parent if Path.cwd().name in ["notebook", "notebooks"] else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# outputs 폴더 준비
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# 기본 변수 준비
AUTHOR = globals().get(
    "AUTHOR",
    globals().get("author", os.environ.get("AUTHOR", "student"))
)

TARGET_COLUMN = globals().get(
    "TARGET_COLUMN",
    os.environ.get("TARGET_COLUMN", "churn")
)

LOCAL_CLEAN_FILE_RAW = globals().get(
    "LOCAL_CLEAN_FILE",
    os.environ.get("LOCAL_CLEAN_FILE", "data/clean/customers_clean_20260606_v2.csv")
)

LOCAL_CLEAN_FILE = Path(LOCAL_CLEAN_FILE_RAW)

if not LOCAL_CLEAN_FILE.is_absolute():
    LOCAL_CLEAN_FILE = BASE_DIR / LOCAL_CLEAN_FILE

# expected_columns가 이전 셀에 없을 경우 기본값 사용
expected_columns = globals().get(
    "expected_columns",
    [
        "customer_id",
        "age",
        "gender",
        "monthly_fee",
        "contract_type",
        "usage_days",
        "support_calls",
        "churn",
    ]
)


def safe_relative_path(path: Path, base_dir: Path) -> str:
    """
    path가 base_dir 하위이면 상대경로를 반환하고,
    아니면 절대경로 문자열을 반환한다.
    """
    path = Path(path)

    try:
        return str(path.relative_to(base_dir))
    except ValueError:
        return str(path)


def markdown_safe(value) -> str:
    """
    Markdown 표에서 깨질 수 있는 값을 안전한 문자열로 변환한다.
    """
    if value is None:
        return "확인 필요"

    text = str(value).replace("\n", " ").strip()

    if not text:
        return "확인 필요"

    # Markdown 표에서 | 문자가 있으면 표가 깨질 수 있으므로 치환
    text = text.replace("|", "\\|")

    return text


def make_bullet_list(items, empty_text: str) -> str:
    """
    리스트를 Markdown bullet 문자열로 변환한다.
    """
    if not items:
        return empty_text

    return "\n".join([f"- {item}" for item in items])


def make_target_count_text(target_count_dict: dict) -> str:
    """
    target 분포 dict를 Markdown bullet 문자열로 변환한다.
    """
    if not target_count_dict:
        return "- target 분포 없음"

    return "\n".join(
        [
            f"- {label}: {count}"
            for label, count in target_count_dict.items()
        ]
    )


# validation_result가 없으면 src.preprocess를 사용해서 새로 생성
if "validation_result" not in globals():
    if not LOCAL_CLEAN_FILE.exists():
        validation_result = {
            "row_count": 0,
            "column_count": 0,
            "columns": {
                "expected_columns": expected_columns,
                "actual_columns": [],
                "missing_columns": expected_columns,
                "extra_columns": [],
                "has_required_columns": False,
            },
            "missing_values": {
                "total_missing_count": None,
                "columns_with_missing": [],
                "has_missing_values": None,
            },
            "dtypes": {
                "dtype_map": {},
                "numeric_columns": [],
                "object_columns": [],
                "bool_columns": [],
                "date_candidate_columns": [],
                "id_candidate_columns": [],
            },
            "target": {
                "target_column": TARGET_COLUMN,
                "target_exists": False,
                "target_missing_count": None,
                "target_missing_ratio_percent": None,
                "target_unique_count": None,
                "target_distribution_count": {},
                "target_distribution_ratio": {},
            },
            "leakage": {
                "target_column": TARGET_COLUMN,
                "leakage_keywords": [],
                "possible_leakage_columns": [],
                "possible_leakage_columns_count": 0,
            },
            "baseline_ready": False,
        }
    else:
        import sys

        if str(BASE_DIR) not in sys.path:
            sys.path.append(str(BASE_DIR))

        from src.preprocess import read_clean_data, validate_customer_schema

        df_clean = read_clean_data(LOCAL_CLEAN_FILE)

        validation_result = validate_customer_schema(
            df=df_clean,
            expected_columns=expected_columns,
            target_column=TARGET_COLUMN,
        )


# validation_result 내부 값 안전하게 꺼내기
columns_result = validation_result.get("columns", {})
missing_values_result = validation_result.get("missing_values", {})
dtypes_result = validation_result.get("dtypes", {})
target_result = validation_result.get("target", {})
leakage_result = validation_result.get("leakage", {})

missing_columns = columns_result.get("missing_columns", [])
extra_columns = columns_result.get("extra_columns", [])
columns_with_missing = missing_values_result.get("columns_with_missing", [])
possible_leakage_columns = leakage_result.get("possible_leakage_columns", [])

missing_columns_text = make_bullet_list(
    missing_columns,
    "- 없음"
)

extra_columns_text = make_bullet_list(
    extra_columns,
    "- 없음"
)

missing_value_text = "\n".join(
    [
        f"- {item.get('column')}: {item.get('missing_count')}개 ({item.get('missing_ratio_percent')}%)"
        for item in columns_with_missing
    ]
) or "- 결측치가 남아 있는 컬럼 없음"

possible_leakage_text = make_bullet_list(
    possible_leakage_columns,
    "- 명확한 leakage 후보 컬럼 없음"
)

numeric_columns_text = ", ".join(dtypes_result.get("numeric_columns", [])) or "없음"
object_columns_text = ", ".join(dtypes_result.get("object_columns", [])) or "없음"
date_candidate_text = ", ".join(dtypes_result.get("date_candidate_columns", [])) or "없음"
id_candidate_text = ", ".join(dtypes_result.get("id_candidate_columns", [])) or "없음"

target_count_text = make_target_count_text(
    target_result.get("target_distribution_count", {})
)

expected_columns_text = "\n".join(
    [f"- {col}" for col in expected_columns]
) or "- expected_columns 없음"

local_clean_relative = safe_relative_path(LOCAL_CLEAN_FILE, BASE_DIR)

schema_fix_needed = len(missing_columns) > 0
missing_review_needed = missing_values_result.get("has_missing_values", "확인 필요")
leakage_review_needed = leakage_result.get("possible_leakage_columns_count", 0) > 0

# Markdown 리포트 내용
data_validation_report_md = f"""
# Day 5 3교시 데이터 검증 리포트

## 1. 작성자

- author: {AUTHOR}

## 2. 오늘 주제

S3에서 내려받은 clean 데이터 검증 + 전처리 로직 재사용

## 3. 입력 데이터

| 항목 | 값 |
|---|---|
| local clean file | {markdown_safe(local_clean_relative)} |
| absolute path | {markdown_safe(LOCAL_CLEAN_FILE)} |
| target column | {markdown_safe(TARGET_COLUMN)} |
| execution environment | local_pc_wsl2 |
| OpenShift Local 사용 | 사용하지 않음, 동일 구조 실행 가능성으로 연결 |
| g4dn.xlarge 사용 | 사용하지 않음 |

## 4. 데이터 크기

| 항목 | 값 |
|---|---:|
| row_count | {markdown_safe(validation_result.get("row_count"))} |
| column_count | {markdown_safe(validation_result.get("column_count"))} |

## 5. 컬럼 검증

### expected columns

{expected_columns_text}

### missing columns

{missing_columns_text}

### extra columns

{extra_columns_text}

## 6. 결측치 확인

{missing_value_text}

## 7. dtype 요약

| 구분 | 컬럼 |
|---|---|
| numeric columns | {markdown_safe(numeric_columns_text)} |
| object columns | {markdown_safe(object_columns_text)} |
| date candidate columns | {markdown_safe(date_candidate_text)} |
| id candidate columns | {markdown_safe(id_candidate_text)} |

## 8. target 확인

| 항목 | 값 |
|---|---|
| target column | {markdown_safe(TARGET_COLUMN)} |
| target exists | {markdown_safe(target_result.get("target_exists"))} |
| target missing count | {markdown_safe(target_result.get("target_missing_count"))} |
| target unique count | {markdown_safe(target_result.get("target_unique_count"))} |

### target 분포

{target_count_text}

## 9. leakage 후보 점검

{possible_leakage_text}

## 10. baseline 준비 판단

| 항목 | 값 |
|---|---|
| baseline_ready | {markdown_safe(validation_result.get("baseline_ready"))} |
| schema fix 필요 | {markdown_safe(schema_fix_needed)} |
| 결측치 검토 필요 | {markdown_safe(missing_review_needed)} |
| leakage 검토 필요 | {markdown_safe(leakage_review_needed)} |

## 11. 사용한 재사용 함수

| 함수 | 역할 |
|---|---|
| read_clean_data() | clean CSV 읽기 |
| compare_columns() | expected/actual 컬럼 비교 |
| summarize_missing_values() | 결측치 개수와 비율 요약 |
| summarize_dtypes() | dtype과 컬럼 유형 후보 요약 |
| summarize_target() | target 존재와 분포 확인 |
| detect_possible_leakage_columns() | leakage 후보 컬럼 탐지 |
| validate_customer_schema() | 전체 검증 실행 |

## 12. OpenShift Local 연결

이번 교시에서는 OpenShift Local에 앱을 배포하지 않았다.

하지만 `src/preprocess.py`로 검증 로직을 분리했기 때문에,  
같은 프로젝트 구조와 같은 `.env` 설정을 사용하면  
OpenShift Local 또는 Developer Sandbox에서도 동일한 검증 함수를 재사용할 수 있다.

## 13. g4dn.xlarge 연결

이번 교시에서는 g4dn.xlarge를 사용하지 않았다.

데이터 검증은 pandas 기반 CPU 작업이며 GPU가 필요하지 않다.

이후 GPU 실습에서도 모델 학습 전에 같은 검증 원칙을 사용해야 한다.

## 14. 다음 교시 연결

4교시에서는 검증된 clean 데이터를 기반으로 feature 데이터를 생성한다.

중요한 점은 target인 `{TARGET_COLUMN}`을 feature로 넣지 않는 것이다.
"""

# 앞뒤 공백 정리 후 저장
data_validation_report_md = textwrap.dedent(data_validation_report_md).strip() + "\n"

data_validation_report_md_file = OUTPUT_DIR / "data_validation_report.md"

data_validation_report_md_file.write_text(
    data_validation_report_md,
    encoding="utf-8"
)

print("데이터 검증 Markdown 저장:", data_validation_report_md_file)
print("존재 여부:", data_validation_report_md_file.exists())
print("상대 경로:", data_validation_report_md_file.relative_to(BASE_DIR))

데이터 검증 Markdown 저장: /home/soldesk/week2-reproducibility/outputs/data_validation_report.md
존재 여부: True
상대 경로: outputs/data_validation_report.md

In [68]:
from pathlib import Path
import os
import sys
import json
import textwrap


# 현재 실행 위치가 notebook 또는 notebooks 폴더이면 부모 폴더를 프로젝트 루트로 사용
BASE_DIR = Path.cwd().parent if Path.cwd().name in ["notebook", "notebooks"] else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# 폴더 준비
REPORT_DIR = BASE_DIR / "reports" / "week2"
OUTPUT_DIR = BASE_DIR / "outputs"

REPORT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


# 기본 설정값
AUTHOR = globals().get(
    "AUTHOR",
    globals().get("author", os.environ.get("AUTHOR", "student"))
)

AWS_REGION = globals().get(
    "AWS_REGION",
    os.environ.get("AWS_REGION", "ap-northeast-2")
)

S3_BUCKET = globals().get(
    "S3_BUCKET",
    globals().get("BUCKET", globals().get("bucket_name", os.environ.get("S3_BUCKET", "edu-ai-lake")))
)

S3_CLEAN_PREFIX = globals().get(
    "S3_CLEAN_PREFIX",
    os.environ.get("S3_CLEAN_PREFIX", f"users/{AUTHOR}/clean/customers/")
)

S3_CLEAN_KEY = globals().get(
    "S3_CLEAN_KEY",
    os.environ.get("S3_CLEAN_KEY", f"{S3_CLEAN_PREFIX}customers_clean_20260606_v2.csv")
)

S3_CLEAN_URI = f"s3://{S3_BUCKET}/{S3_CLEAN_KEY}"

TARGET_COLUMN = globals().get(
    "TARGET_COLUMN",
    os.environ.get("TARGET_COLUMN", "churn")
)

LOCAL_CLEAN_FILE_RAW = globals().get(
    "LOCAL_CLEAN_FILE",
    os.environ.get("LOCAL_CLEAN_FILE", "data/clean/customers_clean_20260606_v2.csv")
)

LOCAL_CLEAN_FILE = Path(LOCAL_CLEAN_FILE_RAW)

if not LOCAL_CLEAN_FILE.is_absolute():
    LOCAL_CLEAN_FILE = BASE_DIR / LOCAL_CLEAN_FILE

expected_columns = globals().get(
    "expected_columns",
    [
        "customer_id",
        "age",
        "gender",
        "monthly_fee",
        "contract_type",
        "usage_days",
        "support_calls",
        "churn",
    ]
)


def safe_relative_path(path: Path, base_dir: Path) -> str:
    """
    path가 base_dir 하위이면 상대경로를 반환하고,
    아니면 절대경로 문자열을 반환한다.
    """
    path = Path(path)

    try:
        return str(path.relative_to(base_dir))
    except ValueError:
        return str(path)


def markdown_safe(value) -> str:
    """
    Markdown 표 안에서 깨질 수 있는 값을 안전한 문자열로 변환한다.
    """
    if value is None:
        return "확인 필요"

    text = str(value).replace("\n", " ").strip()

    if not text:
        return "확인 필요"

    return text.replace("|", "\\|")


def bullet_list(items, empty_text: str = "- 없음") -> str:
    """
    리스트를 Markdown bullet 문자열로 변환한다.
    """
    if not items:
        return empty_text

    return "\n".join([f"- {item}" for item in items])


def dict_to_bullets(data: dict, empty_text: str = "- 없음") -> str:
    """
    dict를 Markdown bullet 문자열로 변환한다.
    """
    if not data:
        return empty_text

    return "\n".join([f"- {key}: {value}" for key, value in data.items()])


def safe_read_json(path: Path) -> dict:
    """
    JSON 파일을 안전하게 읽는다.
    """
    if not path.exists():
        return {}

    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


# validation_result가 있으면 사용하고, 없으면 JSON 또는 src.preprocess로 생성 시도
if "validation_result" in globals():
    validation_result_for_record = validation_result

else:
    data_validation_json_file = OUTPUT_DIR / "data_validation_report.json"
    validation_result_for_record = safe_read_json(data_validation_json_file)

    if not validation_result_for_record and LOCAL_CLEAN_FILE.exists():
        if str(BASE_DIR) not in sys.path:
            sys.path.append(str(BASE_DIR))

        try:
            from src.preprocess import read_clean_data, validate_customer_schema

            df_clean_for_record = read_clean_data(LOCAL_CLEAN_FILE)

            validation_result_for_record = validate_customer_schema(
                df=df_clean_for_record,
                expected_columns=expected_columns,
                target_column=TARGET_COLUMN,
            )

        except Exception as e:
            validation_result_for_record = {
                "row_count": "확인 필요",
                "column_count": "확인 필요",
                "error": f"{type(e).__name__}: {e}",
            }

    if not validation_result_for_record:
        validation_result_for_record = {
            "row_count": "확인 필요",
            "column_count": "확인 필요",
            "columns": {
                "expected_columns": expected_columns,
                "actual_columns": [],
                "missing_columns": [],
                "extra_columns": [],
            },
            "missing_values": {
                "columns_with_missing": [],
                "has_missing_values": "확인 필요",
            },
            "dtypes": {
                "numeric_columns": [],
                "object_columns": [],
                "date_candidate_columns": [],
                "id_candidate_columns": [],
            },
            "target": {
                "target_column": TARGET_COLUMN,
                "target_exists": "확인 필요",
                "target_missing_count": "확인 필요",
                "target_unique_count": "확인 필요",
                "target_distribution_count": {},
            },
            "leakage": {
                "possible_leakage_columns": [],
                "possible_leakage_columns_count": 0,
            },
            "baseline_ready": "확인 필요",
        }


# 검증 결과 꺼내기
columns_result = validation_result_for_record.get("columns", {})
missing_values_result = validation_result_for_record.get("missing_values", {})
dtypes_result = validation_result_for_record.get("dtypes", {})
target_result = validation_result_for_record.get("target", {})
leakage_result = validation_result_for_record.get("leakage", {})

row_count = validation_result_for_record.get("row_count", "확인 필요")
column_count = validation_result_for_record.get("column_count", "확인 필요")

expected_columns_for_report = columns_result.get("expected_columns", expected_columns)
actual_columns_for_report = columns_result.get("actual_columns", [])
missing_columns_for_report = columns_result.get("missing_columns", [])
extra_columns_for_report = columns_result.get("extra_columns", [])

columns_with_missing = missing_values_result.get("columns_with_missing", [])

missing_column_lines = [
    f"{item.get('column')}: {item.get('missing_count')}개 ({item.get('missing_ratio_percent')}%)"
    for item in columns_with_missing
]

high_missing_column_lines = [
    f"{item.get('column')}: {item.get('missing_ratio_percent')}%"
    for item in columns_with_missing
    if float(item.get("missing_ratio_percent", 0)) >= 30
]

numeric_columns = dtypes_result.get("numeric_columns", [])
object_columns = dtypes_result.get("object_columns", [])
date_candidate_columns = dtypes_result.get("date_candidate_columns", [])
id_candidate_columns = dtypes_result.get("id_candidate_columns", [])

target_distribution_count = target_result.get("target_distribution_count", {})
possible_leakage_columns = leakage_result.get("possible_leakage_columns", [])

target_like_columns = [
    col for col in possible_leakage_columns
    if TARGET_COLUMN.lower() in col.lower()
    or "churn" in col.lower()
    or "label" in col.lower()
    or "target" in col.lower()
]

future_info_columns = [
    col for col in possible_leakage_columns
    if "future" in col.lower()
    or "after" in col.lower()
    or "next" in col.lower()
    or "result" in col.lower()
    or "outcome" in col.lower()
]

review_columns = sorted(
    set(possible_leakage_columns + id_candidate_columns)
)

baseline_ready = validation_result_for_record.get("baseline_ready", "확인 필요")

baseline_reason_items = []

if baseline_ready is True:
    baseline_reason_items.append("필수 컬럼, target, 데이터 크기 조건을 1차로 만족했다.")
elif baseline_ready is False:
    if missing_columns_for_report:
        baseline_reason_items.append("필수 컬럼 누락이 있어 schema 수정이 필요하다.")
    if target_result.get("target_exists") is False:
        baseline_reason_items.append("target 컬럼이 존재하지 않는다.")
    if target_result.get("target_missing_count") not in [0, "0", None, "확인 필요"]:
        baseline_reason_items.append("target 컬럼에 결측치가 있다.")
    if target_result.get("target_unique_count") in [0, 1, "0", "1"]:
        baseline_reason_items.append("target class가 2개 미만이다.")
    if not baseline_reason_items:
        baseline_reason_items.append("검증 항목 중 일부가 통과하지 못했다.")
else:
    baseline_reason_items.append("validation_result를 먼저 생성하거나 데이터 검증을 다시 실행해야 한다.")

additional_check_items = [
    "extra columns 중 leakage 후보가 있는지 확인한다.",
    "식별자 컬럼은 feature에서 제외할지 검토한다.",
    "target 컬럼은 feature에 넣지 않는다.",
]

local_clean_file_text = safe_relative_path(LOCAL_CLEAN_FILE, BASE_DIR)

# 저장 파일 경로
period3_record_file = REPORT_DIR / "day5_period3_data_validation_record.md"

# Markdown 기록 양식
period3_record_text = f"""
# 2주차 Day 5 3교시 실습 기록지

## 작성자

- author: {AUTHOR}

## 1. 오늘 주제

데이터 검증 + 전처리 로직 재사용

## 2. 입력 데이터

- local clean file: {local_clean_file_text}
- S3 bucket: {S3_BUCKET}
- S3 key: {S3_CLEAN_KEY}
- S3 URI: {S3_CLEAN_URI}

## 3. 데이터 크기

- rows: {row_count}
- columns: {column_count}

## 4. 컬럼 검증

### expected columns

{bullet_list(expected_columns_for_report)}

### actual columns

{bullet_list(actual_columns_for_report)}

### missing columns

{bullet_list(missing_columns_for_report)}

### extra columns

{bullet_list(extra_columns_for_report)}

## 5. 결측치 확인

- 결측치가 있는 컬럼:

{bullet_list(missing_column_lines, "- 결측치가 있는 컬럼 없음")}

- 결측치 비율이 높은 컬럼:

{bullet_list(high_missing_column_lines, "- 결측치 비율이 높은 컬럼 없음")}

- 처리 필요 여부: {markdown_safe(missing_values_result.get("has_missing_values", "확인 필요"))}

## 6. dtype 확인

- 수치형 컬럼:

{bullet_list(numeric_columns)}

- 범주형 또는 object 컬럼:

{bullet_list(object_columns)}

- 날짜형 후보 컬럼:

{bullet_list(date_candidate_columns)}

- 식별자 후보 컬럼:

{bullet_list(id_candidate_columns)}

## 7. target 확인

- target 컬럼: {markdown_safe(target_result.get("target_column", TARGET_COLUMN))}
- target 존재 여부: {markdown_safe(target_result.get("target_exists", "확인 필요"))}
- target 결측치 수: {markdown_safe(target_result.get("target_missing_count", "확인 필요"))}
- target class 개수: {markdown_safe(target_result.get("target_unique_count", "확인 필요"))}
- target 분포:

{dict_to_bullets(target_distribution_count, "- target 분포 확인 필요")}

## 8. leakage 점검

- target과 유사한 feature 후보:

{bullet_list(target_like_columns)}

- 미래 정보 컬럼 후보:

{bullet_list(future_info_columns)}

- 식별자 컬럼 후보:

{bullet_list(id_candidate_columns)}

- 제거 또는 검토할 컬럼:

{bullet_list(review_columns)}

## 9. baseline 준비 가능 여부

- 가능 여부: {markdown_safe(baseline_ready)}
- 이유:

{bullet_list(baseline_reason_items)}

- 추가 확인 필요 사항:

{bullet_list(additional_check_items)}

## 10. 작성한 산출물

| 산출물 | 경로 |
|---|---|
| 데이터 검증 JSON | outputs/data_validation_report.json |
| 데이터 검증 Markdown | outputs/data_validation_report.md |
| 전처리 재사용 모듈 | src/preprocess.py |

## 11. OpenShift Local 연결

- OpenShift Local에서 같은 검증 로직을 실행하려면 무엇이 같아야 하는가?
- 같은 프로젝트 폴더 구조를 사용해야 한다.
- 같은 `requirements.txt`를 사용해야 한다.
- 같은 `.env.example` 구조를 유지해야 한다.
- 같은 `src/preprocess.py` 모듈을 사용할 수 있어야 한다.
- S3 bucket, S3 key, local clean file 경로를 환경 변수 또는 ConfigMap으로 주입할 수 있어야 한다.

## 12. g4dn 연결

- 이번 교시에서 g4dn을 사용하지 않는 이유는?
  - 데이터 검증은 pandas 기반 CPU 작업이므로 GPU가 필요하지 않다.

- GPU 학습 전에 데이터 검증이 필요한 이유는?
  - 잘못된 데이터로 GPU 학습을 실행하면 시간과 비용이 낭비된다.
  - target 누락, leakage, 결측치, 컬럼 불일치를 먼저 확인해야 한다.
  - 검증된 feature 데이터만 GPU 학습 단계로 넘기는 것이 안전하다.

## 13. 오늘 배운 핵심

- 데이터 검증은 모델링 전에 반드시 수행해야 한다.
- expected columns와 actual columns를 비교해야 한다.
- target 컬럼은 존재 여부, 결측치, class 개수를 확인해야 한다.
- leakage 후보 컬럼은 feature로 사용하기 전에 반드시 검토해야 한다.
- 검증 로직은 `src/preprocess.py`로 분리하면 재사용할 수 있다.

## 14. 다음 교시에서 할 일

feature 데이터 생성 + 저장 구조 정리
"""

# 앞뒤 공백 정리 후 저장
period3_record_text = textwrap.dedent(period3_record_text).strip() + "\n"

period3_record_file.write_text(
    period3_record_text,
    encoding="utf-8"
)

print("Day 5 3교시 데이터 검증 실습 기록지 저장:", period3_record_file)
print("존재 여부:", period3_record_file.exists())
print("상대 경로:", period3_record_file.relative_to(BASE_DIR))

Day 5 3교시 데이터 검증 실습 기록지 저장: /home/soldesk/week2-reproducibility/reports/week2/day5_period3_data_validation_record.md
존재 여부: True
상대 경로: reports/week2/day5_period3_data_validation_record.md

In [69]:
from pathlib import Path
import os
import sys
import json
from datetime import datetime
import numpy as np
import pandas as pd
from dotenv import load_dotenv
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
if str(BASE_DIR) not in sys.path:
    sys.path.append(str(BASE_DIR))
env_path = BASE_DIR / ".env"
load_dotenv(env_path)
AUTHOR = os.getenv("AUTHOR", "student")
SEED = int(os.getenv("SEED", "42"))
LOCAL_CLEAN_FILE_RAW = os.getenv(
    "LOCAL_CLEAN_FILE",
    "data/clean/customers_clean_20260606_v2.csv"
)
LOCAL_FEATURE_FILE_RAW = os.getenv(
    "LOCAL_FEATURE_FILE",
    "data/feature/customers_feature_20260607_v1.csv"
)
LOCAL_CLEAN_FILE = BASE_DIR / LOCAL_CLEAN_FILE_RAW
LOCAL_FEATURE_FILE = BASE_DIR / LOCAL_FEATURE_FILE_RAW
DATA_DIR = BASE_DIR / "data"
CLEAN_DIR = DATA_DIR / "clean"
FEATURE_DIR = DATA_DIR / "feature"
OUTPUT_DIR = BASE_DIR / "outputs"
REPORT_DIR = BASE_DIR / "reports" / "week2"
for directory in [CLEAN_DIR, FEATURE_DIR, OUTPUT_DIR, REPORT_DIR]:
    directory.mkdir(parents=True, exist_ok=True)
print("AUTHOR:", AUTHOR)
print("LOCAL_CLEAN_FILE:", LOCAL_CLEAN_FILE)
print("LOCAL_FEATURE_FILE:", LOCAL_FEATURE_FILE)
print("clean exists:", LOCAL_CLEAN_FILE.exists())

AUTHOR: kim-juil
LOCAL_CLEAN_FILE: /home/soldesk/week2-reproducibility/data/clean/customers_clean_20260606_v2.csv
LOCAL_FEATURE_FILE: /home/soldesk/week2-reproducibility/data/feature/customers_feature_20260607_v1.csv
clean exists: True

In [70]:
if not LOCAL_CLEAN_FILE.exists():
    raise FileNotFoundError(f"clean 데이터 파일이 없습니다: {LOCAL_CLEAN_FILE}")
df_clean = pd.read_csv(LOCAL_CLEAN_FILE)
print("df_clean shape:", df_clean.shape)
print("df_clean columns:", list(df_clean.columns))
df_clean.head()

df_clean shape: (9, 29)
df_clean columns: ['customer_id', 'age', 'monthly_fee', 'usage_days', 'support_calls', 'gender_standard', 'contract_type_standard', 'signup_date', 'last_login_date', 'signup_year', 'signup_month', 'last_login_dayofweek', 'last_login_day_name', 'days_since_signup', 'days_since_last_login', 'age_was_missing', 'monthly_fee_was_missing', 'gender_was_missing', 'contract_type_was_missing', 'monthly_fee_outlier', 'support_calls_outlier', 'is_high_fee', 'is_short_user', 'has_many_support_calls', 'usage_group', 'is_long_contract', 'churn', 'gender', 'contract_type']

,customer_id,age,monthly_fee,usage_days,support_calls,gender_standard,contract_type_standard,signup_date,last_login_date,signup_year,...,monthly_fee_outlier,support_calls_outlier,is_high_fee,is_short_user,has_many_support_calls,usage_group,is_long_contract,churn,gender,contract_type
0,C001,34,59000,120,1,female,monthly,2025-01-10,2026-06-01,2025,...,0,0,1,0,0,middle,0,0,female,month-to-month
1,C002,45,79000,380,3,male,one_year,2024-12-01,2026-05-10,2024,...,0,0,1,0,1,long,1,1,male,1-year
2,C003,41,72000,45,0,female,monthly,2026-04-20,2026-06-03,2026,...,0,0,1,0,0,middle,0,0,female,month-to-month
3,C004,52,99000,800,5,male,one_year,2023-05-15,2026-03-01,2023,...,0,0,1,0,1,long,1,1,male,1-year
4,C005,41,69000,220,2,female,unknown,2025-08-03,2026-05-30,2025,...,0,0,1,0,0,middle,0,0,female,unknown

In [71]:
data_validation_report_file = OUTPUT_DIR / "data_validation_report.json"
if data_validation_report_file.exists():
    with open(data_validation_report_file, "r", encoding="utf-8") as f:
        data_validation_report = json.load(f)
    print("baseline_ready:", data_validation_report["decision"]["baseline_ready"])
    print("need_schema_fix:", data_validation_report["decision"]["need_schema_fix"])
    print("need_missing_value_review:", data_validation_report["decision"]["need_missing_value_review"])
    print("need_leakage_review:", data_validation_report["decision"]["need_leakage_review"])
else:
    print("data_validation_report.json이 없습니다. 3교시 검증 결과를 먼저 생성하세요.")

baseline_ready: True
need_schema_fix: False
need_missing_value_review: False
need_leakage_review: False

In [72]:
import importlib
import src.preprocess as preprocess
importlib.reload(preprocess)
from src.preprocess import create_basic_features, create_basic_customer_features
print("feature 생성 함수 import 완료")

feature 생성 함수 import 완료

In [73]:
feature_df = create_basic_features(df_clean)
print("df_clean shape:", df_clean.shape)
print("feature_df shape:", feature_df.shape)
feature_df.head()

df_clean shape: (9, 29)
feature_df shape: (9, 32)

,customer_id,age,monthly_fee,usage_days,support_calls,gender_standard,contract_type_standard,signup_date,last_login_date,signup_year,...,is_short_user,has_many_support_calls,usage_group,is_long_contract,churn,gender,contract_type,fee_per_usage_day,support_call_flag,long_usage_flag
0,C001,34,59000,120,1,female,monthly,2025-01-10,2026-06-01,2025,...,0,0,middle,0,0,female,month-to-month,491.666667,1,0
1,C002,45,79000,380,3,male,one_year,2024-12-01,2026-05-10,2024,...,0,1,long,1,1,male,1-year,207.894737,1,1
2,C003,41,72000,45,0,female,monthly,2026-04-20,2026-06-03,2026,...,0,0,middle,0,0,female,month-to-month,1600.000000,0,0
3,C004,52,99000,800,5,male,one_year,2023-05-15,2026-03-01,2023,...,0,1,long,1,1,male,1-year,123.750000,1,1
4,C005,41,69000,220,2,female,unknown,2025-08-03,2026-05-30,2025,...,0,0,middle,0,0,female,unknown,313.636364,1,1

In [74]:
before_columns = set(df_clean.columns)
after_columns = set(feature_df.columns)
created_columns = sorted(list(after_columns - before_columns))
print("생성된 컬럼:", created_columns)

생성된 컬럼: ['fee_per_usage_day', 'long_usage_flag', 'support_call_flag']

In [75]:
display_columns = [
    "monthly_fee",
    "usage_days",
    "fee_per_usage_day",
    "support_calls",
    "support_call_flag",
    "long_usage_flag",
    "churn"
]
available_display_columns = [col for col in display_columns if col in feature_df.columns]
feature_df[available_display_columns].head()

,monthly_fee,usage_days,fee_per_usage_day,support_calls,support_call_flag,long_usage_flag,churn
0,59000,120,491.666667,1,1,0,0
1,79000,380,207.894737,3,1,1,1
2,72000,45,1600.000000,0,0,0,0
3,99000,800,123.750000,5,1,1,1
4,69000,220,313.636364,2,1,1,0

In [76]:
created_feature_cols = [
    "fee_per_usage_day",
    "support_call_flag",
    "long_usage_flag"
]
feature_df[created_feature_cols].describe()

       fee_per_usage_day  support_call_flag  long_usage_flag
count           9.000000           9.000000         9.000000
mean          750.670964           0.777778         0.555556
std           971.537244           0.440959         0.527046
min           109.090909           0.000000         0.000000
25%           123.750000           1.000000         0.000000
50%           313.636364           1.000000         1.000000
75%           800.000000           1.000000         1.000000
max          3000.000000           1.000000         1.000000

In [77]:
feature_df[created_feature_cols].isna().sum()

fee_per_usage_day    0
support_call_flag    0
long_usage_flag      0
dtype: int64

In [78]:
np.isinf(feature_df["fee_per_usage_day"]).sum()

np.int64(0)

In [79]:
print("fee_per_usage_day min:", feature_df["fee_per_usage_day"].min())
print("fee_per_usage_day max:", feature_df["fee_per_usage_day"].max())
print("support_call_flag unique:", sorted(feature_df["support_call_flag"].unique().tolist()))
print("long_usage_flag unique:", sorted(feature_df["long_usage_flag"].unique().tolist()))

fee_per_usage_day min: 109.0909090909091
fee_per_usage_day max: 3000.0
support_call_flag unique: [0, 1]
long_usage_flag unique: [0, 1]

In [80]:
print("support_call_flag 분포")
print(feature_df["support_call_flag"].value_counts(dropna=False))
print("long_usage_flag 분포")
print(feature_df["long_usage_flag"].value_counts(dropna=False))

support_call_flag 분포
support_call_flag
1    7
0    2
Name: count, dtype: int64
long_usage_flag 분포
long_usage_flag
1    5
0    4
Name: count, dtype: int64

In [81]:
target_col = "churn"
if target_col not in feature_df.columns:
    raise KeyError(f"target 컬럼이 없습니다: {target_col}")
print("target_col:", target_col)

target_col: churn

In [82]:
drop_cols = [
    "customer_id",
    target_col
]

In [83]:
possible_leakage_columns = []
if data_validation_report_file.exists():
    possible_leakage_columns = data_validation_report["validation_result"]["leakage"]["possible_leakage_columns"]
print("possible_leakage_columns:", possible_leakage_columns)

possible_leakage_columns: []

In [84]:
drop_cols = sorted(
    set([col for col in drop_cols + possible_leakage_columns if col in feature_df.columns])
)
print("drop_cols:", drop_cols)

drop_cols: ['churn', 'customer_id']

In [85]:
feature_cols = [col for col in feature_df.columns if col not in drop_cols]
print("target:", target_col)
print("drop_cols:", drop_cols)
print("feature_cols:", feature_cols)

target: churn
drop_cols: ['churn', 'customer_id']
feature_cols: ['age', 'monthly_fee', 'usage_days', 'support_calls', 'gender_standard', 'contract_type_standard', 'signup_date', 'last_login_date', 'signup_year', 'signup_month', 'last_login_dayofweek', 'last_login_day_name', 'days_since_signup', 'days_since_last_login', 'age_was_missing', 'monthly_fee_was_missing', 'gender_was_missing', 'contract_type_was_missing', 'monthly_fee_outlier', 'support_calls_outlier', 'is_high_fee', 'is_short_user', 'has_many_support_calls', 'usage_group', 'is_long_contract', 'gender', 'contract_type', 'fee_per_usage_day', 'support_call_flag', 'long_usage_flag']

In [86]:
object_cols = feature_df[feature_cols].select_dtypes(include=["object"]).columns.tolist()
object_cols

/tmp/ipykernel_1480/2472527084.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = feature_df[feature_cols].select_dtypes(include=["object"]).columns.tolist()

['gender_standard',
 'contract_type_standard',
 'signup_date',
 'last_login_date',
 'last_login_day_name',
 'usage_group',
 'gender',
 'contract_type']

In [87]:
categorical_candidates = [
    "gender",
    "gender_standard",
    "contract_type",
    "contract_type_standard",
    "usage_group"
]
categorical_cols = [
    col for col in categorical_candidates
    if col in feature_cols
]
print("categorical_cols:", categorical_cols)

categorical_cols: ['gender', 'gender_standard', 'contract_type', 'contract_type_standard', 'usage_group']

In [88]:
numeric_cols = [
    col for col in feature_cols
    if col not in categorical_cols
]
print("numeric_cols:", numeric_cols)

numeric_cols: ['age', 'monthly_fee', 'usage_days', 'support_calls', 'signup_date', 'last_login_date', 'signup_year', 'signup_month', 'last_login_dayofweek', 'last_login_day_name', 'days_since_signup', 'days_since_last_login', 'age_was_missing', 'monthly_fee_was_missing', 'gender_was_missing', 'contract_type_was_missing', 'monthly_fee_outlier', 'support_calls_outlier', 'is_high_fee', 'is_short_user', 'has_many_support_calls', 'is_long_contract', 'fee_per_usage_day', 'support_call_flag', 'long_usage_flag']

In [89]:
feature_type_summary = pd.DataFrame({
    "column": feature_cols,
    "dtype": [str(feature_df[col].dtype) for col in feature_cols],
    "role": [
        "categorical" if col in categorical_cols else "numeric_or_other"
        for col in feature_cols
    ]
})
feature_type_summary

                       column    dtype              role
0                         age    int64  numeric_or_other
1                 monthly_fee    int64  numeric_or_other
2                  usage_days    int64  numeric_or_other
3               support_calls    int64  numeric_or_other
4             gender_standard      str       categorical
5      contract_type_standard      str       categorical
6                 signup_date      str  numeric_or_other
7             last_login_date      str  numeric_or_other
8                 signup_year    int64  numeric_or_other
9                signup_month    int64  numeric_or_other
10       last_login_dayofweek    int64  numeric_or_other
11        last_login_day_name      str  numeric_or_other
12          days_since_signup    int64  numeric_or_other
13      days_since_last_login    int64  numeric_or_other
14            age_was_missing    int64  numeric_or_other
15    monthly_fee_was_missing    int64  numeric_or_other
16         gender_was_missing    int64  numeric_or_other
17  contract_type_was_missing    int64  numeric_or_other
18        monthly_fee_outlier    int64  numeric_or_other
19      support_calls_outlier    int64  numeric_or_other
20                is_high_fee    int64  numeric_or_other
21              is_short_user    int64  numeric_or_other
22     has_many_support_calls    int64  numeric_or_other
23                usage_group      str       categorical
24           is_long_contract    int64  numeric_or_other
25                     gender      str       categorical
26              contract_type      str       categorical
27          fee_per_usage_day  float64  numeric_or_other
28          support_call_flag    int64  numeric_or_other
29            long_usage_flag    int64  numeric_or_other

In [90]:
FEATURE_DIR.mkdir(parents=True, exist_ok=True)
feature_csv_file = FEATURE_DIR / "customers_feature_20260607_v1.csv"
feature_parquet_file = FEATURE_DIR / "customers_feature_20260607_v1.parquet"
print("feature_csv_file:", feature_csv_file)
print("feature_parquet_file:", feature_parquet_file)

feature_csv_file: /home/soldesk/week2-reproducibility/data/feature/customers_feature_20260607_v1.csv
feature_parquet_file: /home/soldesk/week2-reproducibility/data/feature/customers_feature_20260607_v1.parquet

In [91]:
print("feature_df shape:", feature_df.shape)
print("feature_cols count:", len(feature_cols))
print("categorical_cols:", categorical_cols)
print("numeric_cols:", numeric_cols)
print("target_col:", target_col)
print("drop_cols:", drop_cols)

feature_df shape: (9, 32)
feature_cols count: 30
categorical_cols: ['gender', 'gender_standard', 'contract_type', 'contract_type_standard', 'usage_group']
numeric_cols: ['age', 'monthly_fee', 'usage_days', 'support_calls', 'signup_date', 'last_login_date', 'signup_year', 'signup_month', 'last_login_dayofweek', 'last_login_day_name', 'days_since_signup', 'days_since_last_login', 'age_was_missing', 'monthly_fee_was_missing', 'gender_was_missing', 'contract_type_was_missing', 'monthly_fee_outlier', 'support_calls_outlier', 'is_high_fee', 'is_short_user', 'has_many_support_calls', 'is_long_contract', 'fee_per_usage_day', 'support_call_flag', 'long_usage_flag']
target_col: churn
drop_cols: ['churn', 'customer_id']

In [92]:
feature_df.to_csv(feature_csv_file, index=False, encoding="utf-8")
print("CSV 저장:", feature_csv_file)
print("존재 여부:", feature_csv_file.exists())
print("파일 크기 bytes:", feature_csv_file.stat().st_size if feature_csv_file.exists() else None)

CSV 저장: /home/soldesk/week2-reproducibility/data/feature/customers_feature_20260607_v1.csv
존재 여부: True
파일 크기 bytes: 1789

In [93]:
feature_df.to_parquet(feature_parquet_file, index=False)
print("Parquet 저장:", feature_parquet_file)
print("존재 여부:", feature_parquet_file.exists())
print("파일 크기 bytes:", feature_parquet_file.stat().st_size if feature_parquet_file.exists() else None)

Parquet 저장: /home/soldesk/week2-reproducibility/data/feature/customers_feature_20260607_v1.parquet
존재 여부: True
파일 크기 bytes: 20888

In [94]:
feature_csv_check = pd.read_csv(feature_csv_file)
print("CSV check shape:", feature_csv_check.shape)
print("CSV same columns:", list(feature_csv_check.columns) == list(feature_df.columns))

CSV check shape: (9, 32)
CSV same columns: True

In [95]:
feature_parquet_check = pd.read_parquet(feature_parquet_file)
print("Parquet check shape:", feature_parquet_check.shape)
print("Parquet same columns:", list(feature_parquet_check.columns) == list(feature_df.columns))

Parquet check shape: (9, 32)
Parquet same columns: True

In [96]:
print("original:", feature_df.shape)
print("csv:", feature_csv_check.shape)
print("parquet:", feature_parquet_check.shape)

original: (9, 32)
csv: (9, 32)
parquet: (9, 32)

In [97]:
S3_BUCKET = os.getenv("S3_BUCKET", "edu-ai-lake")
S3_FEATURE_PREFIX = os.getenv("S3_FEATURE_PREFIX", f"users/{AUTHOR}/feature/customers/")
feature_metadata = {
    "day": "week2_day5",
    "lesson": "period4_feature_generation_and_storage",
    "author": AUTHOR,
    "created_at": datetime.now().isoformat(),
    "execution_environment": {
        "main": "local_pc_wsl2",
        "openshift_local_used": False,
        "openshift_local_connection": "same project structure and src/preprocess.py can be reused",
        "developer_sandbox_connection": "same environment variables and S3 prefixes can be reused",
        "g4dn_used": False,
        "g4dn_not_used_reason": "feature generation uses pandas and does not require GPU"
    },
    "input": {
        "clean_file": str(LOCAL_CLEAN_FILE.relative_to(BASE_DIR)),
        "clean_file_absolute": str(LOCAL_CLEAN_FILE),
        "s3_source_bucket": os.getenv("S3_BUCKET", ""),
        "s3_source_key": os.getenv("S3_CLEAN_KEY", ""),
        "s3_source_uri": f"s3://{os.getenv('S3_BUCKET', '')}/{os.getenv('S3_CLEAN_KEY', '')}"
    },
    "output": {
        "feature_csv": str(feature_csv_file.relative_to(BASE_DIR)),
        "feature_parquet": str(feature_parquet_file.relative_to(BASE_DIR)),
        "s3_feature_prefix": S3_FEATURE_PREFIX,
        "planned_s3_csv_uri": f"s3://{S3_BUCKET}/{S3_FEATURE_PREFIX.rstrip('/')}/{feature_csv_file.name}",
        "planned_s3_parquet_uri": f"s3://{S3_BUCKET}/{S3_FEATURE_PREFIX.rstrip('/')}/{feature_parquet_file.name}"
    },
    "feature_generation": {
        "source_dataframe_shape": list(df_clean.shape),
        "feature_dataframe_shape": list(feature_df.shape),
        "created_columns": created_columns,
        "created_feature_definitions": {
            "fee_per_usage_day": "monthly_fee divided by usage_days; zero usage_days is handled safely",
            "support_call_flag": "1 if support_calls > 0 else 0",
            "long_usage_flag": "1 if usage_days >= 180 else 0"
        },
        "safety_checks": {
            "fee_per_usage_day_missing_count": int(feature_df["fee_per_usage_day"].isna().sum()),
            "fee_per_usage_day_inf_count": int(np.isinf(feature_df["fee_per_usage_day"]).sum()),
            "support_call_flag_unique": sorted([int(x) for x in feature_df["support_call_flag"].unique().tolist()]),
            "long_usage_flag_unique": sorted([int(x) for x in feature_df["long_usage_flag"].unique().tolist()])
        }
    },
    "column_roles": {
        "target_col": target_col,
        "drop_cols": drop_cols,
        "feature_cols": feature_cols,
        "categorical_cols": categorical_cols,
        "numeric_cols": numeric_cols
    },
    "leakage_policy": {
        "target_is_not_feature": True,
        "customer_id_excluded": "customer_id" in drop_cols,
        "possible_leakage_columns_excluded": possible_leakage_columns,
        "test_data_not_used_in_period4": True
    },
    "file_format": {
        "csv": "human-readable and easy to inspect",
        "parquet": "efficient for analysis pipeline and model input"
    },
    "next_lesson": "train validation test split and leakage check"
}
feature_metadata_file = OUTPUT_DIR / "feature_metadata.json"
with open(feature_metadata_file, "w", encoding="utf-8") as f:
    json.dump(feature_metadata, f, ensure_ascii=False, indent=2)
print("feature metadata JSON 저장:", feature_metadata_file)
print("존재 여부:", feature_metadata_file.exists())

feature metadata JSON 저장: /home/soldesk/week2-reproducibility/outputs/feature_metadata.json
존재 여부: True

In [98]:
print("author:", feature_metadata["author"])
print("created_columns:", feature_metadata["feature_generation"]["created_columns"])
print("target_col:", feature_metadata["column_roles"]["target_col"])
print("feature_cols:", feature_metadata["column_roles"]["feature_cols"])
print("categorical_cols:", feature_metadata["column_roles"]["categorical_cols"])
print("numeric_cols:", feature_metadata["column_roles"]["numeric_cols"])

author: kim-juil
created_columns: ['fee_per_usage_day', 'long_usage_flag', 'support_call_flag']
target_col: churn
feature_cols: ['age', 'monthly_fee', 'usage_days', 'support_calls', 'gender_standard', 'contract_type_standard', 'signup_date', 'last_login_date', 'signup_year', 'signup_month', 'last_login_dayofweek', 'last_login_day_name', 'days_since_signup', 'days_since_last_login', 'age_was_missing', 'monthly_fee_was_missing', 'gender_was_missing', 'contract_type_was_missing', 'monthly_fee_outlier', 'support_calls_outlier', 'is_high_fee', 'is_short_user', 'has_many_support_calls', 'usage_group', 'is_long_contract', 'gender', 'contract_type', 'fee_per_usage_day', 'support_call_flag', 'long_usage_flag']
categorical_cols: ['gender', 'gender_standard', 'contract_type', 'contract_type_standard', 'usage_group']
numeric_cols: ['age', 'monthly_fee', 'usage_days', 'support_calls', 'signup_date', 'last_login_date', 'signup_year', 'signup_month', 'last_login_dayofweek', 'last_login_day_name', 'days_since_signup', 'days_since_last_login', 'age_was_missing', 'monthly_fee_was_missing', 'gender_was_missing', 'contract_type_was_missing', 'monthly_fee_outlier', 'support_calls_outlier', 'is_high_fee', 'is_short_user', 'has_many_support_calls', 'is_long_contract', 'fee_per_usage_day', 'support_call_flag', 'long_usage_flag']

In [99]:
created_columns_text = "\n".join([f"- {col}" for col in created_columns]) or "- 없음"
drop_cols_text = "\n".join([f"- {col}" for col in drop_cols]) or "- 없음"
feature_cols_text = "\n".join([f"- {col}" for col in feature_cols]) or "- 없음"
categorical_cols_text = "\n".join([f"- {col}" for col in categorical_cols]) or "- 없음"
numeric_cols_text = "\n".join([f"- {col}" for col in numeric_cols]) or "- 없음"
leakage_cols_text = "\n".join([f"- {col}" for col in possible_leakage_columns]) or "- 명확한 leakage 후보 없음"
feature_metadata_md = f"""# Day 5 4교시 Feature 데이터 생성 기록
## 1. 작성자
- author: {AUTHOR}
## 2. 오늘 주제
feature 데이터 생성 + 저장 구조 정리
## 3. 입력 데이터
| 항목 | 값 |
|---|---|
| clean file | {LOCAL_CLEAN_FILE.relative_to(BASE_DIR)} |
| clean shape | {list(df_clean.shape)} |
| 실행 환경 | 개인 로컬 PC WSL2 |
| OpenShift Local 사용 | 앱 배포 없음, 동일 구조 실행 가능성으로 연결 |
| g4dn.xlarge 사용 | 사용하지 않음 |
## 4. clean 데이터와 feature 데이터 차이
clean 데이터는 분석 가능한 정제 데이터이다.
feature 데이터는 모델 학습에 사용할 입력 데이터이다.
이번 교시에서는 clean 데이터를 기반으로 feature 데이터를 생성했다.
## 5. 생성한 파생 feature
{created_columns_text}
## 6. feature 정의
| feature | 정의 | 의미 |
|---|---|---|
| fee_per_usage_day | monthly_fee / usage_days | 사용일수 대비 월 요금 |
| support_call_flag | support_calls > 0 | 고객지원 문의 여부 |
| long_usage_flag | usage_days >= 180 | 장기 사용 고객 여부 |
## 7. target 컬럼
- target_col: {target_col}
target인 `{target_col}`은 예측해야 할 정답이므로 feature_cols에 포함하지 않는다.
## 8. 제외 컬럼
{drop_cols_text}
## 9. leakage 후보 컬럼
{leakage_cols_text}
## 10. feature 후보 컬럼
{feature_cols_text}
## 11. 범주형 컬럼
{categorical_cols_text}
## 12. 수치형 컬럼
{numeric_cols_text}
## 13. 저장 결과
| 파일 | 경로 |
|---|---|
| CSV | {feature_csv_file.relative_to(BASE_DIR)} |
| Parquet | {feature_parquet_file.relative_to(BASE_DIR)} |
## 14. S3 업로드 예정 위치
| 항목 | 값 |
|---|---|
| S3 feature Prefix | {S3_FEATURE_PREFIX} |
| 예정 CSV URI | s3://{S3_BUCKET}/{S3_FEATURE_PREFIX.rstrip('/')}/{feature_csv_file.name} |
| 예정 Parquet URI | s3://{S3_BUCKET}/{S3_FEATURE_PREFIX.rstrip('/')}/{feature_parquet_file.name} |
## 15. 값 검증 결과
| 항목 | 값 |
|---|---|
| fee_per_usage_day 결측치 수 | {int(feature_df["fee_per_usage_day"].isna().sum())} |
| fee_per_usage_day 무한대 수 | {int(np.isinf(feature_df["fee_per_usage_day"]).sum())} |
| support_call_flag unique | {sorted([int(x) for x in feature_df["support_call_flag"].unique().tolist()])} |
| long_usage_flag unique | {sorted([int(x) for x in feature_df["long_usage_flag"].unique().tolist()])} |
## 16. OpenShift Local 연결
이번 교시에서는 OpenShift Local에 앱을 배포하지 않았다.
하지만 feature 생성 로직을 `src/preprocess.py`에 분리했으므로,
같은 프로젝트 구조와 같은 `.env` 설정을 사용하면
OpenShift Local 또는 Developer Sandbox에서도 동일한 feature 생성 함수를 실행할 수 있다.
## 17. g4dn.xlarge 연결
이번 교시에서는 g4dn.xlarge를 사용하지 않았다.
feature 생성은 pandas 기반 CPU 작업이며 GPU가 필요하지 않다.
이후 GPU 실습에서는 이 feature 데이터 또는 split 데이터를 입력으로 사용할 수 있다.
## 18. 다음 교시 연결
5교시에서는 이번 교시에서 만든 feature 데이터를 기반으로
train / validation / test split을 수행한다.
중요한 점은 target 비율을 유지하고,
test 데이터를 마지막까지 아껴 두는 것이다.
"""
feature_metadata_md_file = OUTPUT_DIR / "feature_metadata.md"
feature_metadata_md_file.write_text(feature_metadata_md, encoding="utf-8")
print("feature metadata Markdown 저장:", feature_metadata_md_file)
print("존재 여부:", feature_metadata_md_file.exists())

feature metadata Markdown 저장: /home/soldesk/week2-reproducibility/outputs/feature_metadata.md
존재 여부: True

In [100]:
print("feature_df:", feature_df.shape)
print("target_col:", target_col)
print("drop_cols:", drop_cols)
print("feature_cols:", feature_cols)
print("categorical_cols:", categorical_cols)
print("numeric_cols:", numeric_cols)
print("feature csv:", feature_csv_file)
print("feature parquet:", feature_parquet_file)

feature_df: (9, 32)
target_col: churn
drop_cols: ['churn', 'customer_id']
feature_cols: ['age', 'monthly_fee', 'usage_days', 'support_calls', 'gender_standard', 'contract_type_standard', 'signup_date', 'last_login_date', 'signup_year', 'signup_month', 'last_login_dayofweek', 'last_login_day_name', 'days_since_signup', 'days_since_last_login', 'age_was_missing', 'monthly_fee_was_missing', 'gender_was_missing', 'contract_type_was_missing', 'monthly_fee_outlier', 'support_calls_outlier', 'is_high_fee', 'is_short_user', 'has_many_support_calls', 'usage_group', 'is_long_contract', 'gender', 'contract_type', 'fee_per_usage_day', 'support_call_flag', 'long_usage_flag']
categorical_cols: ['gender', 'gender_standard', 'contract_type', 'contract_type_standard', 'usage_group']
numeric_cols: ['age', 'monthly_fee', 'usage_days', 'support_calls', 'signup_date', 'last_login_date', 'signup_year', 'signup_month', 'last_login_dayofweek', 'last_login_day_name', 'days_since_signup', 'days_since_last_login', 'age_was_missing', 'monthly_fee_was_missing', 'gender_was_missing', 'contract_type_was_missing', 'monthly_fee_outlier', 'support_calls_outlier', 'is_high_fee', 'is_short_user', 'has_many_support_calls', 'is_long_contract', 'fee_per_usage_day', 'support_call_flag', 'long_usage_flag']
feature csv: /home/soldesk/week2-reproducibility/data/feature/customers_feature_20260607_v1.csv
feature parquet: /home/soldesk/week2-reproducibility/data/feature/customers_feature_20260607_v1.parquet

In [101]:
from pathlib import Path
import textwrap

# 현재 실행 위치가 notebook 또는 notebooks 폴더이면 부모 폴더를 프로젝트 루트로 사용
BASE_DIR = Path.cwd().parent if Path.cwd().name in ["notebook", "notebooks"] else Path.cwd()
BASE_DIR = BASE_DIR.resolve()

# reports/week2 폴더 준비
REPORT_DIR = BASE_DIR / "reports" / "week2"
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# 저장 파일 경로
period4_record_file = REPORT_DIR / "day5_period4_feature_generation_record.md"

# Markdown 기록 양식
period4_record_text = """
# 2주차 Day 5 4교시 실습 기록지

## 작성자

## 1. 오늘 주제

feature 데이터 생성 + 저장 구조 정리

## 2. 입력 데이터

- clean file:
- clean shape:
- S3 source URI:

## 3. clean 데이터와 feature 데이터 차이

- clean 데이터:
- feature 데이터:

## 4. target 컬럼

- target_col:

## 5. 제외 컬럼

- drop_cols:

## 6. 생성한 feature

### fee_per_usage_day

- 정의:
- 의미:
- 결측치 수:
- 무한대 수:

### support_call_flag

- 정의:
- 의미:
- unique 값:

### long_usage_flag

- 정의:
- 의미:
- unique 값:

## 7. feature 후보 컬럼

- feature_cols:

## 8. 범주형 컬럼

- categorical_cols:

## 9. 수치형 컬럼

- numeric_cols:

## 10. 저장 파일

| 구분 | 경로 |
|---|---|
| CSV | data/feature/customers_feature_20260607_v1.csv |
| Parquet | data/feature/customers_feature_20260607_v1.parquet |
| metadata JSON | outputs/feature_metadata.json |
| metadata Markdown | outputs/feature_metadata.md |

## 11. S3 업로드 예정 Prefix

- feature Prefix:

## 12. OpenShift Local 연결

- OpenShift Local에서 같은 feature 생성 코드를 실행하려면 무엇이 같아야 하는가?

## 13. g4dn 연결

- 이번 교시에서 g4dn을 사용하지 않는 이유는?
- 이후 GPU 실습에서 feature 데이터가 왜 필요한가?

## 14. 오늘 배운 핵심

-

## 15. 다음 교시에서 할 일

train / validation / test split + leakage 점검
"""

# 앞뒤 공백 정리 후 저장
period4_record_text = textwrap.dedent(period4_record_text).strip() + "\n"

period4_record_file.write_text(
    period4_record_text,
    encoding="utf-8"
)

print("Day 5 4교시 feature 생성 실습 기록지 저장:", period4_record_file)
print("존재 여부:", period4_record_file.exists())
print("상대 경로:", period4_record_file.relative_to(BASE_DIR))

Day 5 4교시 feature 생성 실습 기록지 저장: /home/soldesk/week2-reproducibility/reports/week2/day5_period4_feature_generation_record.md
존재 여부: True
상대 경로: reports/week2/day5_period4_feature_generation_record.md